### ISSUE TITLE
Release Reek v5!

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1000]
I labeled our existing pull requests and AFAIS we only have [2 breaking changes / PRs](https://github.com/troessner/reek/pulls?q=is%3Aopen+is%3Apr+label%3Abreaking-change) that are relevant for this release.
Let's get those 2 going as fast as possible and then release right away because those 2 are blocking other important features like [making Reek more resilient on incomprehensible source](https://github.com/troessner/reek/pull/996).

Lets also get into the habit of having an upgrade doc under docs/upgrades for every major release and link to it prominently in our README to make it easier on users.

WDYT?

**Comment by troessner** [comment]
BTW this is issue number 1000!

**Comment by mvz** [comment]
> release right away

As I mentioned, I'd like to play around with the progress option for a bit, say a week.

> upgrade doc

This would basically be an expanded version of what's already in the change log, with examples?

**Comment by troessner** [comment]
>> As I mentioned, I'd like to play around with the progress option for a bit, say a week.

Sorry, forgot about that, sure ;)

>> This would basically be an expanded version of what's already in the change log, with examples?

Yes! I believe this makes it a lot, a lot easier on users.

**Comment by troessner** [comment]
And this time, let's not make the same mistake like with Reek 4 and put both features in a Reek 5 branch. I just created "reek-5" and I'll point #997 to it later on. @jhubert can you do the same for #983 please?

**Comment by troessner** [comment]
#997 now has transformed into #1015 and is **not** breaking anymore.
Means that #983 is the only breaking change at the moment.

**Comment by mvz** [comment]
I think we can safely declare #983 non-breaking.

**Comment by troessner** [comment]
But what about all the plugins, e.g. for vim and sublime?
Did you have a look at those as well?

**Comment by mvz** [comment]
@troessner see https://github.com/troessner/reek/pull/983#issuecomment-252407552

**Comment by troessner** [comment]
>> @troessner see #983 (comment)

Yep, saw that one too late :)

**Comment by troessner** [comment]
Well, what do you know, we got away with all PR's being not breaking anything and we don't have anything breaking on the horizon, so I'm closing this one ;)
