### ISSUE TITLE
Making mutant completely optional

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1007]
Don't get me wrong, I love [mutant](https://troessner.svbtle.com/kill-all-the-mutants-a-deep-dive-into-mutation-testing-and-how-the-mutant-gem-works) but I feel the way we're treating the integration is too much. 

A 100% or close to 100% mutation spec coverage all the time is extremely exhausting, clubbing all fun to death and in general doesn't seem worth like it. I this was software for flying a rocket to Mars or controlling life support system I'd have a different opinion. But it's not.

And quite frankly, I noticed that this has become a psychological blocker for me when working on new features because I'm always afraid that working one hour on a feature results in 3 hours of spec'ing.

Not to mention that ever since we introduced our mutant policy every single pull request has a red build status. Every single one of them.

I'd suggest to make mutation coverage completely optional. 

Meaning that:

* it shouldn't be relevant for the merge status of a PR
* it shouldn't make our build fail

We can and should still run it on CI and of course we can and should run it locally at least once in the course of a PR to see if any big issues pop up. But that should be it.

WDYT?

**Comment by mbj** [comment]
> Not to mention that ever since we introduced our mutant policy every single pull request has a red build status. Every single one of them.

I'm totally biased, but I wounder if you should listen to the pain. Its totally possible to run mutant enabled builds on CI and I prove this via mutant itself. And mutant is a complex piece of software.

If you get constantly red builds it seems one of the following (or a combination) may be true:

* Your tests are weak
* Your code contains redundancy
* Test selection (as done by mutant) is to narrow for your testing strategy
* Your overall mutation testing strategy, and especially how you start applying mutation testing to a project that was not from day 0 using it is imperfect.
* Mutant sucks for all projects but mine

I'm happy to spend some time in an in-debt discussion, as I'm curious and expect that its a documentation mistake as many people wrote about mutants internals, or how to run mutant, but not on how to incorporate it into a development cycle. And I've not seen any team outside of mine that got a huge value feedback from mutant on CI so far.

I'd love to somehow result in something we could hand out to other teams to use the tool more efficiently.

**Comment by mbj** [comment]
> And quite frankly, I noticed that this has become a psychological blocker for me when working on new features because I'm always afraid that working one hour on a feature results in 3 hours of spec'ing.

I was there, 3y ago. And it dramatically changed when I realized to listen to the pain and change the implementation strategies to be driven by: How do mutation test this, not: How do I get the feature in.

The dramatic side effect are code bases you seem to like and blog about.

If you wanted: Lets pair for 60minutes and we screenshare on the reek code base. I expect we'll both learn something.

**Comment by troessner** [comment]
>> Your tests are weak
Your code contains redundancy
Test selection (as done by mutant) is to narrow for your testing strategy
Your overall mutation testing strategy, and especially how you start applying mutation testing to a project that was not from day 0 using it is imperfect.

All of those points are true 😆 
Our test set up sucks, no question. We're [actively](https://github.com/troessner/reek/pull/1001)[working](https://github.com/troessner/reek/pull/992) on this but there is still a long way to go.

>> or how to run mutant, but not on how to incorporate it into a development cycle.

Excellent observation, I also feel this is missing.

>> The dramatic side effect are code bases you seem to like and blog about.

I do! It's not about mutant being bad or anything, I just feel that our set up is not really ready for it. And with setup I basically mean this

>> Your tests are weak

and this

>>Your code contains redundancy

But I feel that we can live with the latter. Our bad spec set up is what's really killing us here. 

>> If you wanted: Lets pair for 60minutes and we screenshare on the reek code base. I expect we'll both learn something.

Appreciated for sure, thanks! Let's finish this discussion first and then come back to this :)

**Comment by mvz** [comment]
As I see it, the main problem is currently:

> * Test selection (as done by mutant) is too narrow for your testing strategy

In many cases, classes are tested by how they are used by other classes. For example, many of the methods on AST nodes mainly make sense by how they are used in the smell detectors, so were introduced to make specs on the smell detectors pass.

A smaller problem is that a few of mutant's mutations are more style-oriented. By that, I mean that, at least for our code base, they don't actually change the result of the code for any reasonable input. Examples are: `foo == 'bar'` being mutated to `foo.eql? 'bar'`, and `super` being mutated to `super()` for methods that take no parameters. Those mutations could only be killed by using a style of Ruby programming that to me feels awkward. As a result, the code stays as it is and mutant fails whenever that file is touched.

I'm sure the other points you mention also play a role, like:

> * Your tests are weak
> * Your code contains redundancy

However, those would be relatively easy to fix without restructuring the entire test suite.

**Comment by troessner** [comment]
>> A smaller problem is that a few of mutant's mutations are more style-oriented. By that, I mean that, at least for our code base, they don't actually change the result of the code for any reasonable input. Examples are: foo == 'bar' being mutated to foo.eql? 'bar', and super being mutated to super() for methods that take no parameters. Those mutations could only be killed by using a style of Ruby programming that to me feels awkward. As a result, the code stays as it is and mutant fails whenever that file is touched.

Fully agree on that - @mbj any plans to make it configurable which mutators are run by mutant?

**Comment by mbj** [comment]
> Fully agree on that - @mbj any plans to make it configurable which mutators are run by mutant?

No. Not on my free OSS time. And I'd even resist a lot of someone would try to pay me for that feature.

Its by far the most popular feature request, and I'd make many users happy to fulfill it, but likely its not in that users interest, even if they do not agree to my opinion. But I've a deeper insight typically on what strategy makes sense in the long-term than those users.

I see how it looks appealing for "Ohh, lets not worry about the pain a certain operator introduces for now, lets disable it", but if that route is taken the message the tool delivers is by far not as strong and it may even better to not use it at all.

`#==` vs `#eql?` had been discussed in the mutant community very often and its now universally agreed its a really valuable mutation (note mutant even tries to mutate to `#equal?`) these kinds of operators, and the axioms behind it probably deserve a dedicated blog post. I can assure you, its not a style mutation, mutant does not have these typically. Its a bitter pill to swallow, but to my personal experience (and the teams that use mutant in a commercial environment) its worth to swallow it.

> being mutated to super() for methods that take no parameters.

That one is nasty and I agree to fix it. There is even a ticket for it already.

> I this was software for flying a rocket to Mars or controlling life support system I'd have a different opinion.

You should NOT write such software in Ruby, ever. I actually think software should not be written in Ruby at all, but that is a different topic. I personally think working with Ruby only makes sense on !greenfield. Mutant is a tool I created to get legacy code bases under control, and the strategy to do so is not documented at all anywhere. But again my offer to spend 60+ minutes on pairing to explain how I'd approach mutation testing with reek still stands. Maybe that strategy than reaches blog post form some day ;).

**Comment by troessner** [comment]
>> I see how it looks appealing for "Ohh, lets not worry about the pain a certain operator introduces for now, lets disable it", but if that route is taken the message the tool delivers is by far not as strong and it may even better to not use it at all.

But it's a quality tool. And quality is subjective. Software development is a lot closer to writing a book than it will ever be to designing car.
Rubocop, Reek and a lot of other tools allow users to define exceptions because they make the concession that quality is subjective and the tool is not the police. mutant takes a different stance and I respect that. But this doesn't mean it's more right than other tools because this:

>> but if that route is taken the message the tool delivers is by far not as strong and it may even better to not use it at all.

would apply to all others as well.

>> You should NOT write such software in Ruby, ever. 

Sure you can and why not, you can write shit programs in all languages, but let's not go down this road ;)

**Comment by mbj** [comment]
> Rubocop, Reek and a lot of other tools allow users to define exceptions because they make the concession that quality is subjective and the tool is not the police. mutant takes a different stance and I respect that.

In mutant you can also make exceptions, `--ignore-subject` flags recorded in the repo is what I recommend for onboarding to projects that did not do mutation testing from day one.

But at operator level its too fine grained. IMO.

**Comment by mbj** [comment]
> would apply to all others as well.

Yes, imagine you'd disable 90% of rubocop cops, you'll end up spending more time maintaining the fine grained exclusion list, than fixing problems. If you disable the most painful mutation operators, you should consider to not use the tool instead.

**Comment by mvz** [comment]
> `#==` vs `#eql?` had been discussed in the mutant community very often and its now universally agreed its a really valuable mutation

I'm very interested in this discussion, do you have any pointers to where I can read up on it?

**Comment by mvz** [comment]
Also, @mbj, I wouldn't mind helping improve mutant's documentation while my confusion is still fresh. Do you have any place where you would like the documentation to end up? (e.g., comments in the mutators, wiki, github pages).

**Comment by mbj** [comment]
> Also, @mbj, I wouldn't mind helping improve mutant's documentation while my confusion is still fresh. Do you have any place where you would like the documentation to end up? (e.g., comments in the mutators, wiki, github pages).

There is no formal structure yet, suggestions welcome. Most work was done so far in the README, but it grows to big.

**Comment by mbj** [comment]
> I'm very interested in this discussion, do you have any pointers to where I can read up on it?

Its very likely still in the mutant Slack channel, but we only have a limited amount of history there. Feel free to re-ignite it.

**Comment by troessner** [comment]
Closing this one since Mutant is optional now.
