### ISSUE TITLE
Handle or fail tests when smell detectors return nil

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1027]
When `#sniff` returns `nil` instead of `[]`, our tests still pass but we output our please-report-an-exception text. We should either allow `nil` output or fail tests in this case.

I found this with mutant when implementing #1026.

**Comment by troessner** [comment]
>> We should either allow nil output or fail tests in this case.

👍 for the latter - I think this should fail our tests.

**Comment by mvz** [comment]
If no-one has any other input, I'll have a go at implementing this.

**Comment by troessner** [comment]
:+1

**Comment by backus** [comment]
Big :thumbsup: for this. Having failing tests not look like normal RSpec failures was quite confusing when I was making my first contribution
