### ISSUE TITLE
Re-introduce Mutant

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1030]
With #1007 implemented I'd love to discuss how we can re-introduce mutant "the right way".

**Comment by mvz** [comment]
I recently added mutant to a private project and decided to go through all the classes and fix mutant issues in each one, rather than just adding the task and waiting for the build to break. This was very effective, but it is a a small project that I purposefully developed using quite strict TDD, and there was not a lot broken.

Based on this, I think we should start making one smell detector mutant-green, adding a mutant task that tests just that smell using whitelisting, and then continue fixing and adding detectors and then on with the rest. I'm sure we can switch to blacklisting at some point, but that's for later.

**Comment by troessner** [comment]
I'm hesitant. As long as almost all PRs break because of "to_s" vs "to_str" or "==" vs "===" I don't think this will work. The Mutant community is of the opinion that those mutations are meaningful and I would disagree.
It would be great if Mutant would be configurable but we already discussed and it doesn't seem be an option in the near future.

What's your take on this problem @mvz ?

**Comment by mvz** [comment]
In my private project `#==` vs `#eql?` vs `#equal?`, and `#first` vs. `#last` were the most difficult to kill. I do see the usefulness of both mutations, however.

The first one forces you to think about your equality implementations and/or about the type of parameters you expect. For example, if you accept integers as parameters, you should think about whether you accept floats that have the same value. For objects of classes you own, you should think about what conversions you allow, and whether you allow objects of subclasses to be equal to objects of the superclass.

The `#first` vs `#last` mutation forces you to consider whether the object you call these methods on really should be an enumerable.

I didn't encounter `to_s` vs `to_str` in that project, so I can't comment on how easy it is to kill.

Finally, I agree that re-adding mutant may make more PRs red in the end, but I think that will only start being a major concern once we have stopped whitelisting and started blacklisting. By that time, we should have more experience with these tricky mutations, resulting in a more well-founded opinion on them. We can always decide not to start blacklisting in the end.

**Comment by troessner** [comment]
Ok, fair enough.

Then I'm fine with proceeding like you suggested:

>> Based on this, I think we should start making one smell detector mutant-green, adding a mutant task that tests just that smell using whitelisting, and then continue fixing and adding detectors and then on with the rest. I'm sure we can switch to blacklisting at some point, but that's for later.

**Comment by backus** [comment]
> The `#first` vs `#last` mutation forces you to consider whether the object you call these methods on really should be an enumerable.

I had a long discussion with Markus on this mutation and I grew to agree with it. This mutation will always be frustrating if you are using libraries which, in certain contexts, return an array with exactly one element. The solution is to implement something like this `Reek::Util.one`:

```ruby
module Reek
  module Util
    # Error raised by `Util.one` if size is not one
    SizeError = Class.new(IndexError)

    # Return only element in array if it contains exactly one member
    #
    # @param array [Array]
    #
    # @return [Object] first entry
    def self.one(array)
      return array.first if array.one?

      fail SizeError, "expected size to be exactly 1 but size was #{array.size}"
    end
  end
end
```

I initially objected to this mutation because it basically forces you to write this method but I agree that I wouldn't have a problem with this mutation if ruby provided an `Enumerable#one` method by default. This framing makes me realize that the pain of this mutation is a ruby core library pain and not an inconvenience that mutant itself is forcing on me.

**Comment by backus** [comment]
> Finally, I agree that re-adding mutant may make more PRs red in the end, but I think that will only start being a major concern once we have stopped whitelisting and started blacklisting. By that time, we should have more experience with these tricky mutations, resulting in a more well-founded opinion on them. We can always decide not to start blacklisting in the end.

You can also probably build up a "killing mutations" section in your CONTRIBUTING.md. These explanations could probably also eventually make it upstream to mutant. Markus eventually wants to add explanation/context for mutations that the tool can present.

**Comment by backus** [comment]
> As long as almost all PRs break because of "to_s" vs "to_str"

This is a category of mutations. So you aren't surprised, there are several mutations like this:

* `:to_s` → `:to_str`
* `:to_i` → `:to_int`
* `:to_a` → `:to_ary`
* `:to_h` → `:to_hash`

These have been discussed a lot. Checkout https://github.com/mbj/mutant/issues/447 and https://github.com/mbj/mutant/issues/218 for example.

Basically the argument is that, if an object responds to something like `#to_str`, that means that it is saying that it is basically an string object. Likewise for `#to_int` in that only other numeric types will respond to `to_int` where as a whole slew of objects respond to `#to_i`. When I see `#to_int` I think "ok something that is already a number is being turned into an integer" where as if I see `#to_i` I think "ok this might be a numeric type but it can also be `nil`, `String`, `Process::Status`, `Time`, `File`, or any `IO`.

**Comment by mvz** [comment]
@backus thanks for your explanations. I have a question about the implementation of `#one` you used. I see it uses `#first` so won't it suffer from the same mutations that you're trying to kill in the first place? I came up with an implementation like the following at some point, but I'm not sure I like it better:

```ruby
   element, *rest = *array
   raise if rest.any?
```

**Comment by backus** [comment]
@mvz the test for that method would be subject to the same mutation but I then kill that by passing in something like `instance_double(Array, first: "value")`

**Comment by mvz** [comment]
I've thought about this a bit more and I changed my mind. Until it is possible to disable mutations like `==` to `equal?` and `[]` to `fetch`, I think mutant (unintentionally, I'm sure) enforces a particular style of coding that I find unpleasant both to read and to write. This is particularly annoying for the domains where these methods yield essentially the same result. Since one of the reasons I write in Ruby is that it is a pleasure to write in, I think a tool that reduces that pleasure is counterproductive.

**Comment by troessner** [comment]
I agree. @mbj would you be willing to accept PRs that make mutators configurable?
I mean, what's the point of a tool if people shy away from it because they consider it too rigid ;)

**Comment by mbj** [comment]
> I agree. @mbj would you be willing to accept PRs that make mutators configurable?
> I mean, what's the point of a tool if people shy away from it because they consider it too rigid ;)

No, and I've argued this many times, I should put up a blog post on why its a *really* bad idea to allow configuration of these in my current constraints.

**Comment by mbj** [comment]
> I've thought about this a bit more and I changed my mind. Until it is possible to disable mutations like == to equal? and [] to fetch, I think mutant (unintentionally, I'm sure) enforces a particular style of coding that I find unpleasant both to read and to write. This is particularly annoying for the domains where these methods yield essentially the same result. Since one of the reasons I write in Ruby is that it is a pleasure to write in, I think a tool that reduces that pleasure is counterproductive.

These are not style, these are valid semantic reductions.

**Comment by troessner** [comment]
>> No, and I've argued this many times, I should put up a blog post on why its a really bad idea to allow configuration of these in my current constraints.

Ok, I'm trying to understand you here:
Following that rationale, do you think it's bad that Reek allows disabling smell detectors since they only care about semantics?

**Comment by mbj** [comment]
> Following that rationale, do you think it's bad that Reek allows disabling smell detectors since they only care about semantics?

No. You can provide this feature at your OSS time for your users. I cannot. That simple. My policy for OSS is:

* Only support features I use for myself or one of my clients.

**Comment by mvz** [comment]
> These are valid semantic reductions.

I agree, but for many types they are equivalant and force the use of particular methods. This means they have an influence on style.

**Comment by mvz** [comment]
> Only support features I use for myself or one of my clients.

That is a very sensible policy.

**Comment by troessner** [comment]
>> Only support features I use for myself or one of my clients.

That's your right as an author, but you **do** want your software to be used (otherwise you wouldn't even bother to have this discussion) and by being so strict about it you'll basically kill that completely (since I'm pretty sure that not having the possibility to opt out of any mutator will alienate a lot, a lot of users).

So yes, that is fully up to you to decide, but I can have an opinion about this, and my opinion about this is that you'll harm your project. Your basically going down the "it's my way or the highway / zero compromise" road which is not the road to success. Social life (like open source!) is about tradeoffs. E.g. we decided to make Reek's UtilityFunction optional for non-public methods which was a great choice in hindsight because there were just too many justified usages and tradeoffs.

And finally: What good is a tool about code quality if it alienates people so that they won't use it at all? (Again, I refute the "I'm doing that for myself and my clients" statement, you want people to use it, otherwise we would neither have this discussion nor would there be any point of making it open source).

**Comment by backus** [comment]
Someone started a fork recently which removes most of the mutations you have mentioned not liking in this thread: https://github.com/baseballlover723/mutant

**Comment by mvz** [comment]
@backus that could be useful and I'll see where it goes. I'd prefer a version where I can mark mutations as not relevant in the given code base.

**Comment by mbj** [comment]
> That's your right as an author, but you do want your software to be used (otherwise you wouldn't even bother to have this discussion)

Right now I'm happy if my software is useful for others, but I do not sacrifice efficiency formyself to get others using it.

**Comment by mbj** [comment]
OT: I've yet to be shown an example where these mutations are not universally valid. If that examples exists this discussion will go different, as I'd see it favorable to have the configurability as my own use cases will be affected.

Can we talk about the "offending" mutations and counter examples before trying to change my OSS development rules?

**Comment by troessner** [comment]
>> Can we talk about the "offending" mutations and counter examples before trying to change my OSS development rules?

But it's **not** about changing **your** development rules. It's about making Mutant flexible enough so people can use to ensure that their development guidelines are met.
That would you still allow to ensure the integrity of your set of rules.
Making mutators optional wouldn't affect you at all - you could just choose to not do it :)

>> OT: I've yet to be shown an example where these mutations are not universally valid.

Ok, so let's assume that they all are valid in the sense that I might introduce a bug when not taking care of them. Maybe that's fine for us? That again comes back to what I mentioned about tradeoffs.

You can go for a 100% mutation test coverage but that decreases development speed.
So I, and that is a personal decision, want to use mutant but in a way that gives me a good compromise between development speed and confidence in my code.
And yes, that means willingly accepting some margins of error.

Why not give it a shot?

**Comment by mbj** [comment]
> Making mutators optional wouldn't affect you at all - you could just choose to not do it :)

Each single line of code I add to my projects increases the amount of maintainership. 

Before you argue about a feature: Can we discuss the cases you found where these mutations are style?

**Comment by mbj** [comment]
> Why not give it a shot?

Because its against my OSS rules to do something I do not need nor my clients need. Hence I'm willing to explore if my clients need it, so please get me the exact case where these mutations are style so I can discover a need.

**Comment by troessner** [comment]
>> Each single line of code I add to my projects increases the amount of maintainership.

Ack. That is the part of the deal you need to do on your side if you want to have people using your software. Not all requests, but at least the popular ones that are still in line with the overall goals (i believe my request from above is).

>> Before you argue about a feature: Can we discuss the cases you found where these mutations are style?

We don't have to. I agree that they are not style, but semantics. Doesn't change my statement - we still would like to ignore those mutators. As outlined above, we are willing to do this tradeoff for the sake of speed and ....uhm, developer joy :)

>> Because its against my OSS rules to do something I do not need nor my clients need. Hence I'm willing to explore if my clients need it, so please get me the exact case where these mutations are style so I can discover a need.

You're creating a logical contradiction out of which you can't escape. 

Premise [A]: You want people to use Mutant. And **not** just your clients. Otherwise we wouldn't have this conversation. I don't understand why you always fall back to the "my clients needs" argument when it's clear that it's not just about your clients.

Premise [B]: If Mutant is not at least **a little bit** configurable it is too rigid and people won't use.

We can argue all day long but [B] will always contradict [A].

**Comment by mvz** [comment]
> please get me the exact case where these mutations are style

Our implementation of ModuleInitialize is an example:
https://github.com/troessner/reek/blob/master/lib/reek/smell_detectors/module_initialize.rb#L26

There are some mutations there that are easy to kill and improve the code, but after that the following mutation remains:

```
-    if (node.name.to_s == "initialize")
+    if node.name.to_s.eql?("initialize")
```

The existing code can be improved by changing it to `if node.name == :initialize`, but then I get the follwing two mutations:

```
-    if (node.name == :initialize)
+    if node.name.eql?(:initialize)
[...]
-    if (node.name == :initialize)
+    if node.name.equal?(:initialize)
```

**Comment by mvz** [comment]
The improvements mentioned above are in this PR: #1126.

**Comment by mbj** [comment]
So you consider using a comparision operator that would silently accept other types in many implementations (such as `#==`) a style issue? If so, I think unless we agree on that one we cannot find common ground.

My development strategy is always to remove unspecified semantics. Replacing coercing operators with non coercing operators is an improvement to the health of the code base. Its not a style issue. I do not care of the concrete syntax is more or less appealing (style): I care about semantics first than style.

> Ack. That is the part of the deal you need to do on your side if you want to have people using your software. 

I want people to use my software if they think it adds value to their process. If they do not agree to the choices I make based on axioms (I described one above) I prefer having those people NOT to use my software. I'm fine getting my axioms challenged, and act on results of challenged axioms.

> Premise [A]: You want people to use Mutant. And not just your clients. Otherwise we wouldn't have this conversation. I don't understand why you always fall back to the "my clients needs" argument when it's clear that it's not just about your clients.

I want people to use mutant to discover problems that would affect my clients, and the broadening of audience I got from releasing mutant "as is" got me that. I do not many anyone but myself and clients happy, sorry.

> Premise [B]: If Mutant is not at least a little bit configurable it is too rigid and people won't use.

Its configurable to the degree I need it to be effective for my use cases, example I removed explicit coverage expectations, as they proved to be ineffective for my use cases compared to fine grained subject ignores.

**Comment by troessner** [comment]
I understand your arguments, I really do. 
However I feel that you're way to stubborn since I believe life is about compromises.

I do respect your opinion but in this case I don't see any common ground for us and we'll probably not re-introduce Mutant, as sad as I think it is.

**Comment by mbj** [comment]
> However I feel that you're way too stubborn since I believe life is about compromises.

Thats your opinion, and its fine you tell me that one. See my perspective: OSS took a significant amount of my lifetime for a minimum gain. Hence I decided to limit it.

> I do respect your opinion but in this case I don't see any common ground for us and we'll probably not re-introduce Mutant, as sad as I think it is.

NP.

**Comment by backus** [comment]
@troessner you guys could probably make a third party gem happen though that could implement filtering. Basically, we could make a small implementation change in mutant that would change `Mutant::Mutator` to be injected (via the [default config](https://github.com/mbj/mutant/blob/master/lib/mutant.rb#L209-L241)). I talked to @mbj about injecting the mutator and he is open to that since he doesn't like having to stub constants in specs.

A third party gem could then inject its own mutator which would wrap `Mutant::Mutator` and apply a filter. This wouldn't be incredibly simple since, to do the filter well, you would have to "diff" the input AST against each output AST to figure out which mutation was emitted. I think this is doable though.

**Comment by mvz** [comment]
> So you consider using a comparision operator that would silently accept other types in many implementations (such as #==) a style issue? If so, I think unless we agree on that one we cannot find common ground.

In the case where I as the implementor know there is no difference in practice for the types that actually occur, I would argue that it *becomes* a style issue. For these cases, there is no reasonable test setup that will kill the mutant, yet the code is both perfectly fine and not overcomplicated for the functionality provided.

I do not know of any implementations that will return true on `#== :foo` unless the receiver actually is a symbol for any of the core classes. Additionally, `#==` is slightly faster for, e.g., integers on MRI 2.3.

I want to stress that I do understand your desire to weed out cases where `#==` versus `#eql?` makes an actual difference. I would just like to be able to tell mutant about cases where it does not, and where it cannot figure this out by itself.

**Comment by mvz** [comment]
@backus I may have a look at that option. It will be some time before I get the chance, though.

**Comment by mbj** [comment]
> In the case where I as the implementor know there is no difference in practice for the types that actually occur, I would argue that it becomes a style issue. For these cases, there is no reasonable test setup that will kill the mutant, yet the code is both perfectly fine and not overcomplicated for the functionality provided.

You transform a value to compare equivalency via a weak operator `left.to_s ==" right"` is 2 times less correct than `left.equal?(:most_primitive_literal)`, weak equivalency test + testing on presentation not the original value. That would be the most redundancy free implementation of what you can specify from your tests. Hence you should use this.

You all agree that a mutation from `a; b` to `a` is okay, because if we can remove semantics of `b` without counter examples in our tests we should not have ´b` in the first place.

This case is not different, at all. As you may have a solution via a mutant plugin, I'm fine to stop arguing here.

**Comment by mvz** [comment]
@troessner I think we can close this for now until such time as I've been able to take a look at @backus' suggestion

**Comment by troessner** [comment]
Ack!
