### ISSUE TITLE
Kill the `examine` / `report_on` architecture.

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1040]
The nested calling of `examine` and `report_on` is making it very hard to tease apart the Examiner / SmellRepository / WarningCollector classes. Also, it means we're continually updating the state of some collector class.

I'd like to go from this to a more functional style, where `#examine` just returns a collection of smells.

As part of this, I'd like to also clean up the division of labour between `Examiner#examine` and `SmellRepository#examine`: For some reason they interface by passing individual context objects, making at lease `SmellRepository#examine` very hard to re-use.

**Comment by mvz** [comment]
This will probably be a breaking change :smile:.

**Comment by troessner** [comment]
Yes, I couldn't agree. The current state of this is really bad. Quite some methods we only call for sideeffects and / or they can update an object that is buried down deep deep deep in some other objects. 
👍 for a more functional style.

**Comment by troessner** [comment]
Closing this one with #1041 merged!
