### ISSUE TITLE
Problems with 'refers to X more than self (maybe move it to another class?)'

### ISSUE THREAD

**Issue by alepaez** [troessner/reek#1043]
Hello Guys!

I'm stuck trying to make this code pass on reek 4.4.0 tests, can you guys gimme a hint on how this code should look like?

Reek is giving this warnings:

app/use_codes/utl_validate_fraud_analysis_params.rb -- 4 warnings:
  [55, 56]:FeatureEnvy: UTLValidateFraudAnalysisParams#validate_hash refers to required more than self (maybe move it to another class?) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]
  [47, 49]:FeatureEnvy: UTLValidateFraudAnalysisParams#validate_params refers to namespace more than self (maybe move it to another class?) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]
  [54]:LongParameterList: UTLValidateFraudAnalysisParams#validate_hash has 4 parameters [https://github.com/troessner/reek/blob/master/docs/Long-Parameter-List.md]
  [44]:LongParameterList: UTLValidateFraudAnalysisParams#validate_params has 4 parameters [https://github.com/troessner/reek/blob/master/docs/Long-Parameter-List.md]

```
# Validate multilevel nested fraud analysis params
class UTLValidateFraudAnalysisParams
  REQUIRED_PARAMS = [
    :value, :id,
    {
      payer: [
        :name,
        :cpf_cnpj,
        :phone,
        :phone_prefix,
        :email,
        address: [
          :street,
          :number,
          :city,
          :state,
          :country,
          :zip_code
        ]
      ]
    }
  ].freeze

  def initialize(parameters)
    @data = parameters.clone
    @missing_params = []
  end

  def call
    self.class.validate_params(REQUIRED_PARAMS, @data, [], self)
    @missing_params
  end

  def add_missing_param(param, namespace)
    namespace = "#{namespace}." if !namespace.blank?
    @missing_params.push("#{namespace}#{param}".strip)
  end

  private

  class << self

    def validate_params(required, parameters, namespace, target)
      required.each do |req|
        if req.class == Hash
          validate_hash(req, parameters, namespace.clone, target)
        else
          (target.add_missing_param(req, namespace.join("."))) if parameters[req].blank?
        end
      end
    end

    def validate_hash(required, parameters, namespace, target)
      required.keys.each do |key|
        (validate_params(required[key], parameters[key], namespace.push(key), target))
      end
    end

  end


end
```

Thank you very much!

**Comment by troessner** [comment]
Quite often Reek will not discover smells that are literally fixable in the place they occured but rather hint at flaws in your overall architecture. Or to put it differently: To fix the reported smells you rather need to fix the architecture.
Skimming your code I can already see a couple of questionable things, especially:

```Ruby
  def call
    self.class.validate_params(REQUIRED_PARAMS, @data, [], self)
    @missing_params
  end
```

So you're having an instance method that calls a ..... class method but then even passes the instance itself to it. That is spaghetti code and goes against OOP. Why not only instances?

Another bad spot is:

```Ruby
  private

  class << self
```

Why is that a class method? Think about it: You have a class and 80% of this class are not instance methods but class methods. Are you sure you're not rather looking for a `Module` and `module_function`? 

What does UTL stand for in the class name? Util? That's hinting at an SRP violation already. Or in other words: This class acts like a grab bag of unrelated features and responsibilities.

Hope this helps you refactoring this ;)

**Comment by alepaez** [comment]
Thank you very much troessner! Your tips were very valuable!
