### ISSUE TITLE
UnusedParameters will swallow UncommunicativeParameterName

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1045]
> > echo "def m(a); end" | reek
> > STDIN -- 2 warnings:
> >   [1]:UncommunicativeMethodName: m has the name 'm' 
> >   [1]:UnusedParameters: m has unused parameter 'a' 
> > echo "def m(a); a; end" | reek
> > STDIN -- 2 warnings:
> >   [1]:UncommunicativeMethodName: m has the name 'm' 
> >   [1]:UncommunicativeParameterName: m has the parameter name 'a'

**Comment by mvz** [comment]
IIRC, this is intentional.

**Comment by troessner** [comment]
But what's the rationale behind it?

**Comment by mvz** [comment]
I'll see if I can dig that up.

**Comment by mvz** [comment]
This was introduced in cd311ac9. The general idea is that we allow names starting with `_` only if they are unused.

**Comment by mvz** [comment]
Yes, the implementation done back then was a bit of a hack to avoid a different set of regexp depending on whether a parameter is used or not.

**Comment by troessner** [comment]
Great, then let's fix this ;)
