### ISSUE TITLE
Missing documentation for instance variable assumption

### ISSUE THREAD

**Issue by backus** [troessner/reek#1049]
Running the latest version of reek on my codebase reported an `InstanceVariableAssumption` smell but the link (https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md) 404s

**Comment by mvz** [comment]
:scream:

**Comment by troessner** [comment]
Pretty bad that we missed this in #1017 😆 
I'll come up with a PR to fix this in the next couple of minutes.
