### ISSUE TITLE
Define a checklist what is required for a new smell detector

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1050]
Coming from #1049

**Comment by waldyr** [comment]
From the top of my head:

- [ ] Documentation
- [ ] Cucumber Scenario
- [ ] Rspec tests
- [ ] Smell Detector (with target expression)

**Comment by mvz** [comment]
:-1: for Cucumber scenario, at least not a separate one. I don't think it's needed, and we're trying (and failing) to bring down the number of scenarios. Maybe we can add new smells to the `samples.feature` feature.

:+1: for the rest.

**Comment by backus** [comment]
This is sort of off topic but it would be nice if you could do something like I did here https://github.com/nevir/rubocop-rspec/pull/174 that would basically ensure that you only have to write examples for smells once. Would reduce the likelihood of something like #1049

**Comment by mvz** [comment]
@backus yes that would be nice.

**Comment by troessner** [comment]
wip in #1072
