### ISSUE TITLE
InstanceVariableAssumption problems with inheritance

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1051]
Given

```Ruby
class Parent
  def initialize(omg)
    @omg = omg
  end
end

class Child < Parent
  def initialize(omg)
    super
  end

  def foo
    @omg
  end
end
```

Reek would report:

>>
  [7]:InstanceVariableAssumption: Child assumes too much for instance variable @omg [https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md]

I don't think we should report here. I can't see anything dirty about it.
For me this smell detector was about doing things like this:

```Ruby
class Foo
  def bar
    @hola = 42
  end
  
  def baz
    @hola + 99
  end
end
```

but **not** about the example above.

What do you guys think?

**Comment by mvz** [comment]
The example you give was part of what I had in mind. The idea is that you should create an `attr_reader` to use `@omg` in the subclass.

**Comment by troessner** [comment]
>> The idea is that you should create an attr_reader to use @omg in the subclass.

But that's a separate smell, isn't it?
That is basically the DirectAccess smell we discusses [here](https://github.com/troessner/reek/issues/483), right?

**Comment by mvz** [comment]
> That is basically the DirectAccess smell we discusses here, right?

That one seems to be about assigning, and can be about an ivar that is introduced in the same class.

> How about adding my example and your solution [...] to the wiki docs for InstanceVariableAssumption

Yes, makes sense since without it the explanation is really incomplete.
