### ISSUE TITLE
Error for certain malformed smell suppressions

### ISSUE THREAD

**Issue by backus** [troessner/reek#1054]
A while back after reading the [Smell Suppression](https://github.com/troessner/reek/blob/master/docs/Smell-Suppression.md) doc I thought I would be clever and apply my new knowledge about smell suppression. I added the following comment:

```
# :reek:TooManyStatements { max_statements: 8 }
```

Fast forward to today: I'm grepping through our code and removing stale `:reek:*` comments. I get to this comment and check if I can lower the number. I change it to `# :reek:TooManyStatements { max_statements: 7 }` and reek still passes, `max_statements: 6`, `5`, `4`, etc.. until I hit zero.

After a moment of confusion I pull the docs up and realize the mistake. The correct original comment would have been

```
# :reek:TooManyStatements: { max_statements: 8 }
```

subtle! Here is the diff if you can't see it:

```diff
--- incorrect
+++ corrected
@@ -1 +1 @@
-# :reek:TooManyStatements { max_statements: 8 }
+# :reek:TooManyStatements: { max_statements: 8 }
```

Could reek help me in this situation? I imagine I'm not the only person that has done this.

**Comment by troessner** [comment]
Hmmm, of the top of my head I believe we could mitigate this a lot by making our [configuration regex](https://github.com/troessner/reek/blob/master/lib/reek/code_comment.rb#L10) more lenient.

I'd definitely would be in favor of this as well.

Pull request welcome if not I can look into this in a couple of days as well.

**Comment by troessner** [comment]
Fun fact: We also fucked this up, e.g. [here]{https://github.com/troessner/reek/blob/master/lib/reek/ast/node.rb#L89}

**Comment by troessner** [comment]
Looking into this in #1068
