### ISSUE TITLE
Is there a way to turn off all smells so as to surgically turn on one or two?

### ISSUE THREAD

**Issue by pitosalas** [troessner/reek#1057]
[Apologies if you don't like to have questions in this forum. Just let me know the more appropriate forum]

I want to turn off all smell detections and then only turn on one or two. Other than disabling all of them one by one is there a better way? Thanks!

**Comment by troessner** [comment]
I want to turn off all smell detections and then only turn on one or two. Other than disabling all of them one by one is there a better way?

2 options:

You can use the "--smell" cli option:

```
reek --smell FeatureEnvy warehouse.rb
```

but that only works for one specific smell unfortunately. 
Other than you can just use our [defaults](https://github.com/troessner/reek/blob/master/defaults.reek) reek config file and then just replace 

`
enabled: true
`

with 

`
enabled: false
`

everywhere, re-enable the smells you are interested in and then use that configuration with the "-c" option in your cli call.

We probably should make "--smell" take multiple values :)

**Comment by troessner** [comment]
Closing this one with #1061 as follow-up.

**Comment by mvz** [comment]
@pitosalas you can pass the `--smell` option multiple times, so you can turn on two or three smells that way.
