### ISSUE TITLE
Make it possible to pass a list of smells to our "--smell" cli option.

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1061]
Coming from #1057 - i think we should make it possible to pass a list of smells to our "--smell" cli option.

WDYT?

**Comment by mvz** [comment]
I think you can repeatedly use this option, like `--smell Foo --smell Bar`?

**Comment by troessner** [comment]
Yes, but I believe this is a little unintuitive and cumbersome, don't you think?

**Comment by mvz** [comment]
OTOH, I always get confused when I have to pass a list, especially regarding the separators.

**Comment by troessner** [comment]
>> OTOH, I always get confused when I have to pass a list, especially regarding the separators.

Me as well, but if we document it properly in -h flag this shouldn't be an issue, should it?
Also, how about calling the flag "--smells" (so plural) to make it less confusing?

**Comment by mvz** [comment]
Ok, let's give this a try. I agree multiple `--smell` arguments are confusing. Options for naming:

1. Keep `--smell` and deal with it.
2. Add `--only`, like RuboCop, and deprecate `--smell`
3. Add `--smells` and deprecate `--smell`.

I'm fine with 1.

**Comment by troessner** [comment]
I think option 3 is the most intuitive for users and I'd like to go in this direction. Deal?

**Comment by waldyr** [comment]
1 - Does not handle multiple smells at once, which is bad in my opinion
2 - Works well with multiple and singular smells at once, which is good.
3 - Does handle a singular smell but feels strange.

I'd rather go with 2 or 3 without deprecating `--smell`

**Comment by troessner** [comment]
>> I'd rather go with 2 or 3 without deprecating --smell

Let's go with "--smells" AND keep "--smell".

Everybody on board with this?

**Comment by troessner** [comment]
I'm not sure if this actually still makes sense. I'd rather vote for closing it. WDYT @mvz ?

**Comment by mvz** [comment]
What made you change your mind?

**Comment by troessner** [comment]
That i never missed this functionality and no user has upvoted this feature in 2 years ;)

**Comment by mvz** [comment]
Ok, let's close this!
