### ISSUE TITLE
Validate the configuration in total before executing any smell detectors.

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1062]
Coming from #1058 - the way we catch exceptions in our smell detectors actually masks errors users might make in Reeks configuration.

We should definitely fix this by validating the configuration in total before executing any smell detectors.
I'd consider this as rather urgent since it's very easy to fuck up and then be left with no clue what actually went wrong.

**Comment by troessner** [comment]
This has been bugging me for a while now, I'll handle this next.

Scope would just be the configuration file at bootup, not code comments that are read at runtime.

Thinking of slim cucumber features that:

* check for Detector existence
* key / attribute correctness for this detector

Combined with more specific Rspec examples.
I'll get this going next week ;)

**Comment by troessner** [comment]
Actually this is non trivial. 
To do this properly we'd need to (pseudocode):

```ruby
config.top_level_entries.each do |entry|
  case
  when entry.contains_detectors?
    handle_directory_directive entry
  when key.contains_detector_configuration?
    handle_detector_configuration entry
  else raise
end
```

Also, lets look into yaml schema, this might help a lot.

**Comment by mvz** [comment]
We could let the detectors verify their own settings at set-up time.

**Comment by troessner** [comment]
Yeah, but this might get messy because we need to validate detectors from multiple angles. Comments, config and maybe something we don't think of right now. 
Let me put up a prototype PR and then we can discuss in code ;)

**Comment by troessner** [comment]
Duplicate to #889

**Comment by troessner** [comment]
Continuing in #1317 - closing this one
