### ISSUE TITLE
Getting our data types right

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1070]
Let's get this right across Reek.
Suggestion:

* class or module names we carry around in hashes and configuration and what not should be designated by constants. So `DuplicateMethodCall`, not `:DuplicateMethodCall` or `"DuplicateMethodCall"`
* hash keys should be all symbols unless they designate classes / modules. See above.
* everything else like messages or parameters in smell warnings should be strings, nothing else.

WDYT?

**Comment by mvz** [comment]
Fully agreed on points 2 and 3.

If we can do the first without having to do the conversion at an inconvenient time, then also agreed on 1.

**Comment by troessner** [comment]
Not so sure this issue still makes sense:

>>
class or module names we carry around in hashes and configuration and what not should be designated by constants. So DuplicateMethodCall, not :DuplicateMethodCall or "DuplicateMethodCall"

I think the only place where this actually happens is when we do it in our specs. Which is kind of ok.

>>
hash keys should be all symbols unless they designate classes / modules. See above.

Let's rather discuss this in #699 - i don't think anymore that this is a good idea.

>>
everything else like messages or parameters in smell warnings should be strings, nothing else.

That is something that we got right across Reek with the last bunch of pull requests.

Closing this issue - feel free to re-open if I missed something.
