### ISSUE TITLE
Move directory directives under a special key

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1078]
Looking into #1062 i realize that it is very hard to validate our configuration because we  deliberately made it very ambiguous if something is a directory directive or a smell detector.
Validating our configuration AND handling most edgecases will be a nightmare.
I think we can make it easier:
- introduce a new top level key called "directories" analoguous to [exclude_paths](https://github.com/troessner/reek#configuration-options) under which we put the directives
- the change should be trivial for users but would make our lifes easier. 
- users can still fuck up the config but since we can make solid assumptions (e.g. everything under "directories" is a directory directive) we can show the users far better and helpful error messages that will help him figure it out on his own. E.g. ""foo/bar/baz is not a valid smell detector. Are you trying to set up a directory directive? Please see...."
- this would be a breaking change of course

Wdyt?

**Comment by troessner** [comment]
With #961 close to the finishing which would in turn result in a Reek 5 release we should get this discussion here going as well :)

**Comment by troessner** [comment]
@mvz any feedback from your side?

**Comment by mvz** [comment]
I don't know how complicated this would be, but maybe we can have a transition period where the old way works but is deprecated?

Also, is #961 a breaking change?

**Comment by troessner** [comment]
Supporting both ways will be incredibly hard I believe (might be wrong here, but thats my gut feeling).

>> Also, is #961 a breaking change?

I dont think so :)

**Comment by troessner** [comment]
Given that we had hardly any issues with this that were reported by our users I'd like to change my point of view and not do this. Wdyt @mvz ?

**Comment by mvz** [comment]
I thought the point was to make it easier to implement #1062 and #889?

**Comment by troessner** [comment]
Good point, I change my opinion back, let's do this :D

**Comment by troessner** [comment]
I'll tackle this soon. This will also allow us to do a proper schema validation <3
