### ISSUE TITLE
Configuration via source code does not allow arrays

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1081]
Found that while working on #1080 

This will work:

``` Cucumber
  Scenario: Configure smell detector with the basic exclude option as string
    Given a file named "configure_exclude_option.rb" with:
      """
      # Test class
      # :reek:TooManyInstanceVariables { exclude: '@hotel' }
      class Alfa
        def initialize
          @charlie = @delta = @echo = @foxtrot = @hotel = 1
        end
      end
      """
    When I run reek configure_exclude_option.rb
    Then it succeeds
    And it reports nothing
```

but this won't:

``` Cucumber
  Scenario: Configure smell detector with the basic exclude option as string
    Given a file named "configure_exclude_option.rb" with:
      """
      # Test class
      # :reek:TooManyInstanceVariables { exclude: ['@hotel'] }
      class Alfa
        def initialize
          @charlie = @delta = @echo = @foxtrot = @hotel = 1
        end
      end
      """
    When I run reek configure_exclude_option.rb
    Then it succeeds
    And it reports nothing
```

Running this will output:

> > ```
> > When I run reek configure_exclude_option.rb                              # features/step_definitions/reek_steps.rb:1
> > Then it succeeds                                                         # features/step_definitions/reek_steps.rb:25
> >   expected that command "reek --no-color configure_exclude_option.rb" has exit status of "0", but has "2". (RSpec::Expectations::ExpectationNotMetError)
> >   ./features/step_definitions/reek_steps.rb:27:in `/^it succeeds$/'
> >   features/configuration_via_source_comments/well_formed_source_comments.feature:66:in `Then it succeeds'
> > And it reports nothing                                                   # features/step_definitions/reek_steps.rb:13
> > ```

Our [basic smell options docs](https://github.com/troessner/reek/blob/master/docs/Basic-Smell-Options.md) clearly state the following for "exclude":

> > an array of strings or regular expressions

**Comment by troessner** [comment]
Seems like this is highly specific to the "exclude" parameter and also to the TooManyInstanceVariables detector. 
Failing test spec:

```Ruby
require_relative '../../spec_helper'
require_lib 'reek/smell_detectors/too_many_instance_variables'

RSpec.describe 'Configuration via source comment' do
  it 'accepts lists of values to be excluded' do
    src = <<-EOS
      # :reek:TooManyInstanceVariables { exclude: '@hotel' }
      class Alfa
        def initialize
          @charlie = @delta = @echo = @foxtrot = @hotel = 1
        end
      end
    EOS

    expect(src).not_to reek_of(:TooManyInstanceVariables)
  end
end
```

**Comment by mvz** [comment]
It turns out neither method works, The former raises an error but Reek exists with a success value anyway. The latter doesn't work because the exclusion mechanism checks context descriptions (so in this case, you would exclude 'Alfa').

**Comment by troessner** [comment]
Wait, why did you close this? There are multiple issues in this one, the least of it being that some of our docs are misleading?

**Comment by mvz** [comment]
AFAICS, it works as it should. You have to put an array of (partial) context names in exclude, not an array of instance variable names.
