### ISSUE TITLE
Fix bad naming and module organisation in regards to smell detectors

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1103]
1.) SmellRepository is **not** a smell repository but instead a **smell detector** repository. PR for this is up in #1104 
2.) /smells/ is an extremely misleading name. It should be "smell_detectors" and not "smells".
3.) /smells/ should only contain smell detectors. Not SmellWarning, not SmellRepository and not SmellConfiguration. It's super confusing that this namespace contain 90% smell detectors and then those 3 classes as well. I believe SmellWarning, SmellRepository and SmellConfiguration should be at the top level

I think [1] and [2] are not controversial so I'll just go ahead to create PR's for those.
[3] might be a bit controversial so I'm happy to discuss this first.

WDYT?

**Comment by mvz** [comment]
:+1: on all three points!

Some bits may need to be part of the reek 5 release, I haven't checked yet what bits are public API.

**Comment by troessner** [comment]
>> Some bits may need to be part of the reek 5 release, I haven't checked yet what bits are public API.

According to our [api docs](https://github.com/troessner/reek/blob/master/docs/API.md) none :)
SmellWarning is part of our API and would change from Reek::Smells::SmellWarning to Reek::SmellWarning but that should be irrelevant for the user.

**Comment by troessner** [comment]
[1] and [2] has been merged and [3] extracted into a separate issue here: #1124 
Closing this one.
