### ISSUE TITLE
Generate specific Code Climate fingerprints for some issues

### ISSUE THREAD

**Issue by wfleming** [troessner/reek#1115]
Hi,

I'm an engineer at @codeclimate, and we've recently gotten some customer confusion from PR comparisons sometimes showing the same effective issue as both "fixed" and "new" on some issues from Reek.

The underlying logic we use in comparisons is based on the [`fingerprint`](https://github.com/codeclimate/spec/blob/master/SPEC.md#data-types) attribute that engines can optionally emit on issues. When a `fingerprint` isn't included, Code Climate generates a default one based on a hash of the code referred to by the issue's `location`, but for some types of issues this doesn't work very well.

For example: https://github.com/almostwhitehat/codeclimatetest/blob/master/example.rb contains some code that Reek detects as `RepeatedConditional`, and [this PR](https://github.com/almostwhitehat/codeclimatetest/pull/3/files) makes a small change that ends up changing the fingerprint because the underlying code changed. (I'm afraid the repo doesn't actually have Code Climate configured, so it's not obvious just from visiting the pages: one way to confirm this is to clone the repo and use the Code Climate CLI, e.g. `code climate analyze -f json`, to see the generated fingerprint.)

In other engines, we've addressed this by generating fingerprints on more stable attributes like the check name & the attached message. Our [RuboCop implementation](https://github.com/codeclimate/codeclimate-rubocop/blob/master/lib/cc/engine/fingerprint.rb) is a good example of the approach we've taken elsewhere, and I think a similar approach might make sense for Reek as well.

Our team is interested in helping fix this issue, so I'm opening this so we can discuss what approach would make sense for you. We're happy to discuss details & help with implementation if we can. I think one thing it would be helpful to discuss here is if there are checks aside from `RepeatedConditional` in Reek that would be good to include fingerprint logic for.

One more small detail: the [codeclimate-engine-rb](https://github.com/andyw8/codeclimate-engine-rb) gem you're using for JSON generation doesn't actually support the `fingerprint` key right now. I opened a [small PR](https://github.com/andyw8/codeclimate-engine-rb/pull/7) this afternoon to fix that, so hopefully that will get merged, but so you know that's a small blocker on fixing this issue fully.

**Comment by troessner** [comment]
Dataclump is probably affected as well plus others. If you need an exhaustive list I can check all detectors on columbus day. 
But why not err on the safe side and use the "detector name + message " fingerprint for all detectors?

**Comment by wfleming** [comment]
> But why not err on the safe side and use the "detector name + message " fingerprint for all detectors?

It's a good question: we used to generate default fingerprints in very much that way.

What we found that was a lot of tools will emit rules like "missing semicolon" without further information. So with "detector name + message", if you were editing a large file that was already missing *1* semicolon somewhere (maybe because you've started using linters on an old code base), if you forgot another one while editing that file, the new instance would get the same fingerprints as the old ones, and wouldn't be detected as "new".

(We could see that the count of issues was different of course, but unfortunately that's not sufficient since then we don't know which one is new. We don't use line numbers for these calculations at all because adding some lines near the top of a file will move lines further down, but generally issues on those later lines shouldn't be considered changed because the lines moved.)

If you're interested, the [PR where we changed the algorithm has some context](https://github.com/codeclimate/codeclimate/pull/419)

So the default fingerprint algorithm is a balancing act between avoiding collisions and gracefully handling changes to files that semantically don't mean much for whether an issue is new or not. The current default is better for the former, and somewhat worse for the latter.

> Dataclump is probably affected as well plus others. If you need an exhaustive list I can check all detectors on columbus day. 

Great, thanks. A complete list would be appreciated since you know your detectors better than we could, but if you don't have time that's very understandable. You could also reasonably decide that *all* of reek's detectors should use something like "detector name + message", if you think that's sensible based on the discussion above. (E.g. if all of the emitted message's include identifying details like method name, then that might work.)

Also, noting here that `0.4.0` of `codeclimate-engine-rb` has been released with support for the `fingerprint` attribute, so that blocker is now gone.

**Comment by troessner** [comment]
>> You could also reasonably decide that all of Reek's detectors should use something like "detector name + message", if you think that's sensible based on the discussion above. (E.g. if all of the emitted message's include identifying details like method name, then that might work.)

There might be some extremely weird edge cases I'm forgetting right now, but I think, I **think** we should be fine with going ahead like this.

>> Also, noting here that 0.4.0 of codeclimate-engine-rb has been released with support for the fingerprint attribute, so that blocker is now gone.

I just [updated the codeclimate-engine-rb](https://github.com/troessner/reek/pull/1116) dependency.

What else do you need? An official release?

**Comment by mvz** [comment]
Most edge cases should be gone, because we used to make the smell messages ignoring the line number. This means context + detector name + message will be pretty much unique.

There is at least one edge case since we added the line number as a unique attribute very recently: #1048. Looking at the related ticket #1044, ManualDispatch is that edge case.

**Comment by wfleming** [comment]
> I just updated the codeclimate-engine-rb dependency.
> What else do you need? An official release?

Thanks for updating that dependency. The change to that gem just added support for emitting the `fingerprint` attribute on the issues, not actually calculating a fingerprint, so no need for a release yet. Sorry if I wasn't clear about the scope of the gem change before. We'll try and open a PR here with actual fingerprint generation soon.

Thanks both of you for the info about the attributes on the detectors. It does seem like we could probably just use context + detector + message in all cases in Reek, but we'll certainly take a closer look at `ManualDispatch` when we start implementing to be sure.
