### ISSUE TITLE
Data types (again) and custom options

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1123]
Kind of related to #699 and #1070 but I think it's worth mentioning separately:

Let's transform this

``` Ruby
    class DataClump < BaseDetector
      MAX_COPIES_KEY = 'max_copies'.freeze
      DEFAULT_MAX_COPIES = 2

      MIN_CLUMP_SIZE_KEY = 'min_clump_size'.freeze
      DEFAULT_MIN_CLUMP_SIZE = 2
    end
```

to

``` Ruby
class DataClump < BaseDetector
  CUSTOM_OPTIONS = {
    max_copies: 2,
    min_clump_size: 2
  }
end
```

And more importantly: Transform all keys used in detectors from string to symbol.

That's not only more coherent, it makes things like #1113 wayyyyy more easier.

**Comment by mvz** [comment]
Sounds good to me.

**Comment by troessner** [comment]
Actually I'm backing down from this again. 
First of all, we're using stuff like MAX_COPIES_KEY a lot in our specs, so removing this will clean up the detector a bit but might decrease readability in other places.
Also, the symbols don't work right now because we're getting strings from our config.

I do think that the changes above would be nice but I don't think the effort is worth it (because trust me, that's going to be a **big** PR).
