### ISSUE TITLE
/smell_detectors/ should only contain smell detectors

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1124]
Extracted from #1103 

/smell_detectors/ should only contain smell detectors. Not SmellWarning, not SmellRepository and not SmellConfiguration. It's super confusing that this namespace contain 90% smell detectors and then those 3 classes as well. I believe SmellWarning, SmellRepository and SmellConfiguration should be at the top level

**Comment by mvz** [comment]
Agreed.

**Comment by mvz** [comment]
All merged :tada:!
