### ISSUE TITLE
False positives for InstanceVariableAssumption when using before_action

### ISSUE THREAD

**Issue by oliverklee** [troessner/reek#1133]
We have a controller that basically looks like this (simplified)

```ruby
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :destroy]

  def find_user
    @user = Identity::User.find(params.fetch(:id))
  end

  def update
    @user.save
  end
end
```

For this controller, Reek complains:
  InstanceVariableAssumption: Admin::UsersController assumes too much for instance variable '@user' [https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md]

I consider this a false positive. Reek should register the before_action that sets the user instance variable.

**Comment by mvz** [comment]
Hello @oliverklee, thanks for your bug report. Rails encourages some special patterns that will cause Reek to report smells. Please see [the section Working with Rails in the README](https://github.com/troessner/reek/blob/master/README.md#working-with-rails) for details on which detectors we recommend you to disable.

**Comment by oliverklee** [comment]
@mvz Oh, I totally missed that addition to that section in the README. Thanks for the pointer!
