### ISSUE TITLE
Flag class, module, def nested inside def as a smell

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1160]
In at least one place, and I'm sure in several more, we take care to handle the case where a class, module, or regular method definition is nested inside a method definition. I think this is a little silly, and I think these should be flagged as a smell, since they usually either don't do what the programmer intended (i.e., they're interpreted as 'nested' classes etc, when their definition is actually processes each time the method is called), or decrease clarity.

**Comment by troessner** [comment]
What do you mean with "take care"? Link? :)

**Comment by mvz** [comment]
We just removed one case here: https://github.com/troessner/reek/pull/1161/files#diff-f3ed2b751dc879ca719fec97feeec152L9

**Comment by troessner** [comment]
Ah, fair enough ;)
What smell would you report?

**Comment by mvz** [comment]
I'll give that some thought.

**Comment by mvz** [comment]
It looks like nested class or module definitions are a syntax error, and nested def is caught by RuboCop's `Lint/NestedMethodDefinition` cop. I'm not sure we need to flag this ourselves anymore. WDYT, @troessner?

**Comment by troessner** [comment]
Agree on us not flagging this anymore @mvz

**Comment by mvz** [comment]
Alright, closing this.
