### ISSUE TITLE
Unable to install/launch reek sucessfully

### ISSUE THREAD

**Issue by gunjanaggarwal** [troessner/reek#1168]
I am trying to install and use the latest version of reek on my ubuntu (16.04 LTS) machine. 
I have : 
ruby version : ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
gem version : 2.5.1

When I executed command `sudo gem install reek`, I got following error:
```
ERROR:  Error installing reek:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rainbow-2.2.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1/gem_make.out
```

After that, I executed command `sudo apt install ruby-reek` which successfully installed reek. But now when I try to execute reek as following:
`echo "class C; def m; end; end" | reek` or any other way, I get the following error:
 
```
/usr/bin/reek:9:in `require_relative': cannot load such file -- /usr/lib/reek (LoadError)
	from /usr/bin/reek:9:in `<main>'
```

Can anyone please help me fix this error? 

Thanks.

**Comment by troessner** [comment]
You're trying to install Reek version 2.5.1?
That one is **years** old. Please try the latest version.
Also I'd rather recommend using rbenv as ruby version manager and not the ubuntu distribution packages (every time i see a "sudo" in front of a "gem install" a kitten dies).

But even without that a 

`gem install reek`

should work out of the box.

**Comment by gunjanaggarwal** [comment]
Hi,

Thanks for the reply. I get the following error with `gem install reek`:
```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
```

But, I just tried to install reek again using `sudo gem install reek` (sorry about another kitten), after removing the reek I installed using `sudo apt install ruby-reek` and it installed reek successfully.

Thanks.

**Comment by troessner** [comment]
Good to hear that ;)
