### ISSUE TITLE
Reek still tries to process excluded files

### ISSUE THREAD

**Issue by andyw8** [troessner/reek#1169]
I'm using reek 4.5.4. My `.reek` config contains:

```
exclude_paths:
  - app/gulp/javascripts
```

When I run `reek app`, it reports a warning:

`Source app/gulp/javascripts/opal/bigdecimal.js.rb can not be processed by Reek.`

Possibly related to https://github.com/troessner/reek/issues/1092.

**Comment by mvz** [comment]
I'm also interested why Reek thinks it cannot process an opal file.

**Comment by andyw8** [comment]
I'm not familiar with Opal, but the file in question doesn't look like valid Ruby.

**Comment by mvz** [comment]
Time to squash that bug. I'll take a stab at it this weekend.

**Comment by mvz** [comment]
This has been fixed in master.

**Comment by andyw8** [comment]
Thanks @mvz !
