### ISSUE TITLE
Should `exclude_paths` configuration be respected when checking a file in that path?

### ISSUE THREAD

**Issue by IanWhitney** [troessner/reek#1196]
Config.reek contents:

```yaml
---
exclude_paths:
  - db/migrate
```

`reek .` returns no smells, but `reek db/migrate/20170328163910_create_features.rb` returns 3 smells. 

Should reek respect the exclude_paths config options when passed in a file in an excluded path?

**Comment by troessner** [comment]
I understand that this is confusing but I consider it a feature rather than a bug ;)
I consider passing Reek an absolute path a way of saying "I really, really want to have this checked".

Like I said above though, I understand that this is confusing and I'd be open to a pull request that still ignores the file but then prints something like "You told me to check file xyz but this file is under an excluded path in your config file xyz.reek".

**Comment by IanWhitney** [comment]
The problem we run in to is when we combine Reek with a automated runner like [Overcommit](https://github.com/brigade/overcommit).

When Overcommit runs its pre-commit hook it looks for all files that have changed. It then passes each file to Reek with an absolute path. So if we've changed a file in db/migrate we get a Reek error.

**Comment by troessner** [comment]
Fair point. I'm open to changing the behaviour but I'm swamped at the moment unfortunately, so this might take a while :-/
@mvz would you be up for this?

**Comment by IanWhitney** [comment]
We may be able to help as well. But I didn't want to create PR without first checking to see if the PR would be welcomed.

**Comment by troessner** [comment]
>> We may be able to help as well.

That would be great, happy to help you with that PR as well.

**Comment by Drenmi** [comment]
> I consider passing Reek an absolute path a way of saying "I really, really want to have this checked".

Just to chip in, I personally very much appreciate this behaviour. (It works the same for RuboCop.) If it is changed, please let's add a flag that still allows me to inspect it. `--force`?

**Comment by mvz** [comment]
@IanWhitney which version of reek are you using?

**Comment by mvz** [comment]
@IanWhitney never mind, I can reproduce this with current reek.

The handling of exlude paths was changed recently: Before, reek completely ignored it when paths were passed on the command line. My intent was to make it always honour the exclude paths, but it looks like we're now somewhere in the middle (note that `reek db/migrate` will not report any smells).

**Comment by troessner** [comment]
>> Just to chip in, I personally very much appreciate this behaviour. (It works the same for RuboCop.) If it is changed, please let's add a flag that still allows me to inspect it. --force?

I like this idea a lot.

**Comment by mvz** [comment]
I would prefer to make the behavior as much the same as RuboCop's as possible, preferably identical. RuboCop has the option `--force-exlusions` or something like that to help with tools like overcommit and pronto.

**Comment by troessner** [comment]
Sounds good to me as well. I don't really care for the precise solution but for a consistent, flexible solution.

**Comment by IanWhitney** [comment]
Here's the feature test that I'm starting from. Once this is passing I'll submit a PR

https://github.com/umn-asr/reek/commit/05214c1ba72e3e30bf22905c961c3cd25dd36c52

**Comment by troessner** [comment]
The cucumber feature looks good to me ;)

**Comment by Drenmi** [comment]
@mvz: Corright. The flag is `--force-exclusion`. 🙂

**Comment by mvz** [comment]
I would prefer moving those two new tests to a second scenario in the same file.
