### ISSUE TITLE
Cucumber tests not run by `bundle exec rake`?

### ISSUE THREAD

**Issue by IanWhitney** [troessner/reek#1198]
Looking at the Readme

https://github.com/troessner/reek#developing-reek--contributing

I thought Cucumber tests would run with `bundle exec rake`

But after setting up a Cucumber test that I knew would fail, `bundle exec rake` continued to tell me that all my tests were green.

Running `bundle exec cucumber` ran the features and showed me my failing test as expected.

**Comment by troessner** [comment]
Good catch! Just pushed [a fix](https://github.com/troessner/reek/pull/1199) for this.

**Comment by mvz** [comment]
This seems wrong; I'll look into it more this weekend.

**Comment by troessner** [comment]
Pretty sure that was intentional back then since our cucumber features are slower than a snail on opium :-/

**Comment by mvz** [comment]
I just checked, and when I run `bundle exec rake`, both RSpec and Cucumber tests are run. Something else must be going on here. @IanWhitney does your scenario show up when you run `bundle exec cucumber features --format progress --color` (this is what the rake task does)?

**Comment by mvz** [comment]
> slower than a snail on opium

Thank you for this brilliant simile!

**Comment by mvz** [comment]
@IanWhitney can you give us some more info on this please? Is your scenario run when you do `bundle exec rake ci`? What is the name of your scenario file?

**Comment by IanWhitney** [comment]
This can be closed. Thanks.

**Comment by IanWhitney** [comment]
I must have been typing the wrong command or something. Not sure what was going on here. But from what I see now `bundle exec rake` does run the Cucumber tests as expected. Sorry for the confusion.

**Comment by mvz** [comment]
Thanks for the clarification, @IanWhitney.
