### ISSUE TITLE
[Feature Request] Introduce Syntax smell

### ISSUE THREAD

**Issue by pocke** [troessner/reek#1215]
Problem
-------

Currently, if project has a ruby file that is with a syntax error, Reek stop the analysis.
This behavior have been introduced by #1185 from reek v4.6.0. 

By this behavior, we can notice syntax errors.
However, we can't get analysis results of ruby files that doesn't have syntax error also.

This behavior has problems when we use reek on editor integrations, code review as a service or something.
The tools and services are not always handle the error, so the users maybe can't get analysis result if syntax error files exist. So, maybe users can't notice the syntax error.

Solution
------

### Introduce Syntax smell

For example, RuboCop provides `Lint/Syntax` cop. https://github.com/bbatsov/rubocop/blob/26bad386fa8e3c85ad3a434faef0ec765ba612dc/lib/rubocop/cop/lint/syntax.rb
RuboCop adds offense of `Lint/Syntax` to files that have syntax error.

I think reek introduces the feature, we can avoid the problem. Users can notice syntax error, and users can get analysis result.

WDYT? @mvz @troessner

**Comment by troessner** [comment]
>> This behavior has problems when we use reek on editor integrations, code review as a service or something.

Good point :)

>> RuboCop adds offense of Lint/Syntax to files that have syntax error.

I like the idea. @mvz ?

**Comment by mvz** [comment]
Yes, this makes a lot of sense.

**Comment by pocke** [comment]
Thanks, I'll work on it.
