### ISSUE TITLE
Codeclimate runs seem broken

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1224]
It looks like codeclimate [is failing](https://codeclimate.com/github/troessner/reek/pull/1222) for our repositiory, and it's failing when running Reek. We should investigate.

**Comment by troessner** [comment]
Ack ;)

**Comment by pocke** [comment]
I guess the cause is syntax smell. I added 'Syntax' to default.reek. However, the smell is not available in a reek that is in CodeClimate.
https://github.com/troessner/reek/blob/master/defaults.reek#L69
So, I think we can try one of the followings.

- Wait a release of new version in CodeClimate.
- Remove 'Syntax' from default.reek
  - I don't know that is right way.

**Comment by mvz** [comment]
Or:
* Be more lenient about unknown smell names.

**Comment by troessner** [comment]
I am not a fan of being more lenient. There was a reason why that check is actually there ;)

Maybe there is way to overwrite this check when running in a codeclimate environment? That might be an option.

**Comment by maxjacobson** [comment]
I'm happy to update the version of reek running on Code Climate as a short-term fix.

**Comment by troessner** [comment]
That'd be great @maxjacobson

**Comment by maxjacobson** [comment]
@troessner sounds good. I noticed one issue with the new smell, and I've opened this PR: https://github.com/troessner/reek/pull/1225 .

**Comment by mvz** [comment]
By lenient I mean not totally error out at least.

**Comment by troessner** [comment]
I think there was a reason for this strictness but i really cant recall what it was :D

**Comment by maxjacobson** [comment]
![screen shot 2017-06-07 at 12 40 00](https://user-images.githubusercontent.com/1421211/26890044-3e0bb01c-4b7e-11e7-8943-b2b336caa869.png)

https://codeclimate.com/github/troessner/reek/builds

I triggered a refresh build after releasing 4.7.0 + that fix and it seems to have worked :)

**Comment by troessner** [comment]
Nice! Thanks for the effort :)

**Comment by mvz** [comment]
Thanks, @maxjacobson.
