### ISSUE TITLE
.reek file should use .yml extension

### ISSUE THREAD

**Issue by spilth** [troessner/reek#1232]
The default configuration file should use a `.yml` extension so intelligent text editors can provide YAML syntax checking and functionality ([a la Rubocop](http://rubocop.readthedocs.io/en/latest/configuration/))

My particular use case: I generate a reek TODO file for my project and want to comment out various sections so I can work on those issues. Being able to select multiple lines in RubyMine and comment them out with Command / would be helpful instead of having to do that manually (and error prone)

**Comment by mvz** [comment]
I think this makes sense, but we'll need some other way to signify that this is Reek's configuration.

Also, this is a breaking change so a full changeover will have to be part of a Reek 5 release. We can introduce this as an alternative option, however.

**Comment by spilth** [comment]
I was thinking .reek.yml

**Comment by Drenmi** [comment]
> I was thinking .reek.yml

+1 for this, as it follows the convention of many other tools and services. 🙂

**Comment by mvz** [comment]
@spilth that is the obvious choice 🙂 

I suppose this also neatly solves the problem of having to catch the presence of multiple Reek config files.

**Comment by troessner** [comment]
I agree that this change makes sense.

>> Also, this is a breaking change so a full changeover will have to be part of a Reek 5 release. We can introduce this as an alternative option, however.

Do you see any problems with having a major release? Seems the cleanest solution to me.

**Comment by mvz** [comment]
> Do you see any problems with having a major release? Seems the cleanest solution to me.

Only that I would like to cram as many breaking changes into the one major release as possible.

**Comment by troessner** [comment]
>> Only that I would like to cram as many breaking changes into the one major release as possible.


We haven't been super-active on Reek for the last couple of months. I'd rather not block a useful change just for the sake of being as efficient as possible.

**Comment by troessner** [comment]
Quickly looking into this, it looks like this is a [one-line code change](https://github.com/troessner/reek/blob/master/lib/reek/configuration/configuration_file_finder.rb#L99) and then changing it everywhere in our documentation. I'll create a PR for this soon.
