### ISSUE TITLE
Drop `reek_of` and `reek_only_of` matchers from public API

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1249]
These really only make sense for Reek development.

**Comment by troessner** [comment]
>> These really only make sense for Reek development.

I disagree with this premise. What about tool authors that build on reek? E.g. most of our numerous editor integration probably use this. AFAIR we also had regular users using this.

**Comment by mvz** [comment]
> most of our numerous editor integration probably use this.

Hm. How would they use this? And why would the want to check for individual smells, as opposed to using the basic `reek` matcher?

**Comment by troessner** [comment]
But we dont know how other people use it. I dont see how maintaining those methods is much of a maintenance burden. 

If you are confident though this will not break any of the Plugins we list in our Readme i am fine with the change.

**Comment by troessner** [comment]
@mvz any update from your side? (see my comment above)

**Comment by mvz** [comment]
I agree that keeping these public is not much of a burden. I'd like to revisit their API for the 5.0 release, though.

**Comment by mvz** [comment]
The main change I want to make is what is described in #1163.
