### ISSUE TITLE
[Attribute] Writable attribute warning 

### ISSUE THREAD

**Issue by alain-andre** [troessner/reek#1255]
In one of my project, I'm having this **writable attribute** warning and I do not understand why.

The given [documentation](https://github.com/troessner/reek/blob/master/docs/Attribute.md) is clear but I have no idea how to do then. 
>  setter for an instance variable invites client classes to become too intimate with its inner workings

For example, I'm having a ActiveRecord class `Language` containing a attribute `rank`, this class is `Comparable` by `rank`. The `rank` attribute is not a **ActiveRecord** attribute as it is an instance information.

```ruby
class Language < ApplicationRecord
  include Comparable
  attr_accessor :rank

  ##
  # Compare a Language to an other
  # @param Language other The other Language instance to compare
  def <=>(other)
    return nil unless rank.is_a? Integer
    rank <=> other.rank
  end
end
```

And another class (not ActiveRecord) `Languages` that contains a method that calculate each rank and sort the languages. 

```ruby 
class Languages
  ##
  # Offers among the available languages the closest one to the datasets
  # @param string input The data set.
  def guess(input)
    return [] if @languages.empty?
    @languages.each do |language|
      language.rank = score(input, language)
    end
    @languages.sort.reject { |language| language.rank.zero? }
  end
end
```

How should I do ? Can someone give a way to fix it ?

**Comment by mvz** [comment]
The following line in your code creates a reader and a writer for your `rank` attribute:

```ruby
attr_accessor :rank
```

The fix in this case is to replace it with

```ruby
attr_reader :rank
```

**Comment by Drenmi** [comment]
If `#rank` is only used within `Languages#guess`, you could opt to use some transient data structure to do the sorting.

If the rank is unique, you could use a hash where the key is the rank and the `Language` is the value. If it is not unique, you could use an array of tuples (one-element hashes, or two-element arrays.) Then, after sorting, you can return either just the sorted languages, or the languages and their ranks (if it's used somewhere outside of sorting.)

**Comment by waldyr** [comment]
Remove the `Comparable`, `attr_writer` and the `<=>` method and then the `guess(input)` method should look like:
```
def guess(input)
  hash = @languages.map { |language| [language, score(input, language)] }.to_h
  sorted_languages = @languages.sort_by { |language| hash[language] }
  sorted_languages.reject { |language| hash[language].zero? }
end
```

**Comment by alain-andre** [comment]
@Drenmi Yes you are totally right. `#rank` should not be in `Language` but a hash in `Languages` as @waldyr proposes. 

Obrigado de mais @waldyr !! Nos encontramos em breve :p

**Comment by mvz** [comment]
@alain-andre sorry, I totally missed the point of your question back there. Glad it got solved anyway!

**Comment by alain-andre** [comment]
@mvz No problem :p
