### ISSUE TITLE
What about Ataru?

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1260]
So, Ataru seems dead upstream, and they're now behind on the `thor` dependency. What shall we do? Some options (there may be others):

1. Drop Ataru.
2. Find some replacement for Ataru and use that.
3. Fork Ataru.
4. Not care about `thor`.

**Comment by mvz** [comment]
This might work (haven't checked the code yet): https://github.com/lsegal/yard-examples/blob/master/doctest/doctest.rb

**Comment by troessner** [comment]
I'd go with  [4] unless integrating doctest from above is a breeze.

**Comment by mvz** [comment]
It seems the doctest thing is only for the `@example` yard tags.

**Comment by troessner** [comment]
We rarely have any additions for ataru to check, so i wouldnt really bother. :)

**Comment by mvz** [comment]
@troessner does that mean you're ok with dropping it?

**Comment by troessner** [comment]
Not really. Ataru adds quite some value to our build process. Why would we drop that if we can just leave it as it is? I dont get it :)

**Comment by mvz** [comment]
Ok, clear, just wasn't sure what you meant by 'wouldn't really bother'.

**Comment by troessner** [comment]
@mvz seems like we reached a conclusion here - are you ok with dropping it?

**Comment by mvz** [comment]
Yes, can be closed.
