### ISSUE TITLE
Replace pry with irb-tools?

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1274]
I'm trying to wean myself off pry due to various reasons, and @chastell pointed me to irb-tools, which I like very much. I'd like to propose replacing pry as our debugging tool with irb-tools.

**Comment by troessner** [comment]
I still like pry. What are those various reasons?

**Comment by mvz** [comment]
I'm not going to do any linking here, but:
* Iffy release policy (seems to have improved somewhat recently).
* Lack of focus in what is in core or not (e.g., there is now a `gem-stat` command that fetches statistics from rubygems.org **in core**)
* Seems more interested in adding/supporting non-features like the pry-media plugin than in creating a solid foundation.
* Overly complex implementation, lowering complexity does not seem to be a consideration.

**Comment by troessner** [comment]
If you feel that irb-tools will increase your productivity then I am ok with replacing pry.

**Comment by troessner** [comment]
@mvz should we close this one? As mentioned above, I'm fine with using irb-tools.

**Comment by mvz** [comment]
Yes, this can be closed. I feel less strongly about pry at the moment, they seem to be releasing in a more timely manner these days. We'll see what happens ...
