### ISSUE TITLE
Drop support for Ruby < 2.3

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1285]
It's time 😄

**Comment by Drenmi** [comment]
❤️

**Comment by troessner** [comment]
Official ruby website says that 2.2. is [still maintained](https://www.ruby-lang.org/en/downloads/) but we can kill 2.1 ;)

**Comment by mvz** [comment]
OTOH, [this page](https://www.ruby-lang.org/en/downloads/branches/) says support for 2.2 ends 31 march 2018. Not sure what to make f that ...
