### ISSUE TITLE
Breaks Rubocop update to 0.53

### ISSUE THREAD

**Issue by davidhrbac** [troessner/reek#1294]
I'm not able to update Rubocop to the latest version since reek requires `parser (>= 2.4.0.0, < 2.5)` https://github.com/troessner/reek/blob/master/reek.gemspec#L24  and the latest Rubocop requires `parser >= 2.5`  https://github.com/bbatsov/rubocop/blob/master/rubocop.gemspec#L40

**Comment by pocke** [comment]
I opened a pull request for this issue.
https://github.com/troessner/reek/pull/1295
