### ISSUE TITLE
Is it possible to exclude at the file level?

### ISSUE THREAD

**Issue by monfresh** [troessner/reek#1301]
Hello. I'm trying to exclude a particular file from all Reek checks, but it looks like the only global option is at the directory level. I don't want to exclude all files in a particular directory, just one file in that directory. Is this possible currently? Thanks!

**Comment by troessner** [comment]
This is currently not possible - as you can see [here](https://github.com/troessner/reek/blob/master/lib/reek/configuration/excluded_paths.rb#L14) and [here](https://github.com/troessner/reek/blob/master/lib/reek/configuration/configuration_validator.rb#L39)  we only accept directory names. Pull requests welcome ;)

**Comment by troessner** [comment]
[Updated our docs](https://github.com/troessner/reek/commit/a162b7380f747aa0b14ad9613044e3778fa37109) to reflect this - closing this issue.
