### ISSUE TITLE
Let's release Reek 5

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1305]
Here's my suggestion list:

* [Change PrimaDonnaMethod to MissingSafeMethod](https://github.com/troessner/reek/pull/1304)
* [Introduce a --list option](https://github.com/troessner/reek/issues/1165) - no particular reason, I just really like the idea
* Whatever we can sneak in from the other items on our ["breaking change" list](https://github.com/troessner/reek/labels/breaking-change)

Afterwards we should release a new version on CodeClimate to fix the problems with the [Syntax smell](https://github.com/troessner/reek/issues/1291)

Thoughts? :)

**Comment by mvz** [comment]
Ideally, I'd like to include all of the breaking changes. Any that we don't include should be closed.

**Comment by mvz** [comment]
I'm going to pick up some of those breaking changes over the weekend.

**Comment by troessner** [comment]
Me too probably. Let's make sure we always assign the issue to ourselves and write a comment that we're working on it to not duplicate work :)

**Comment by troessner** [comment]
Almost there <3 ;)

**Comment by troessner** [comment]
Lemme summarize what is left to do:

* Finish:
  * #1333 
  * #1322 
  * If its not too much effort, sneak in #1319 

* Release v5:
  * Add the documentation that we removed in #1329 
  * Finish via #1324  (don't forget to add the new entries to the changelog)

* Release a new CodeClimate version
  * Ensure that #1325 works
  * And #1291

**Comment by troessner** [comment]
Now that #1322 is out i'd like to give #1319 a quick shot just to make sure that in the scope of the pull request we do not need any other breaking change. That is something I'll look into today.

**Comment by troessner** [comment]
Ok, it looks like #1317 won't add anything breaking so we don't have to wait for this to finish to release Reek 5 ;)
Let's continue with:

```
Add the documentation that we removed in #1329
Finish via #1324 (don't forget to add the new entries to the changelog)
Write a helpful blog post so users can easily transition from Reek 4 to Reek 5 and link it prominently
```

**Comment by troessner** [comment]
Ready to roll, [let's go](https://github.com/troessner/reek/pull/1324)!

**Comment by mvz** [comment]
#1343 may introduce a breaking change to `Examiner` so we should probably wait for that.

**Comment by troessner** [comment]
Right, good point!

**Comment by mvz** [comment]
We also need to actually add `Syntax.md` or remove the detector to really fix #1291.

**Comment by mvz** [comment]
All breaking changes were merged :tada:!

**Comment by troessner** [comment]
Wait, [one more](https://github.com/troessner/reek/pull/1374)! 😆 
Source: [click](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/)

What a coincidence 🌈
