### ISSUE TITLE
Debugging cucumber not working anymore

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1320]
I'm not 100% sure but I think at one point it time I really could just add

```Ruby
binding.pry
```

anywhere in the code and cucumber would stop execution and drop me into the pry shell. 
It seems like we have lost this again, no matter what I do, cucumber will ignore it.

Any ideas?

**Comment by troessner** [comment]
Closing this one. I wont write new cucmber features if possible and if i run into another problem i'd rather replace the feature in question with  a spec.

**Comment by mvz** [comment]
FWIW, Aruba by default doesn't allow interaction with programs it runs, so I'm not sure this ever worked.

**Comment by troessner** [comment]
Fair enough, might be that my memory is fooling me :)
