### ISSUE TITLE
Reek links should link to specific versions of the documentation

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1330]
As mentioned in https://github.com/troessner/reek/pull/1329#issuecomment-396043572, Reek's 'wiki links' link to the master branch so they break if we change the documentation for a new release. Perhaps we can link to the release tag instead?

**Comment by troessner** [comment]
That is a great idea! Are you going to look into this? If not I can take this over as well.

**Comment by mvz** [comment]
I'll take a stab at this and #1331 right now.

**Comment by troessner** [comment]
>> and #1331 right now.

Wait, i already created #1332 😆
