### ISSUE TITLE
The `--wiki-links` option has an obsolete name.

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1331]
Would be nice to change this for the 5.0 release.

Options:
* `--documentation`
* I don't have any other ideas :slightly_smiling_face:.

**Comment by troessner** [comment]
>> The `--wiki-links` option has an obsolete name

Oh, excellent point, i never noticed that 😆 

>> --documentation

It's not fancy, true, but a fitting name, so +1 from my side :)
