### ISSUE TITLE
Output of `--list` is broken

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1334]
On master, `reek --list` outputs literal `\n`. This also means there's something wrong with how our cucumber scenarios check output.

**Comment by troessner** [comment]
>> This also means there's something wrong with how our cucumber scenarios check output.

Interesting, you're right. Should we re-open this issue or do you rather prefer a separate follow-up issue?

**Comment by mvz** [comment]
I'll make a follow-up issue.
