### ISSUE TITLE
Backport some things to a final 4.8.2 version?

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1339]
In the sprint up to 5.0, we fixed some stuff that might be useful to backport. I'm thinking of:

* ~#1335~ Nope, `-l` is not in reek 4.8.
* #1338
* The first commit in #1333

**Comment by troessner** [comment]
Fully agree, sounds like a good idea, especially #1338

**Comment by mvz** [comment]
I'm going to prepare a branch for this.

**Comment by mvz** [comment]
See https://github.com/troessner/reek/tree/reek-4-8

**Comment by mvz** [comment]
Done and released.
