### ISSUE TITLE
Detect old-style reek comments

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1341]
As noticed in #1322, Reek currently still accepts old-style comments with three colons, because the regex used will simply ignore the third colon and everything that follows, essentially blanked-disabling the given smell. This means users will not normally be aware that they need to update their code comments.

Options to fix:

1. Detect this particular usage and complain about it loudly. We probably should have done this already when we deprecated the extra colon.
2. Make the regex less lenient and just ignore the entire code comment if it doesn't use the new style. The reek failures should point out what needs updating, but this could be confusing.

Option 2 could be implemented by:
* Requiring the comment to come at the end of a line.
* Requiring the comment to be followed by anything but a colon.

**Comment by troessner** [comment]
Good points. I think this

>> Detect this particular usage and complain about it loudly. We probably should have done this already when we deprecated the extra colon.

would be my favourite option :)

**Comment by chastell** [comment]
I would also prefer a loud complain in that case!
