### ISSUE TITLE
DuplicateMethodCall for separate blocks

### ISSUE THREAD

**Issue by EdwinRozario** [troessner/reek#1348]
Ruby Version: 2.4.3, OSX
I have something like

`haves = bots.all? { |bot| bot.smart };
  have_nots = bots.select { |bot| !bot.smart }.first`

Reek raises DuplicateMethodCall: MyClass#call calls 'bot.smart' 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]

I am not sure if this an expected behaviour. I feel like usage if method smart is required in two contexts.

**Comment by mvz** [comment]
Hi @EdwinRozario, in this particular case I would probably try to use `Enumerable#partition`, but for the general case please see #1231.
