### ISSUE TITLE
Output hidden in Heroku CI

### ISSUE THREAD

**Issue by mdi** [troessner/reek#1357]
I run reek as part of a custom script on Heroku CI, which isn't a TTY, so the output is hidden during the test run. It would be nice to have a way to force output in those kind of situations.

It looks like this issue was introduced in https://github.com/troessner/reek/pull/1122https://github.com/troessner/reek/pull/1122

**Comment by mvz** [comment]
Hi @mdi, you can add de `--progress` command line option to enable progress reporting on non-TTYs.

**Comment by mdi** [comment]
The `--progress` option seems to have no effect.

**Comment by mvz** [comment]
Ok, something else must be going on. Since `reek --progress | more` works fine for me, I'm going to need a little bit more information on how you're running reek.

**Comment by mdi** [comment]
I have a script that runs reek followed by rubocop followed by my test suite. When I run this script locally in a terminal, reek displays output (my terminal is a TTY).

<img width="1428" alt="mdi_michaels-mbp____src_mdi_fitrackr-api" src="https://user-images.githubusercontent.com/524808/41818587-ec816c08-777f-11e8-8e3c-2e4b68348c11.png">

But when this script is run on Heroku CI, reek displays no output. Note that rubocop and the test suite are displaying output

![fitrackr_ _pipeline___heroku](https://user-images.githubusercontent.com/524808/41818508-6d9658be-777e-11e8-871f-5954e50a5bfb.png)

The script is:

```
#!/usr/bin/env bash

set -x

function test_rb {
  bundle exec rails test "$@"
}

function rubocop_rb {
  bundle exec rubocop "$@"
}

function reek_rb {
  bundle exec reek --progress "$@"
}

reek_rb "$@" && rubocop_rb "$@" && test_rb "$@"
```

I first contacted Heroku support about it, and after a couple of days of back & forth with them, we came to the realization that the issue is Heroku is a non-TTY environment and reek hides output when in a non-TTY environment.

<img width="1214" alt="heroku_help" src="https://user-images.githubusercontent.com/524808/41818533-fe464860-777e-11e8-9740-a8604c2ea578.png">

**Comment by mvz** [comment]
Even in a non-TTY output, Reek should at least output `0 total warnings`, and even that is missing. Something else must be going on.

**Comment by mvz** [comment]
@mdi To eliminate any potential confusion: Which version of Reek are you using?

**Comment by mdi** [comment]
v4.8.1

**Comment by mvz** [comment]
There is one point at which Reek suppresses all output, which is during the loading of the `parser` gem. Perhaps something goes wrong there.

**Comment by mvz** [comment]
Hi @mdi could you try running this with current master? I've removed output suppression during normal Reek runs and I'd like to see if that helps.

**Comment by mdi** [comment]
Upon further investigation, it looks like `reek` is not even being ran on Heroku CI, so I'm reopening the issue with them. My apologies for the trouble.

**Comment by mdi** [comment]
Just to provide some more feedback on this issue, I finally worked it out. The primary issue it turns out was that I had to provide source code directory arguments to `reek` to get it to scan anything on Heroku CI. I was running it without any arguments and that worked locally, but that caused it to not scan anything on Heroku CI. I'm **still** not seeing output, but I have confirmed it is scanning files now at least.

**Comment by abodelot** [comment]
Hi @mdi 

I found this bug report while investigating this issue: 

> I was running it without any arguments and that worked locally, but that caused it to not scan anything on Heroku CI

Any idea about the root cause? How comes `reek` doesn't scan anything on Heroku CI unless you explicitly pass a path argument?

Thanks!

**Comment by mdi** [comment]
I'm not sure.

**Comment by dmunoz-etecnic** [comment]
Happened to me in Gitlab CI/CD. Reek would't analyze any files. Had to append a dot to the reek invocation:

`reek -c .reek.yml .`
