### ISSUE TITLE
Introduce a "law of demeter" detector

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1412]
Excellent introduction [here](http://www.virtuouscode.com/2011/07/05/demeter-its-not-just-a-good-idea-its-the-law/)

**Comment by troessner** [comment]
>> Maybe best to start with bravo.charlie.delta

But this would then warn on 

```Ruby
string.strip.downcase
```
already. Right now I don't see way to differentiate between

```Ruby
string.strip.downcase # Should not smell but will
```
and

```Ruby
parameter.object.method # Should smell
```

Code like

```Ruby
string.strip.downcase # Should not smell
```
is fairly ubiquitous in Ruby programs so we would generate a lot of false positives.
Maybe this endeavour is doomed from the start and it's just not possible on a very basic, fundamental level?

**Comment by chastell** [comment]
(With Demeter being about the number of non-core type changes in a method chain and Ruby not having any type inference mechanisms I think this is indeed hopeless, but I don’t want to discourage anyone; maybe there _is_ a clever hack that could work for 80% of the cases…)

**Comment by mvz** [comment]
@chastell now you made me wonder how easy it is too hook into Crystal's compiler and write a LoD checker for it.

**Comment by troessner** [comment]
Seems like this is a lost cause :(
Closing this issue.
