### ISSUE TITLE
False positive for InstanceVariableAssumption in ActiveRecord models

### ISSUE THREAD

**Issue by coorasse** [troessner/reek#1423]
In ActiveRecord seems common to use the callback `after_initialize` to initialize instance variables, instead of overriding the `initialize` method.
If an instance variable is initialized in a callback reek does not recognise this and marks the error.
I already saw a [similar issue](https://github.com/troessner/reek/issues/1133) and the [Working with Rails](https://github.com/troessner/reek/blob/master/README.md#working-with-rails) section of the README but it seems not to cover our use case

**Comment by troessner** [comment]
Nice observation. @mvz wdyt about adding a configuration to our "working with rails" section where we disable this detector for app/models?

**Comment by mvz** [comment]
Thanks, @sihu that makes things a lot clearer and makes me want to hunt initializers in my Rails projects :smile:.

**Comment by sihu** [comment]
*Update:*  Please note that i forgot to write that this is best practice for ActiveRecord initializers

**Comment by troessner** [comment]
Closed via #1424
