### ISSUE TITLE
Fix UtilityFunction false positive with singleton refinement.

### ISSUE THREAD

**Issue by bkuhlmann** [troessner/reek#1438]
## Overview

Seeing the following warning:

``` bash
[reek]: lib/refinements/times.rb -- 1 warning:
  [9]:UtilityFunction: Refinements::Times#duration doesn't depend on instance state (maybe move it to another class?) [https://github.com/troessner/reek/blob/v5.2.0/docs/Utility-Function.md]
1 total warning
```
...for this refinement:

``` ruby
module Refinements
  # Refinements for times.
  module Times
    refine Time.singleton_class do
      MILLISECONDS = 1_000

      def duration start_at, end_at
        (end_at - start_at) * MILLISECONDS
      end
    end
end
```

It seems Reek thinks this is a *utility method* violation which, generally, would be true but I'm defining a refinement to be used as a class method which would *not* classify as a utility method violation. Here's the usage of the above refinement:

``` ruby
using Refinements::Times
Time.duration start_at, end_at # <= The above refinement introduces a class method.
```

Would it make sense to allow this situation?

**Comment by mvz** [comment]
I don't think we take `refine` into account at all at the moment. Refining the singleton class is a bit of a hack, it seems, so I'm not sure we should endorse *that*, but if we do, this seems a valid way of defining a singleton method on a module and should be allowed. @troessner do you have any experience with `refine` and can you comment on this use?

**Comment by troessner** [comment]
>> @troessner do you have any experience with refine and can you comment on this use?

Nope, no idea, unfortunately. 

I do agree with

>> Refining the singleton class is a bit of a hack, it seems, so I'm not sure we should endorse that

though so I'm inclined to not address this.

**Comment by bkuhlmann** [comment]
:information_source: Closing this since there isn't much traction.
