### ISSUE TITLE
Question about Duplicate Method Call

### ISSUE THREAD

**Issue by monfresh** [troessner/reek#1456]
Hello. I'm curious as to the reasoning behind the Duplicate Method Call check. The way I understand the documentation, it is to prevent accidentally performing the exact same action twice. If that's correct, why does Reek complain about method calls that aren't exact duplicates of each other?

For example, Reek will complain that `Rails.env` is being called twice in this conditional:
```ruby
Rails.env.development? || Rails.env.test?
```
Similarly, it will complain about accessing the same key in a hash:
```ruby
hash = { a: 1, b: 2 } 
one_array = [2]
another_array = [1] 
one_array.include?(hash[:a])
another_array.include?(hash[:a])
```

Are the two examples above indicative of a bad practice, or is it just due to a limitation of Reek in that this particular check can't account for all the possible contexts in which it might make sense to make the same call twice?

**Comment by troessner** [comment]
Why do you believe that it makes sense to do the same call twice in the examples above?

I know that stuff like `Rails.env.foo` is pervasive in Rails docs and across the internet, however, I don't believe this makes it good practice to do so.

So coming back to your example above I'd personally do

```Ruby
env = Rails.env
env.development? || env.test?

a = hash[:a]
one_array.include?(a)
another_array.include?(a)
```

Long story short: A duplicate method call is a duplicate method call for Reek, regardless of any Ruby conventions. So Reek's stance on this issue is quite simple ;)

**Comment by monfresh** [comment]
Yes, I understand that you can do
```ruby
env = Rails.env
env.development? || env.test?
```
My question is, why do you think that is better? Do you think it's more readable? Or is there another reason?

**Comment by troessner** [comment]
So for me, it boils down to 2 reasons:

1.) Efficiency

```Ruby
Rails.env.development? || Rails.env.test?
```

is not as efficient as it could be. If the call to `env` is not memoized your basically paying twice in terms of computation for something that you should only pay once.

Here

```Ruby
Rails.env.development? || Rails.env.test?
```

you have 4 method calls while here:

```Ruby
env = Rails.env
env.development? || env.test?
```

you have one assignment (which is very cheap in terms of computation) and 3 method calls.
The difference might not be much here but just imagine you're writing a high performance app or you doing some expensive database calls in each method call.

It doesn't really matter though if the efficiency difference is significant. This is a matter of principle - we believe that being efficient is one of the vital traits of good software.

2.) Maintainability

The second point is a bit more subtle. This

```Ruby
env = Rails.env
env.development? || env.test?
```

is a lot more intention revealing than 

```Ruby
Rails.env.development? || Rails.env.test?
```

Here

```Ruby
env = Rails.env
env.development? || env.test?
```

I'm very clear on what I do: I get the environment and then I run some checks on it.

Here

```Ruby
Rails.env.development? || Rails.env.test?
```

I'm not very clear on what I do and it requires quite more mental effort: Ok, so I'm talking to Rails, getting the environment and then running a check on it ...or .....oh, I get the same Rails constant again, get the same environment and run another check on it.

**Comment by troessner** [comment]
Addendum: Thanks for asking this question @monfresh, this made me realize that we never really explained our reasoning behind this. See #1457

**Comment by troessner** [comment]
@monfresh did my explanation above answer your question? Closing this issue for now, feel free to re-open it.
