### ISSUE TITLE
Support running reek on open-ended range [1..]

### ISSUE THREAD

**Issue by olleolleolle** [troessner/reek#1460]
Open-ended range fails.

## Reproduce

Have a file with an open range.

```ruby
p [:a, :b, :c, :d, :e][2..]
```

Use 2.6.2.

```
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

Try the program with ruby:

```
$ ruby o.rb
[:c, :d, :e]
```

Run `reek` to inspect this file, and see failure on `unexpected token tRBRACK`:

```
$ reek o.rb
    Inspecting 1 file(s):
        !!!
        Source 'o.rb' cannot be processed by Reek due to a syntax error in the source file.

        This is a problem that is outside of Reek's scope and should be fixed by you, the
        user, in order for Reek being able to continue.

        Things you can try:
        - Check the syntax of the problematic file
        - If the file is not in fact a Ruby file, exclude it in your .reek.yml file

        Exception message:

        #<Parser::SyntaxError: unexpected token tRBRACK>

        Original backtrace:

        /Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/diagnostic/engine.rb:73:in `process'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/base.rb:262:in `on_error'
	/Users/olle/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
	/Users/olle/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/base.rb:167:in `parse'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/base.rb:184:in `parse_with_comments'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/source/source_code.rb:116:in `parse'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/source/source_code.rb:52:in `syntax_tree'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:116:in `syntax_tree'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:120:in `examine_tree'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:94:in `block in run'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:104:in `wrap_exceptions'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:93:in `run'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:61:in `smells'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:77:in `smelly?'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/report/progress_formatter.rb:43:in `progress'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/report/text_report.rb:22:in `add_examiner'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:25:in `each'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:17:in `execute'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/application.rb:32:in `execute'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/bin/reek:12:in `<top (required)>'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/reek:23:in `load'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/reek:23:in `<main>'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'

        !!!
.
```

Source: https://github.com/whitequark/parser/issues/564

See comment:
https://github.com/whitequark/parser/issues/564#issuecomment-475217626

**Comment by iliabylich** [comment]
I guess the issue comes from this line - https://github.com/troessner/reek/blob/79d7b1d98b786c31fcf540747053c348d870d989/lib/reek/source/source_code.rb#L4. Should be `require 'parser/current'`

**Comment by troessner** [comment]
Yes, I think @iliabylich is right on the money. Now that line was 'parser/current' a long time ago and I think, I think it was a conscious decision of us to change it but I can't for the life of mine remember why we actually did that and my quick and sloppy git history search hasn't made me any smarter. @mvz do you recall why we made that change to a specific version?

**Comment by mvz** [comment]
Ik think we wanted to force parsing as Ruby 2.5 even on older Rubies, back when 2.5 was the latest version.

**Comment by troessner** [comment]
Ah, yeah, I always forget that `Parser` has `Parser::CurrentRuby` but not `Parser::LatestRuby`. @iliabylich what are your thoughts about adding this or something similar to `Parser`?

To the problem: PR up in #1465

**Comment by iliabylich** [comment]
`Parser::LatestRuby` doesn't make sense to me. If you want to parse your code exactly how Ruby 2.something would parse it - use `parser/2something`. But in most cases you should use the version that matches your system ruby (i.e. which matches `RUBY_VERSION`) to reject invalid syntax and treat the code as your system ruby would do that.

I'd say `parser/current` is always the right choice.

**Comment by olleolleolle** [comment]
Thanks a lot everyone!

**Comment by troessner** [comment]
Just released v5.3.2 with the fix ;)

**Comment by mvz** [comment]
@iliabylich Reek needs to be lenient since it is not a syntax checker. With the way Ruby evolves, the latest parser generally accepts the widest range of syntax constructions. That is why we chose to always use the latest parser.

We could re-think this but we will need to improve the error message to be more user-friendly. It now looks too much like Reek just crashed. WDYT, @troessner?

**Comment by troessner** [comment]
@iliabylich the idea is that it doesn't matter what ruby version you're running locally. Reek should always use the parser for the latest. So running Reek under Ruby 2.3. should still use Parser26.
I imagine that quite a few other tools like Reek have the requirement for doing something like this, so I don't think we're the only one ;)

@mvz I agree, the error message is not ideal:

>> This is a problem that is outside of Reek's scope and should be fixed by you, the
        user, in order for Reek being able to continue.

I mean, that might be true in some cases but there's also cases like the one in this issue. In this case we, the Reek team, want you to report this back to us. How about adding something like:

>> If you believe that there's nothing wrong with your syntax, please open up an issue at the Reek repository

**Comment by mvz** [comment]
@troessner I have in mind making the message shorter, rather than longer.
