### ISSUE TITLE
Parsing Current Ruby and Syntax Error messages

### ISSUE THREAD

**Issue by mvz** [troessner/reek#1469]
This is a follow-up on #1460.

I'd like to discuss the following points:
* Should Reek parse with Parser's 'current ruby'?
* Should we simplify the Syntax Error message so it doesn't always look like Reek crashed?

My opinion is a tentative yes to both questions:
* The first change will avoid Reek having to play catch-up with Parser's development: If a new version of Ruby is supported by Parser, Reek will automatically support it when using the latest version of Parser. Syntax errors on older Rubies make sense because the code should be valid syntax anyway and Reek should probably not be the first thing you run when you change a file.
* The second change is mostly for aesthetic reasons but will hopefully also make instructions for actually checking the syntax stand out more.

**Comment by troessner** [comment]
That's an easy one: I'd give a strong yes in both cases :)

**Comment by chastell** [comment]
Me too, yes on both counts! :+1: :+1:

**Comment by etagwerker** [comment]
Yes to both. 👍

**Comment by mvz** [comment]
This was implemented in #1474.
