### ISSUE TITLE
IrresponsibleModule in config file causes Reek::Task to die

### ISSUE THREAD

**Issue by jdickey** [troessner/reek#1479]
Given the config file

```yaml
---

detectors:
  IrresponsibleModule:
    enabled: false
```

and the Rake task

```
Reek::Rake::Task.new do |t|
  t.config_file = 'config.reek'
  t.reek_opts = '-s'
  t.source_files = '{apps,lib}/**/*.rb'
end
```

I get the output when running `rake reek` of

```
0 total warnings
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/usr/local/bundle/gems/reek-5.4.0/lib/reek/rake/task.rb:127:in `reek_opts_as_arguments'
/usr/local/bundle/gems/reek-5.4.0/lib/reek/rake/task.rb:112:in `command'
/usr/local/bundle/gems/reek-5.4.0/lib/reek/rake/task.rb:107:in `run_task'
/usr/local/bundle/gems/reek-5.4.0/lib/reek/rake/task.rb:102:in `block in define_task'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => reek
(See full trace by running task with --trace)
```

| Tool | Version |
| ---- | ------- |
| Ruby | ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl] |
| Rake | rake, version 12.3.2 |
| Reek | reek 5.4.0 |
| Docker for Mac | Docker version 18.09.2, build 6247962 |

Running in a Docker container. Other such stacks (using Reek 5.2.0 and 5.3.0) have never exhibited this behaviour.

Help?

**Comment by mvz** [comment]
That is truly weird. Does the problem go away if you remove the IrresponsibleModule bit?

**Comment by jdickey** [comment]
The problem goes away if I remove `IrresponsibleModule` or if I replace it with *any other* smell; candidates tried include `DataClump`, `MissingSafeMethod`, `TooManyStatements`, and `UnusedParameters`. It's clearly specific to `IrresponsibleModule`.

**Comment by mvz** [comment]
I can't reproduce this I'm afraid. Does this happen with one particular project?

**Comment by mvz** [comment]
@jdickey does this problem still happen?

**Comment by jdickey** [comment]
Sorry for being away so long (health issue had me down for ~5 months). As of Reek 6.0.1, I'm good. Thanks for the help and *patience.*
