### ISSUE TITLE
Rule request: word cloud

### ISSUE THREAD

**Issue by Drenmi** [troessner/reek#1503]
Hello! 🙂 

I would like to propose a new smell, which I named after [one of the worst web design trends of the mid 2000's](https://en.wikipedia.org/wiki/Tag_cloud): the "word cloud". It happens when large arrays or string- or symbol literals are arranged with several elements on the same line.

**Example from RuboCop:**

```ruby
MANY_CHILD_NODES  = %i[dstr dsym xstr regexp array hash pair
                       mlhs masgn or_asgn and_asgn
                       undef alias args super yield or and
                       while_post until_post iflipflop eflipflop
                       match_with_lvasgn begin kwbegin return
                       in_match case_match in_pattern match_alt
                       match_as array_pattern array_pattern_with_tail
                       hash_pattern const_pattern].freeze
```

This layout makes it nearly impossible to add, edit, or remove an entry without re-arranging the entire array, lest you want to end up with line length offenses. The resulting git diff is a total mess, with little indication of what was actually changed.

(You can actually see from this example that something was probably removed from the second line of the array at some point, leaving it jarringly short. Fixing that would require all subsequent lines to be shifted.)

I speculate that this kind of layout is a result of an irrational fear of vertical space, that RuboCop itself is probably at least partially responsible for, with its `Metric/MethodLength` and `Metric/ClassLength` rules. 😬

**Comment by mvz** [comment]
That does look a bit like a mess. However, I'm not sure it fits in the 'code smell' category of problems. Isn't this more a rule that fits in RuboCop's Layout namespace?

I would also like to avoid adding new advice fights between Reek and RuboCop. :smile:

**Comment by Drenmi** [comment]
> I'm not sure it fits in the 'code smell' category of problems.

You might be right. In particular, it might not generalize well to other languages.

> Isn't this more a rule that fits in RuboCop's Layout namespace?

I'm thinking about adding it as an opt-in cop. I think the fear of vertical space will make most people anxious about it if it's enabled by default. 😅 

> I would also like to avoid adding new advice fights between Reek and RuboCop. 😄

😬

**Comment by mvz** [comment]
I'm going to close this as something that belongs in RuboCop or an equivalent code formatter.
