### ISSUE TITLE
[Defect] Remove codeclimate from runtime_dependency.

### ISSUE THREAD

**Issue by zw963** [troessner/reek#1507]
`codeclimate-engine-rb` **pull many gems**, but i have tested, those gem never used when i run reek command from a command line interface.

Infact, no this gem, reek can run successful on command line. (after comment several line of code for codeclimate/xml format),  do we consider add code make codeclimate acts as can plugged gem? 

Same issue as REXML gem.

Thank you!

**Comment by troessner** [comment]
Hey @zw963,

Thats a fair point. I guess we could make requiring that gem optional and have it only loaded in a codeclimate environment.  I am still on vacation, @mvz do you have some time to tackle this?

**Comment by mvz** [comment]
I'll take a look.

**Comment by zw963** [comment]
Thank you all.
