### ISSUE TITLE
Release Reek 6?

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1526]
Wanted to release the latest PR https://github.com/troessner/reek/pull/1525 but then I realized we have quite some breaking changes lined up, e.g. dropping support for Ruby 2.3.

Wdyt about doing a major release @mvz ?

**Comment by mvz** [comment]
Yes, let's do it! Our [milestone](https://github.com/troessner/reek/milestone/15) only has the one issue #1369 in it, and from my attempt at resolving it I can say that we should probably close it.

**Comment by mvz** [comment]
And released it is!
