### ISSUE TITLE
Alert on extra exclude rule

### ISSUE THREAD

**Issue by eloyesp** [troessner/reek#1547]
I really like the `--todo` feature, but I noticed that most of the issues are being fixed without one noticing, but it is really hard to clean the list to know better where is the smelling code. It would be awesome if reek alert somehow about exclude rules that are excluding smells that aren't there anymore.

Is something like this possible?

**Comment by troessner** [comment]
Yes, we would love to have that ;)
There's an issue for this already: #961 
We have no capacity to address this currently unfortunately so I wouldn't bet on it any time soon. PRs welcome ;)
