### ISSUE TITLE
Please update dependency on psych gem - Windows is stuck with Ruby < 2.6 constraint by reek

### ISSUE THREAD

**Issue by KevinBuchs** [troessner/reek#1556]
reek (~> 6.0) x64-mingw32 was resolved to 6.0.1, which depends on
      psych (~> 3.1.0) x64-mingw32 was resolved to 3.1.0, which depends on
        Ruby  (< 2.6, >= 2.3) x64-mingw32

Psych 3.2 has a dependency on Ruby >= 2.4.

**Comment by mvz** [comment]
Possibly related to #1531

**Comment by mvz** [comment]
This was already fixed in #1549 but hasn't been released yet.

**Comment by mvz** [comment]
And released it is! Installing Reek 6.0.2 should work for your case @KevinBuchs.

**Comment by KevinBuchs** [comment]
Thanks! I appreciate the rapid turn around. Glad it was so easy to resolve.

Kevin Buchs, Senior Engineer, New Context Services <https://newcontext.com>
kevin.buchs@newcontext.com  507-251-7463  St. Cloud, MN
