### ISSUE TITLE
Backlink to inappropriate site(s)

### ISSUE THREAD

**Issue by babakgh** [troessner/reek#1558]
Probably you want to remove any link to [solnic dot eu] from your documents like https://github.com/troessner/reek/blob/v5.4.1/docs/Control-Couple.md ( then click on **here** )

**Comment by mvz** [comment]
Yeah definitely. Looks like @solnic let his old domain expire or something. The article is now here: https://solnic.codes/2012/04/11/get-rid-of-that-code-smell-control-couple/

**Comment by mvz** [comment]
Oh, this was already fixed in #1516. Nothing much we can do about documentation for old Reek versions I'm afraid.

**Comment by solnic** [comment]
yeah sorry about that, I lost this domain when I was on a sick leave a year ago. I wasn't checking my emails etc. and missed the payment deadline 😭

**Comment by mvz** [comment]
No problem, @solnic
