### ISSUE TITLE
Glob patterns in exclude_paths

### ISSUE THREAD

**Issue by tleish** [troessner/reek#1560]
Is there a specific reason Glob patterns are not supported in `exclude_paths`?  The following change would add support for glob patterns and be backwards compatible with previous configuration.

```diff
# frozen_string_literal: true

require_relative './configuration_validator'
require_relative '../errors/config_file_error'

module Reek
  module Configuration
    #
    # Array extension for excluded paths.
    #
    module ExcludedPaths
      include ConfigurationValidator

      # @param paths [String]
      # @return [undefined]
      def add(paths)
-       paths.each { |path| self << Pathname(path) }
+       paths.flat_map { |path| Dir[path] }
+            .each { |path| self << Pathname(path) }
      end
    end
  end
end
```

If there is not reason for avoid glob patterns and this were an acceptable solution, I'd be happy to create the MR.

**Comment by troessner** [comment]
Hello Hello :) 

I can't recall that we had a specific reason for that. I'd happily review a MR if you're still up to doing it ;)
