### ISSUE TITLE
Fix UtilityFunction false positive with Kernel refinement

### ISSUE THREAD

**Issue by bkuhlmann** [troessner/reek#1563]
## Overview

Seeing the following warning:

``` bash
lib/versionaire/cast.rb -- 1 warning:
  [7]:UtilityFunction: Versionaire::Cast#Version doesn't depend on instance state (maybe move it to another class?) [https://github.com/troessner/reek/blob/v6.0.2/docs/Utility-Function.md]
```

...for this refinement:

``` ruby
module Versionaire
  # Refines Kernel in order to provide a top-level Version conversion function.
  module Cast
    refine Kernel do
      def Version object
        Versionaire::Version object
      end
    end
  end
end
```

Potential Usage:

``` ruby
using Versionaire::Cast

Version "1.2.3"  # => #<struct Versionaire::Version major=1, minor=2, patch=3>
```

## Desired Behavior

It would be nice to not flag this as a violation in this case. This is similar in nature to what was [reported earlier](https://github.com/troessner/reek/issues/1438).

## Notes

I do a lot with refinements so, for context, this might help:

- [Refinements](https://www.alchemists.io/projects/refinements) - A collection of enhancements to Ruby core classes.
- [Versionaire](https://www.alchemists.io/projects/versionaire) - The Ruby `Version` type, shown above, that I'd like to access at the Kernel level much like `Integer`, `String`, `Array`, `Hash`, etc.

**Comment by mvz** [comment]
This makes sense. I'm going to take a look at how we can support refinements in Reek.

**Comment by bkuhlmann** [comment]
In case it's of interest/help, here's the Reek [configuration](https://github.com/bkuhlmann/versionaire/blob/master/.reek.yml) I ended up settling on to workaround this issue:

``` 
detectors:
  UncommunicativeMethodName:
    exclude:
    - Cast#Version
    - Versionaire#Version
  UtilityFunction:
    exclude:
    - Versionaire::Cast#Version
```

Due to implementing a Ruby cast/conversion function, this also causes Reek's to `UncommunicativeMethodName` to trip too.

**Comment by mvz** [comment]
I've investigated this a bit further and it looks like even if Reek correctly recognizes refinements (and it should!), this would still be considered a UtilityFunction, just like in the following case:

```ruby
module Foo
  def Version object
    Versionaire::Version object
  end
end
```

However, with proper support, you should be able to exclude `Kernel#Version` instead of `Cast#Version`.

**Comment by bkuhlmann** [comment]
:bow: @mvz. OK, so reduced to a utility function but not uncommunicative if I understand correctly? Yep, I'll give this a look once the next version is released of Reek. :wink:
