### ISSUE TITLE
Two files that cause Reek to crash

### ISSUE THREAD

**Issue by pitosalas** [troessner/reek#1586]
These two files cause Reek to crash after saying that there was a syntax error. I don't know if the crash and stack trace are intentional.

[bad1.txt](https://github.com/troessner/reek/files/5958326/bad1.txt)
[bad.txt](https://github.com/troessner/reek/files/5958328/bad.txt)

**Comment by troessner** [comment]
Both files contain syntax errors because at least one "end" is missing in both (just did a cursory glance) so this is not related to Reek:

> ruby -c bad.txt
bad.txt:60: syntax error, unexpected end-of-input, expecting `end'

**Comment by pitosalas** [comment]
Agreed. But I was just asking whether the stack trace was intentional.

**Comment by troessner** [comment]
Yes, the stacktrace at the end of Reeks output is indeed intentional ;)
