### ISSUE TITLE
Possible false positive on UtilityFunction

### ISSUE THREAD

**Issue by guillermoap** [troessner/reek#1587]
Hello,

The method `process_file` is triggering the `UtilityFunction`.
This is a helper module, why is it complaining about it not depending on the instance state?

```ruby
module RepositoryHelper
  CLONE_PATH = Rails.root.join('tmp').to_s
  LOGGER = Rails.logger
  
  ...
  
  def process_file(path, pattern_name, sub_options = [])
    IO.write(path, File.open(path) { |file| file.read.gsub(*sub_options) })
    LOGGER.info("Substituted #{pattern_name} in #{path}")
  end
end
```

**Comment by troessner** [comment]
Yeah, that was a design decision we took a loooong time ago and it surely was a controversial one ;)
In short, we consider helper modules smelly by definition, hence Reek raises an alert. For more details see [here](https://github.com/troessner/reek/blob/master/docs/Utility-Function.md).

You can either disable raising an alert for these methods via [magic comment](https://github.com/troessner/reek/blob/master/docs/Smell-Suppression.md) or if you want to disable it for that whole file tweak your Reek configuration like detailed [here](https://github.com/troessner/reek#configuration-file), e.g. in your case by adding

>
---
detectors:
  UtilityFunction:
    exclude:
      - "RepositoryHelper#process_file"

**Comment by mvz** [comment]
Also see https://github.com/troessner/reek#working-with-rails

**Comment by guillermoap** [comment]
Didn't know that, thanks for the suggestion. I ended up disabling it. 

Thanks for the help. Closing this
