### ISSUE TITLE
Reek breaking down!

### ISSUE THREAD

**Issue by OfficeYAportatil** [troessner/reek#1593]
Hi there.

I have been using **reek** for a long time, without any problems, until now.

I just installed rails & friends on my new computer, and, reek does not work. It seems it has some issue with sexp_node.

When I call it like this:
`$ reek app/controllers/clasificactions_controller.rb`

I get:
`Traceback (most recent call last):
	40: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	39: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	38: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/reek:23:in `<main>'
	37: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/reek:23:in `load'
	36: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/bin/reek:11:in `<top (required)>'
	35: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/cli/application.rb:25:in `execute'
	34: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/cli/reek_command.rb:22:in `execute'
	33: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/cli/reek_command.rb:22:in `each'
	32: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/cli/reek_command.rb:23:in `block in execute'
	31: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/cli/reek_command.rb:23:in `new'
	30: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/examiner.rb:34:in `initialize'
	29: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/source_repository.rb:29:in `each'
	28: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/source_repository.rb:29:in `each'
	27: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/examiner.rb:34:in `block in initialize'
	26: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/sniffer.rb:27:in `report_on'
	25: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:23:in `process'
	24: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:42:in `process_class'
	23: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:34:in `process_module'
	22: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:161:in `push'
	21: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:35:in `block in process_module'
	20: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:28:in `process_default'
	19: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:28:in `each'
	18: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:28:in `block in process_default'
	17: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:23:in `process'
	16: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:46:in `process_defn'
	15: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:146:in `handle_context'
	14: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:161:in `push'
	13: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:149:in `block in handle_context'
	12: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:155:in `check_smells'
	11: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/sniffer.rb:32:in `examine'
	10: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/smell_repository.rb:53:in `examine'
	 9: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/smell_repository.rb:53:in `each'
	 8: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/smell_repository.rb:54:in `block in examine'
	 7: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/smells/smell_detector.rb:70:in `examine'
	 6: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/smells/unused_parameters.rb:28:in `examine_context'
	 5: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/smells/unused_parameters.rb:69:in `zsuper?'
	 4: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/sexp_processor-4.15.2/lib/sexp.rb:192:in `find_node'
	 3: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/sexp_processor-4.15.2/lib/sexp.rb:210:in `find_nodes'
	 2: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `each_sexp'
	 1: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `each'
/home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `block in each_sexp': no block given (yield) (LocalJumpError)
`
This fail also happens when **rubycritic** calls **reek**

Now, this is the content of my `Gemfile`:
`source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.2"

gem "bcrypt", "3.1.16"
gem "bootsnap", ">= 1.4.4", require: false
gem "coffee-script"
gem "devise"
gem "haml"
gem "jbuilder", "2.7"
gem "puma", "5.0"
gem "rails", " 6.1.3"
gem "sass-rails", ">= 6"
gem "sqlite3", "1.4"
gem "turbolinks", "5"
gem "webpacker", "5.0"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "guard"
  gem "guard-minitest"
end

group :development do
  gem "guard-flog"
  gem "guard-rails_best_practices"
  gem "brakeman"
  gem "consistency_fail"
  gem "flog"
  gem "fly"
  gem "guard-annotate"
  gem "guard-brakeman"
  gem "guard-bundler", require: false
  gem "guard-coffeelint" # coffeelint --makeconfig > coffeelint.json
  gem "guard-consistency_fail" # falla el init
  gem "guard-haml_lint"
  gem "guard-livereload", "2.5", require: false
  gem "guard-migrate"
  gem "guard-puma"
  gem "guard-railsbp"
  gem "guard-reek"
  gem "guard-rubocop"
  gem "guard-rubycritic" 
  gem "guard-shell"
  gem "listen", "3.3"
  gem "rack-mini-profiler", "2.0"
  gem "rails_best_practices"
  gem "reek", require: false
  gem "rubocop", require: false
  gem "rubocop-i18n"
  gem "rubocop-minitest", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubycritic", require: false
  gem "spring"
  gem "web-console", ">= 4.1.0"
end

group :test do
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  gem "simplecov", require: false
  gem "webdrivers"
end`
(I remove some "~>" to avoid markdown issues)

The versions that I am using are:
**rails** 6.1.3
**ruby** 2.7.2p137
**gem** 3.1.4
**node** 14.16.0

**Comment by mvz** [comment]
@OfficeYAportatil you can add code block markers (triple backticks) around your code in markdown. It will look much better. Can you please edit your ticket?

See https://github.github.com/gfm/#fenced-code-blocks

**Comment by mvz** [comment]
@OfficeYAportatil it looks like you're using reek version 1.3.8, which is from 2014. Can you please try with a more recent version?

**Comment by OfficeYAportatil** [comment]
hi, sorry for the delay, i was out of the city. let me work on this and i will notify you soon

**Comment by OfficeYAportatil** [comment]
Man, you are right. I upgraded reek into version 6.0.3 and everything is working great. Thanks a lot.
