### ISSUE TITLE
Psych 4.0 has breaking changes

### ISSUE THREAD

**Issue by Paul-Yves** [troessner/reek#1606]
After `Loosen dependency on psych`, psych 4 is now loaded but has some breaking changes. A lot of my spec fail now `Psych::DisallowedClass: Tried to load unspecified class: Date` (or BigDecimal), all during a `expect(something).to be_delayed`. I do not use psych in my project, it's only here because of reek and I have no idea how to configure it to fix (gem issues suggest calling psych with specific params).

Any one ran into that issue ?

**Comment by mvz** [comment]
Just to be clear, this error happens when you load some yaml unrelated to Reek, right?

My suggestion would be to add an explicity dependency on psych 3 to your project.

**Comment by Paul-Yves** [comment]
As far as I know no yaml is loaded but you are right, it seems to be specific to Psych I will see on their github.

**Comment by mvz** [comment]
The backtrace of the spec failure should tell you where yaml is loaded. If necessary, pass `-b` to rspec to show all lines of the backtrace.

Have you tried my suggestion to add an explicit dependency on psych 3? For example, you can add the following line to your Gemfile:
```ruby
gem "psych", "~> 3.0"
```

**Comment by Paul-Yves** [comment]
Yes it's working perfectly, I will use that in last resort

**Comment by marcelolx** [comment]
Our build broke today too because of Psych 4.0, explicit setting psych to 3 solves the problem. In our case, the problem is because of config files that use aliases and we are running Rails 6.0 which at this moment don't support those aliases https://github.com/rails/rails/pull/42257#issuecomment-844051751

**Comment by lostapathy** [comment]
Is there a reason reek needs to have an explicit dependency on psych in the gemspec?  I've run out of a fork that removed for a while.

Ruby has included psych by default for quite some time now, so it's available even if reek doesn't demand it in its .gemspec.  If nothing in the Gemfile is asking for psych, bundler won't ever pull in a newer-than-system psych, and then this type of error doesn't happen.

**Comment by mvz** [comment]
@lostapathy yes, it seems psych is a default gem even in Ruby 2.5.0, the lowest version we support now. I'll make a pull request to remove psych as an explicit dependency.

**Comment by mvz** [comment]
Well, that didn't work, since:

- We actually still support Ruby 2.4, but that shouldn't be the case for long
- Even on Ruby 2.5, the system psych does not support the `permitted_classes` option, which we use.

**Comment by mvz** [comment]
Fix released in version 6.0.6.
