### ISSUE TITLE
Errors when building YARD index

### ISSUE THREAD

**Issue by Ji-You** [troessner/reek#1627]
Could anyone please help me troubleshoot this issue?
For context, I am trying to run `yard gems` in my project directory for solargraph. (https://solargraph.org/guides/yard)
However, when it tries to generate documentation for `reek` gem, it outputs following error:
```
[info]: Building yardoc index for gem: reek-6.0.6
[error]: The file `./docs/yard_plugin.rb' could not be loaded:
cannot load such file -- ./docs/yard_plugin.rb
```
Your help would be most appreciated.

**Comment by troessner** [comment]
What would be the easiest way for us to reproduce this?

**Comment by Ji-You** [comment]
1. Enable auto-generation of docs `yard config --gem-install-yri`
2. Install reek `gem install reek`

Expected:
- Documentation is auto-generated for `reek` gem

Actual:
- It errors with following message:
```
$ gem install reek
Fetching: reek-6.0.6.gem (100%)
Successfully installed reek-6.0.6
Building YARD (yri) index for reek-6.0.6...
[error]: The file `./docs/yard_plugin.rb' could not be loaded:
cannot load such file -- ./docs/yard_plugin.rb
```

**Comment by anicholson-sq** [comment]
I had this issue too – I did this to workaround it:

```shell
$ pushd $(bundle show reek)
$ mkdir -p docs
$ touch docs/yard_plugin.rb
$ popd
```

and then yard was able to process `reek` with no issues…

**Comment by Ji-You** [comment]
@anicholson-sq 's workaround solved my problem. Thank you. I'm closing this issue now.
