### ISSUE TITLE
UtilityFunction and Concerns

### ISSUE THREAD

**Issue by vsviridov** [troessner/reek#1645]
I have a module which is then `include`d as per `ActiveSupport::Concern` pattern.

There are several methods placed under
```ruby
module SomeConcern
  extend ActiveSupport::Concern

  class_methods do
    def some_class_method
    ...
    end
  end
```

I get a bunch of `UtilityFunction` smells, because it doesn't seem to correctly recognize that those mehtods do end up as class methods already.

**Comment by mvz** [comment]
Hi @vsviridov, this is a duplicate of #1538.
