### ISSUE TITLE
Fix ModuleInitialize false positive with custom Data constructor

### ISSUE THREAD

**Issue by bkuhlmann** [troessner/reek#1682]
## Overview

Hello. :wave: I'm working on upgrading to [Ruby 3.2.0](https://www.ruby-lang.org/en/news/2022/12/06/ruby-3-2-0-rc1-released) by leveraging the new [Data](https://zverok.space/ruby-rdoc/Data.html) primitive and discovered a slight bug where Reek doesn't handle a custom `Data` constructor.

## Screenshots

![2022-12-18_11-04-29-iTerm2](https://user-images.githubusercontent.com/50245/208312370-7c6b7b93-36c1-432e-ab81-afcece9700e6.png)

## Steps to Recreate

- Install [Ruby 3.2.0 RC1](https://www.ruby-lang.org/en/news/2022/12/06/ruby-3-2-0-rc1-released).
  - If you need a Docker image for quick experimentation, I have [one built using Ruby 3.2.0 RC1](https://www.alchemists.io/projects/docker-alpine-ruby). You'd just need to use the `latest` image. Otherwise, installing Ruby via your favorite Ruby version manager will work too.
- Save the code snippet (provided below) as `test.rb` and run as `reek test.rb` to reproduce. 
<details>
  <summary>Example Code Snippet</summary>

``` ruby
# frozen_string_literal: true

RootMail = Data.define :from, :to do
  # ✅ Reek doesn't detect this as a code smell.
  def initialize from: nil, to: nil
    super
  end
end

module Demo
  Mail = Data.define :from, :to do
    # ❌ Reek thinks this is a code smell.
    def initialize from: nil, to: nil
      super
    end
  end
end
```
</details>

## Workaround

As a workaround, I can configure Reek to ignore the source files with false positives but would definitely prefer not to have to do that. 😅 

## Environment

- **Ruby**: ruby 3.2.0rc1 (2022-12-18) [arm64-darwin22.2.0]
- **Reek**: 6.1.2

**Comment by mvz** [comment]
Thanks, @bkuhlmann, I'll take a look.

**Comment by bkuhlmann** [comment]
Hey. :wave: Wanted to touch base on this. Would this be possible to support? I run into this a lot when working `Data` primitives and would make using them more enjoyable when this isn't flagged.

**Comment by mvz** [comment]
Hi @bkuhlmann thanks for the ping. I've created a pull request for this.
