### ISSUE TITLE
Possible bug or improvement for error undefined method `keys'

### ISSUE THREAD

**Issue by fbuys** [troessner/reek#1734]
Current behaviour
When a user:
- Defines a directory with a detector in the .reek.yml
- But fails to provide a configuration for the detector
It:
- Fails
- And produces a cryptic message that reads:
```
configuration_converter.rb:66:in `convertible_attributes': undefined method `keys' for nil:NilClass (NoMethodError)
```

Expected behaviour
When a user:
- Defines a directory with a detector in the .reek.yml
- But fails to provide a configuration for the detector
It:
- Does not fail
- Warns the user that they might be missing configuration for a specific directory + detector.
- Continues and produces reek result for the correctly defined detectors.

See: `lib/reek/configuration/configuration_converter.rb` (method convertible_attributes)
See: `lib/reek/configuration/configuration_converter.rb` (method strings_to_regexes_for_detectors)
See: `lib/reek/configuration/configuration_converter.rb` (method strings_to_regexes_for_directories)

Repo: 
- Clone: https://github.com/fbuys/reek_issue_1734
- bundle install
- run `bundle exec reek .`
- see error
- see `.reek.yml` config

**Comment by mvz** [comment]
This has been fixed in #1749.
