### ISSUE TITLE
Consider replacing the yaml schema validator

### ISSUE THREAD

**Issue by fbuys** [troessner/reek#1742]
The current validator seems outdated and lacks good documentation.

A recent issue showed that we could improve the schema validation to also check and warn against missing configurations
See: #1734 

[dry-schema](https://dry-rb.org/gems/dry-schema/1.13/) provide good documentation and it looks like it also provides the features we require.
> [Structural validation](https://dry-rb.org/gems/dry-schema/1.13/optional-keys-and-values) where key presence can be verified separately from values. This removes ambiguity related to "presence" validation where you don't know if value is indeed nil or if a key is missing in the input hash

**Comment by mvz** [comment]
I agree. dry-schema looks great.

**Comment by mvz** [comment]
@troessner WDYT? I think you picked Kwalify originally so may have more of an opinion on this.

**Comment by troessner** [comment]
Yeah, I think when I picked Kwalify dry-schema didn't exist yet, time flies 😆 
I agree that dry-schema looks great, would certainly be open to a PR that introduces it!

**Comment by fbuys** [comment]
I'll try to open a PR soon that adds dry-schema, seems like that might be a 2 in 1 win (fixing this issue and https://github.com/troessner/reek/pull/1741).

Thank you very much for the feedback @mvz and @troessner 🙇

**Comment by fbuys** [comment]
I opened a PR that could close this issue
