### ISSUE TITLE
Update to Parser 3.3.0

### ISSUE THREAD

**Issue by bkuhlmann** [troessner/reek#1762]
## Why

Hello. :wave: Would it be possible to upgrade to Parser 3.3.0 since it's not possible to upgrade to [RuboCop 1.60.0](https://github.com/rubocop/rubocop/releases/tag/v1.60.0) since it requires Parser 3.3.0 or higher? Here's the error I get when updating to RuboCop 1.60.0 and attempting to use Reek 6.2.0 at the same time:

``` 
Could not find compatible versions

Because reek >= 6.1.4 depends on parser ~> 3.2.0
  and rubocop >= 1.60.0 depends on parser >= 3.3.0.2,
  reek >= 6.1.4 is incompatible with rubocop >= 1.60.0.
And because every version of caliber depends on rubocop ~> 1.60,
  reek >= 6.1.4 is incompatible with caliber >= 0.
So, because Gemfile depends on caliber >= 0
  and Gemfile depends on reek ~> 6.2,
  version solving has failed.
```

## How

This should only require updating the `reek.gemspec` to `spec.add_runtime_dependency 'parser',  '~> 3.3.0'`. This is related to this [code review](https://github.com/troessner/reek/pull/1763).

## Notes

- **OS**: macOS 13.6.3
- **Ruby**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [arm64-darwin22.6.0]
- **Reek**: 6.2.0

**Comment by BrianHawley** [comment]
#1761 fixed this, but it still needs to be released.

**Comment by bkuhlmann** [comment]
Thanks!

Also, with [RuboCop 1.60.1](https://github.com/rubocop/rubocop/releases/tag/v1.60.1) out, the [build failures](https://github.com/troessner/reek/pull/1764) should be able be resolved now.

**Comment by mvz** [comment]
Release 6.3.0 is out now and uses Parser 3.3.x: https://github.com/troessner/reek/pull/1767
