### ISSUE TITLE
Special treatment for utility methods that only raise?

### ISSUE THREAD

**Issue by snusnu** [troessner/reek#181]
Hey guys, I'm wondering why the following doesn't smell like a utility function. Can someone explain the reasoning to me? or is it a bug?

```ruby
# Test for demonstrating a UtilityFunction edgecase
class Test
  def raise_if_necessary(msg)
    raise RuntimeError, msg
  end

  def kernel_raise_if_necessary(msg)
    Kernel.raise RuntimeError, msg
  end
end

# mungo:snippets snusnu$ reek reek.rb
# reek.rb -- 0 warnings
```

EDIT: moved the code inline instead of linking to a pastie

**Comment by mvz** [comment]
This behavior is not a bug: A function is not deemed a UtilityFunction if it only contains one statement.
