### ISSUE TITLE
FeatureEnvy is inconsistent

### ISSUE THREAD

**Issue by mvz** [troessner/reek#215]
```ruby
# An amazing class with a comment
class Foo
  def envy(val)
    if smurf
      val + 1
    else
      val - 1
    end
  end

  def no_envy(val)
    if self.smurf
      val + 1
    else
      val - 1
    end
  end
end
```

The method `envy` is declared smelly by reek, while `no_envy` is not. This is inconsistent. Looking at the code, it seems reek considers the first method to refer to self only once, and the second twice.

**Comment by troessner** [comment]
This has been here for more than a year with nothing happening. 
Closing this. Whoever decides to work on this can just re-open it.
