### ISSUE TITLE
Clean up/organize command line options

### ISSUE THREAD

**Issue by mvz** [troessner/reek#254]
For reek 1.4 (or 2.0), we should take a good look at the set off command line options. Right now, they're a little bit of a mess due to backwards-compatibility considerations and organic growth. Let's see if we can restructure them and perhaps even get rid of some of them.

**Comment by mvz** [comment]
So summarize, what I'll be doing is re-organizing and simplifying the set of switches, but keeping the total set of options intact.

**Comment by troessner** [comment]
Closing now that #372 is merged.
