### ISSUE TITLE
Odd case of FeatureEnvy

### ISSUE THREAD

**Issue by mvz** [troessner/reek#260]
Reek signals that the following code smells of FeatureEnvy in the `#initialize` method:

```ruby
module GirFFI
  # Exception class to be raised whenever an error is signaled through
  # GLib::Error.
  class GLibError < RuntimeError
    attr_reader :domain_quark
    attr_reader :code

    def initialize g_error
      @domain_quark = g_error.domain
      @code = g_error.code
      super g_error.message
    end

    def domain
      @domain ||= GLib.quark_to_string @domain_quark
    end
  end
end
```

This seems rather odd to me. I'm mainly creating this issue in order to not forget about it. I don't yet know if this needs fixing.

**Comment by troessner** [comment]
This has been here for more than a year with nothing happening. 
Closing this. Whoever decides to work on this can just re-open it.
