### ISSUE TITLE
false positive on NestedIterators with begin/rescue

### ISSUE THREAD

**Issue by abacha** [troessner/reek#268]
````
  def perform(clients = nil)
    clients.each do |client|
      begin
        ...
        klass.deliver_to(client.id, account_ids)
      rescue InvalidClient
        next
      end
    end
  end
````
``ClientDeliveryWorker#perform contains iterators nested 2 deep (NestedIterators)``

**Comment by troessner** [comment]
@abacha sorry for the late reply. Basically @PeterCamilleri hit the nail pretty much on the head already. I labeled this as a defect and we'll look into the rescue issue. (Like Peter already pointed out, not sure if there is much that we can do regarding the nested blocks.)

**Comment by troessner** [comment]
Now with reek 2 out of the door I'll look into the rescue issue.

**Comment by troessner** [comment]
@abacha with current versions of reek the nested-iterators-problem isn't an issue anymore:

```Bash
cat nested_iterators_test.rb
```

```Ruby
def perform(clients = nil, x)
  clients.each do |client|
    begin
      #...
      klass.deliver_to(client.id, account_ids)
    rescue InvalidClient
      next
    end
  end
end
```

Gives me:

```Bash
 ( $ (master)) reek nested_iterators_test.rb 
nested_iterators_test.rb -- 1 warning:
  [1]:perform has unused parameter 'x' (UnusedParameters)
```

Or just nothing if I leave out the "x" (that one was just there as safety test that reek still works).

Which basically means: https://www.youtube.com/watch?v=G-C1dRZ_hps

-> Closed.
