### ISSUE TITLE
Allow more fine grained code context

### ISSUE THREAD

**Issue by waiting-for-dev** [troessner/reek#294]
I've been playing with [`exclude` configuration option](https://github.com/troessner/reek/wiki/Basic-Smell-Options) and it seems to only recognize method  and class names. It would nice it to be able to match code context in more detail, like method content.

I have in mind to disable [NestedIterators](https://github.com/troessner/reek/wiki/Nested-Iterators) smell for [Rails respond_to](http://apidock.com/rails/ActionController/MimeResponds/respond_to), which always will have a nested block.

I know that you [recommend not using it in Rails except that for models](https://github.com/troessner/reek/wiki/Working-with-Rails) due to false positives, but I'm trying to use it anyway to at least catch the negatives, and surely it could be useful in other situations.

Thanks.

**Comment by troessner** [comment]
Do you have an example in mind of how this

>> It would nice it to be able to match code context in more detail, like method content.

could look like syntactically?
Also, since we're busy with reek 2 and also still have a couple of annoying defects to fix would you care for a pull request?..:)

**Comment by waiting-for-dev** [comment]
Hey, thanks for your reply. No, I haven't anything in mind. I just thought it would be a good option but I don't know anything about reek internals so no idea if it is difficult or easy. If I have the time I would look into it in more detail, but to be honest right now I'm also too busy :(

**Comment by troessner** [comment]
Ok, fair enough.

Closing this for now since both the syntax and the semantics of this feature request are unclear - please feel free to re-open it once you have a more concrete suggestion.:)
