### ISSUE TITLE
Re-visit reek task

### ISSUE THREAD

**Issue by mvz** [troessner/reek#326]
As mentioned in #325, there are some odd things about the reek task provided:

* Why is the library path altered? The user is supposed to have reek installed.
* Why is ruby called, and not directly reek? This only makes sense if you're working on reek itself and don't have it installed.
* Why provide a way to add options to ruby?
* The task changes the normal default config file behavior.

I'd like to revisit this task and simplify it.

**Comment by troessner** [comment]
@mvz are you working on this? Otherwise i could start with that when my little girl is resting (i now also have that screaming baby problem..;) )

**Comment by mvz** [comment]
@troessner no, go right ahead. And congratulations on your daughter, screaming or not :-).
