### ISSUE TITLE
Uncommunicative Name should not apply to Enumerable methods

### ISSUE THREAD

**Issue by ashmoran** [troessner/reek#35]
I don't think Uncommunicative Name should apply to Enumerable methods.  The following is (to me, at least) perfectly understandable:

```
users.map { |u| u.name }
```

WDYT?

GitHub issues working for me again :)

**Comment by EdvardM** [comment]
Not sure if this is a good place to comment, but what bothers me maybe the most is that
while `users.map { |u| u.name }` is not hard to change to `users.map { |u| u.name }`, there are few issues with it. First, `users.map { |user| user.name }` makes `users` and `user` a bit too similar, while having a short name makes it immediately obvious that it's a different variable. Not a big issue, but if you are reading lots of code, preferably it's so fast and easy to read you don't need to double-check things. The shortcut version is obvious in few milliseconds, while the longer isn't, but it can be just me. Though in this case I'd just prefer to use `users.map(&:name)`, which is even more obvious.

Maybe even worse, eg. rubocop says that when you use inject, the accumulator should be a and element e, eg. `array_of_nums.inject { |a, e| a + e }`. Of course I can just whitelist those with the regex, but overall what concerns me is that different tools consider something as a bad style, while others don't. Also, if I approve `a` and `e` then I can use `a` and `e` separately without inject, which is not the idea, but I'm kinda ok with that too. 

Note, I don't mean to criticize reek. I know checking code quality metrics by using fixed rules is really hard, yet I find reek very useful for quickly identifying files that likely need most work. It's a good tool :)

**Comment by mvz** [comment]
Hi @EdvardM,

> Not sure if this is a good place to comment,

Well, this issue was closed in 2009, so I was going to say 'no', but then again it doesn't make much sense to open a new, identical, issue, so there you go :smile:.

To address your comments:

* For one-line blocks, `u` can be good parameter name, but as soon as the block becomes larger, the clarity starts to suffer.
* I generally use `it` as a block parameter these days. This is a meaningful name, but avoids being too similar to, or clashing with, variables defined outside the block. If you need more than one parameter, you're generally better of using slightly longer names.
* Yes, Reek and RuboCop don't agree on this, but you must agree that `array_of_nums.inject { |a, e| a + e }` is not exactly an emblem of clarity. I generally disable this cop.

**Comment by troessner** [comment]
>> For one-line blocks, u can be good parameter name, but as soon as the block becomes larger, the clarity starts to suffer.
I generally use it as a block parameter these days. This is a meaningful name, but avoids being too similar to, or clashing with, variables defined outside the block. If you need more than one parameter, you're generally better of using slightly longer names.
Yes, Reek and RuboCop don't agree on this, but you must agree that array_of_nums.inject { |a, e| a + e } is not exactly an emblem of clarity. I generally disable this cop.

I agree with @mvz on this one.

**Comment by EdvardM** [comment]
Thanks! I actually like that `it`, while being aware that it'd be very bad to over-use that. Often using a longer name is good, and I use exactly the same heuristics: if the line is a single short one-liner with a map, an abbrev does just fine. Other than that, I use the long name or an abbreviation -- though often consisting of at least 3 chars. 

In Python people often use `elt` for elem, which I kinda like. Maybe I should complain about this in Rubocop project though, as I actually agree that `a, e` is not a nice pair. Even `acc, e` would be at least 73.42 % better than just `a, e`, but I already like `acc, it` even more.

Thanks for the feedback!
