### ISSUE TITLE
reek 2 release notes

### ISSUE THREAD

**Issue by troessner** [troessner/reek#385]
Let's discuss the article I'll try to get published by the Ruby NL and hackernews:

This is what we got so far:

------------------------------

A couple of days ago we released the new and extremely shiny reek version 2 to the world!
 
For those of you who don't know `reek`, `reek` is a static code analyzer for Ruby detecting so called [code smells](https://github.com/troessner/reek/wiki/Code-Smells). Those code smells range from rather trivial ones like [UncommunicativeParameterName] (https://github.com/troessner/reek/wiki/Uncommunicative-Parameter-Name) or [TooManyMethods] (https://github.com/troessner/reek/wiki/Too-Many-Methods) to high-level code smells like [FeatureEnvy] (https://github.com/troessner/reek/wiki/Feature-Envy) or [DataClump] (https://github.com/troessner/reek/wiki/Data-Clump)
 
In the most simple use case you can just run

```Bash
reek my/source/files
```
 
or 
 
```Bash
echo "def dirty(x,y,z); puts 'hossa!'; end" | reek
```
 
So what has happened since 1.*?
 
There are way too many significant changes to list them all so I restrict this list to favourite ones (excluding the countless bugfixes):

**Support**
 
Parse with the `parser` gem allows us to support all major ruby versions:
 
1.9.3
2.0
2.1
2.2.

We deliberately dropped support for 1.8.
 
**New smells**

We introduced 2 new smells:
 
- The [ModuleInitialize smell] (https://github.com/troessner/reek/wiki/Module-Initialize)
- The [Prima Donna Method smell] (https://github.com/troessner/reek/wiki/Prima-Donna-Method)

**Configuration**

We completely revised our configuration handling, basically there are 3 ways of passing reek a configuration file: Using the cli `-c` switch, having a file ending with .reek either in your current working directory or in a parent directory (more on that later), or having a file ending with .reek in your HOME directory.
This means that reek no longer tries to nest configuration files, but instead from reek's point of view there exists only one configuration file and one configuration.

Another cool feature is support for detecting specific smells like this:

```Bash
reek lib/ --smell FeatureEnvy
```

This can be very helpful when refactoring when you want to focus on one group of problems.

And last but not least smell detectors can be configured or disabled in code comments like this (in addition to reek's regular [configuration mechanism] (https://github.com/troessner/reek/wiki/Basic-Smell-Options):

```Ruby
# This method smells of :reek:NestedIterators
def smelly_method foo
  foo.each {|bar| bar.each {|baz| baz.qux}}
end
```

**CLI / Output / UX**
 
We completely restructured and revised the command line interface for reek:

- We now support the yaml and html format besides the standard text format which makes `reek` great for compiling automated reports and statistics
- We overall revamped the UX when using reek. For instance we added color to `reeks` output, enabled different sorting options like "sort by issue count" and added a "show-wiki-links" switch that prints out helpful links next to each warning pointing to our github wiki that explains this particular smell and how to possibly fix ist. 
- Speaking of the wiki, you now should find an extensive description of each smell `reek` might detect including possible solutions

**rspec matchers**
 
We made the `reek_of` / `reek_only_of` rspec matchers a little smarter - you can still just do something like:

```Ruby
expect(src).not_to reek_of(:UncommunicativeParameterName)
```

but if you really want to be more specific about this you can now add a hash of "smell_details" `reek` will check for as well like this:

```Ruby
expect(src).not_to reek_of(:UncommunicativeParameterName, name: 'x1' )
```

You can check out the details [here](https://github.com/troessner/reek/wiki/RSpec-matchers)

**Outlook**

Personally I'd really like to see a couple of annoying bugs fixed, for instance:

- https://github.com/troessner/reek/issues/112
- https://github.com/troessner/reek/issues/27
- https://github.com/troessner/reek/issues/268

**Comment by troessner** [comment]
@mvz let's keep discussing here. I fixed the things you had mentioned in the gist: https://gist.github.com/troessner/c9050bebd94e2c61de06

Regarding your comment:

>> Perhaps mention support for JRuby and Rubinius explicitely?

Our build is failing right now for rubinius. I think if we say that we support JRuby and Rubinius then we should move them out of the "allowed failures" group. What do you think?

Other than that, feel free to update this issue as you see fit.

**Comment by troessner** [comment]
@mvz no more comments? Then I'll go ahead and publish it today.:)

**Comment by mvz** [comment]
I'll go over it once more. Hold on :-).

**Comment by mvz** [comment]
I think the final part of this sentence is too vague:

> Meaning that from reek's point of view there exists only one configuration file and one configuration, as compared to previous versions.

Perhaps something like this:

> This means that reek no longer tries to nest configuration files, but instead from reek's point of view there exists only one configuration file and one configuration.

**Comment by troessner** [comment]
And published it is: https://troessner.wordpress.com/2015/02/14/reek-2-just-got-released/
I already contacted the ruby NL guys..:)
