### ISSUE TITLE
Refactor CodeParser and friends

### ISSUE THREAD

**Issue by troessner** [troessner/reek#395]
I started to look into #112 and decided to completely refactor CodeParser and friends first in order to follow "Make the change easy (that might be hard) and then make the change".

I stumbled across a couple of open questions regarding CodeParser that I'd like to discuss first since I assume that this will be a huge refactoring:

1.) I think we should get rid of the Sniffer and dissolve this into the Examiner. If you look at the sniffer, at least 50% of the code are just for handling Examiner-related issues. I believe this is a wrong, superfluous abstraction that is confusing.
2.) Renaming CodeParser: I think "TreeWalker" would be a better name.
3.) I believe we should remove all that "tree adorning" like counting statements from CodeParser. I just don't see the point in it. Not to mention it creates a lot of complexity. I'd rather do all of those things in SmellDetector. This is where they belong IMHO.

What do you guys think?

**Comment by mvz** [comment]
Agreed on all three points. Since this is big I think we should split this up in 2 or 3 pull requests.

**Comment by troessner** [comment]
[2] is wip in #399

**Comment by troessner** [comment]
[1] is ready-for-review in #400

**Comment by mvz** [comment]
I think this leaves just item 3, right?

**Comment by troessner** [comment]
Yes @mvz !
I am away on holiday the next weeks, so if you want to look into it just go ahead. If you dont have time as well i'll continue in 3 weeks..;)

**Comment by troessner** [comment]
I'll start refactoring /core in a bit which will also include [3] anyways. Closing this.
