### ISSUE TITLE
Location formatting kerfuffle

### ISSUE THREAD

**Issue by tuexss** [troessner/reek#412]
I had a look at the parameters, and this weird setup of having two parameters -s and -n affecting the same variable, leads to some weird behavior:

```
iMac27:reek andreas$ reek -s -n lib/reek/cli/report/*.rb
lib/reek/cli/report/formatter.rb -- 4 warnings:
  [41]:Reek::Cli::Report::SimpleWarningFormatter#base_format doesn't depend on instance state (UtilityFunction)
...
```

but 

```
iMac27:reek andreas$ reek -n -s lib/reek/cli/report/*.rb
lib/reek/cli/report/formatter.rb -- 4 warnings:
  lib/reek/cli/report/formatter.rb:41: Reek::Cli::Report::SimpleWarningFormatter#base_format doesn't depend on instance state (UtilityFunction)
...
```

The order of the parameters is important, and it's really hard to grasp.

**Comment by troessner** [comment]
Good catch!
Thanks for reporting, we'll fix that.

**Comment by mvz** [comment]
I don't think the dependency on argument order is the problem. However, the fact that `-s` and `-n` are not orthogonal can be confusing.

I'm not sure how we can fix this without a breaking change. I'm thinking of something along the lines of `--location-format=`.

**Comment by mvz** [comment]
Looks like we missed our window of opportunity to fix this for reek 3.

**Comment by troessner** [comment]
Cleaning up our issues: Doesn't seem like we'll ever fix this and I'd consider it a minor bug since this was the only complaint about it. Closing this one.
