### ISSUE TITLE
".reek" file no longer detected as configuration by default

### ISSUE THREAD

**Issue by leonsp** [troessner/reek#425]
In previous versions, Reek would detect ".reek" as a configuration file.

In the current version, a longer filename (e.g. "config.reek") is required for Reek to detect the configuration file.

**Comment by troessner** [comment]
@chastell since you're on this already a quick pointer that might help you - this: https://github.com/troessner/reek/blob/master/lib/reek/configuration/configuration_file_finder.rb#L51
is where the configuration file is detected.

**Comment by chastell** [comment]
Yup, thanks! I actually had a fix for this a few weeks ago – as I’d rather have hidden `.reek` in my projects just like `.rubocop.yml` – but it was ugly and I deemed my private preference not worth it. Now that there’s a better reason for this I’m happy to fix this. :)

**Comment by troessner** [comment]
And I just released 2.0.4 with the fix from @chastell !.:)

**Comment by troessner** [comment]
>> troessner added this to the 2.0.4 milestone 2 minutes ago

Sorry, I missed that there was also #417 for this milestone - I'll create milestone 2.0.5 for #417
