### ISSUE TITLE
I've made a Reek plugin for Atom

### ISSUE THREAD

**Issue by dhagerty9009** [troessner/reek#431]
I just published it today, in fact. Any chance of it being added to the README? I figured I'd ask before sending in a pull request.

https://atom.io/packages/linter-reek

**Comment by chastell** [comment]
Thanks, this is most welcome! I took the liberty of adding it to the README as I saw an opportunity to make the Tools section a bit better along the way.

**Comment by dhagerty9009** [comment]
You're welcome! I'm glad it's been added. I'm just glad to help out the community.
