### ISSUE TITLE
Remove core_extras monkeypatches

### ISSUE THREAD

**Issue by troessner** [troessner/reek#433]
https://github.com/troessner/reek/blob/master/lib/reek/source/core_extras.rb

We're monkeypatching File, IO and String.
We're just extending them, so it' certainly not the worst monkeypatch I have ever seen, but we still shouldn't not monkepatch core classes, unless it's really necessary. Which it isn't in this case.
Furthermore, with us defining the reek API for reek 3 and thus promoting the API usage this is certainly an even bigger no-no to modify core classes.

I'll come up with a pull request that fixes this the next couple of days.

**Comment by chastell** [comment]
:+1: – if we wanted to leave this as an option for others, something like

```ruby
module ToReekSource
  def to_reek_source
    Reek::Source::SourceCode.from(self)
  end
end

module Reek
  module Source
    class SourceCode
      def self.from(source)
        case source
        when File   then SourceFile.new(source.path)
        when IO     then new(source.readlines.join, 'io')
        when String then new(source, 'string')
        end
      end
    end
  end
end
```

would allow them to keep the current behaviour just by doing `File.include(ToReekSource)`, etc.

**Comment by troessner** [comment]
```Ruby

module Reek
  module Source
    class SourceCode
      def self.from(source)
        case source
        when File   then SourceFile.new(source.path)
        when IO     then new(source.readlines.join, 'io')
        when String then new(source, 'string')
        end
      end
    end
  end
end
```
Yep, that was exactly what I had in mind.:)

>> if we wanted to leave this as an option for others

Let's throw it out, the less code the better - PR is on his way.
