### ISSUE TITLE
Test classes by full name

### ISSUE THREAD

**Issue by mvz** [troessner/reek#443]
Our specs call `include Reek`, etc., in several places, to avoid having to specify the full names of the classes. This seems silly and hides any problems there might be with the hierarchy (see #438). Also, it means we have to be careful that each spec file includes the modules it needs, or risk being unable to run it on its own. I propose removing all these calls to include, and just use the full name for each class or module.

**Comment by troessner** [comment]
Yes, couldn't :+1: this more.
In all of my latest refactorings I already replaced the 

```Ruby
include Reek
```

whenever I came across them. 
Let's remove them completely everywhere and fully qualify all our constants in our code base.

**Comment by chastell** [comment]
Very much yes, please! :)

**Comment by chastell** [comment]
I can do this later today, unless we have a soft policy of ‘the issue’s reporter gets dibs on fixing it’.

**Comment by troessner** [comment]
>> I can do this later today, unless we have a soft policy of ‘the issue’s reporter gets dibs on fixing it’.

We don't, unless the reporter explicitly says "i'll do this later", so as far as i am concerned just go ahead.:)
