### ISSUE TITLE
release management

### ISSUE THREAD

**Issue by troessner** [troessner/reek#446]
Right now we don't have a proper release management. Milestones are great but they don't help us with cases like this: https://github.com/troessner/reek/pull/418
Doing this right would have meant to release 2.0.5 for #444 and then 2.1.0 #418 
But so far our branch structure doesn't support this and I really don't want to manually cherry-pick things like that.

What do you guys think about introducing gitflow: http://nvie.com/posts/a-successful-git-branching-model/
I have been using this successful in different companies and we're using this at Blacklane right now as well.

**Comment by mvz** [comment]
Excellent idea. I really like that branching model.

**Comment by mvz** [comment]
Would you also like to use the [git-flow](https://github.com/nvie/gitflow) git extension?

**Comment by mvz** [comment]
I just investigated, and it looks like that version of git-flow was superceded by [the AVH edition](https://github.com/petervanderdoes/gitflow). It is conveniently packaged for Debian.

**Comment by chastell** [comment]
:+1: on gitflow as a workflow – and I wasn’t aware that there’s a Git extension, happy to give it a try!

**Comment by troessner** [comment]
>> I just investigated, and it looks like that version of git-flow was superceded by the AVH edition. It is conveniently packaged for Debian.

I wasn't aware of this, thanks for bringing it up, I'll give it a try!

I just created a "develop" branch and updated our contributing paragraph in #448.

Alright, so we all agree on this. I believe this will make our lifes a lot easier..:)
-> Closed.
