### ISSUE TITLE
Crash when scanning view helper from Rails project

### ISSUE THREAD

**Issue by oliverklee** [troessner/reek#463]
Using Reek 1.6.2, I get a crash when I scan the view helper at https://gist.github.com/oliverklee/0a7cecce8ca3ce067a6a :

klee@gonzales:~/src/ruby/justworkshops$ reek /tmp/icon_view_helper.rb 
/home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:298:in `children': undefined method `children' for nil:NilClass (NoMethodError)
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:99:in `effective_body'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:89:in `dispatch'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
        from /home/klee/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:498:in `run'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:149:in `block in emit_hash_body'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:184:in `parentheses'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:147:in `emit_hash_body'
        from /home/klee/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:136:in `dispatch'

Strangely, this only happens if the current working directory is a Rails project (even if there is no defaults.reek file).

**Comment by troessner** [comment]
Reek  1.6.2 is rather old - can you update to our current version?

**Comment by chastell** [comment]
This has been fixed in 3e5fd68aae845d28e596a737cc70b7aaffa1bc14 and upgrading to 1.6.3 should be enough (although you should upgrade to 2.1.0 if possible).

**Comment by oliverklee** [comment]
Oh, it looks like a bundle update had actually downgraded reek. So this was a false alarm. Sorry for that.
