### ISSUE TITLE
Integrate Ataru to make test codeblocks on documentation files

### ISSUE THREAD

**Issue by bibstha** [troessner/reek#472]
[Ataru](https://github.com/CodePadawans/ataru) provides command line interface and continuous integration hooks to test the codeblocks on documentations.

It is a useful feature to integrate it to reek.

**Comment by chastell** [comment]
That would be super useful, go ahead!

**Comment by troessner** [comment]
Great idea!

**Comment by troessner** [comment]
@bibstha  are you still on this? If not, I'd close this one.

**Comment by troessner** [comment]
I started to work on this -> assigning this to myself.
