### ISSUE TITLE
Last pending spec

### ISSUE THREAD

**Issue by bruno-** [troessner/reek#480]
I've talked to @chastell about the last pending spec from `spec/reek/smells/feature_envy_spec.rb` line 262 and how good it would be to get it working.

Unfortunately, it turns out making it work is beyond my abilities, so I'd just like to report the findings.

- from what I could tell, this test was first introduced in [this commit](https://github.com/troessner/reek/commit/1344c3662cc37028384a534cc43545352b1fd886#diff-7af6df8b186567d72140f27cb8f9ad5cR232)
- I've tracked that code through the upcoming commits and it turns out that code/feature was never passing tests. I think it was practically logged as a wanted feature.
- with a little bit of code inspection (and guessing), I concluded that the `#lines` was actually coming from [this line](https://github.com/troessner/reek/commit/aedf315d2f0fa95724a67554e2854cf804cbbf40#diff-3dc159b02e4482c773663260e2e12e5aR25) which in turn seems to be delegating to `parser` gem (at which point I gave up).

So, hopefully, this is helpful info!

**Comment by chastell** [comment]
Thanks, this is most helpful!

**Comment by troessner** [comment]
Closing this one, we can re-open it once one of us starts working on this.

**Comment by chastell** [comment]
I think I have a solution for this. :)
