### ISSUE TITLE
Assigning class variables smell

### ISSUE THREAD

**Issue by mpapis** [troessner/reek#483]
two use cases:

1. assign instance variable directly without a writer (`@something = something`) - I'm actually not sure about this one
2. assigning instance variable in methods - example:

    ```ruby
    attr_reader :something
    def methodA(something)
      @something = something
      methodB
    end
    def methodB
      puts something
    end
    ```
    it might be prefered to set up instance variables in `initialize` so any refactoring would not run the code into missing variables

#stopMichalPapis

**Comment by mvz** [comment]
Can you elaborate a bit more about why these would be smelly? I think point 2 would be caught by ruby's warnings if @something wasn't assigned yet. Point 1 I think conflicts with the Attribute smell, where we're trying to avoid writers (which I think is the better practice).

**Comment by mpapis** [comment]
ah so point 1. can be ignored

I did not get any warnings for point 2. if there is an extra work to get those warnings then maybe it's better to also detect it as not everybody would know about it and would rely on `reek` to provide the best practices not running ruby with extra flags

**Comment by troessner** [comment]
Just so I get this right:

@mpapis you're voting for:

- using and setting instance variables only in initializers 
- when updating them in other methods writer should be used instead of instance variables

right?

**Comment by andyw8** [comment]
I read a interesting post on this recently:
http://designisrefactoring.com/2015/03/29/organizing-data-self-encapsulation/

**Comment by troessner** [comment]
Just read it, interesting, thanks @andyw8 !

**Comment by troessner** [comment]
Well, from what I can see a there are 3 possibilities:

[1] DirectAccess smell
[2[ Mixed Access smell
[3] SettingInstanceVariablesDirectly smell 

Not sure if I would go for [1] and [2], that seems a little overzealous to me.
What do you think about [3]?

**Comment by mvz** [comment]
Yes, that was a very interesting article, @andyw8. I'm partial to Mixed access myself, and I think the problems he shows with adding a `last_name` setter for `Doctor` can be avoided by being consistent with `Person` and setting `@last_name` in the initializer.

Be that as it may, @troessner, what would SettingInstanceVariablesDirectly detect?

**Comment by mvz** [comment]
@mpapis, I think Ruby would emit a warning at runtime if you call `methodB` before `methodA`. However, I do agree that it's nicer to write the code so this temporal dependency doesn't exist.

So, we don't want, e.g.,

```ruby
def methodA(something)
  @something = something
  methodB
end

def methodB
  puts @something
end
```

But we may want to allow:

```ruby
def initialize
  @something = 'starting value'
end

def methodA(bar)
  @something = calculate_something bar
end
def methodB
  puts @something
end
```

And I would also want to allow:
```ruby
  def foo
    @foo ||= calculate_foo
  end
```

I think this detector would be similar to what ruby-lint does in its [undefined variables detector](https://github.com/YorickPeterse/ruby-lint/blob/master/lib/ruby-lint/analysis/undefined_variables.rb).

**Comment by troessner** [comment]
>> I'm partial to Mixed access myself

Me as well.

>> Be that as it may, @troessner, what would SettingInstanceVariablesDirectly detect?

I believe there are so many valid use cases for MixedAccess and DirectAccess that I wouldn't go in the direction of flagging this as smelly but rather find a the smallest common denominator.

And that would be to "not set instance variables directly".

So basically everything like this:

```Ruby
def omg
  @bar = :hola
end
```

would smell (including the initializer) whereas

```Ruby
def omg
  self.bar = :hola
end
```

would be golden.

**Comment by mvz** [comment]
> And that would be to "not set instance variables directly".

I don't understand. Wouldn't that mean **not* * allowing MixedAccess?

**Comment by troessner** [comment]
>> I don't understand. Wouldn't that mean *not * allowing MixedAccess?

Yes, you're right and I was rambling.:)

**Comment by chastell** [comment]
I like this discussion!

I’m not sure whether this will be useful information, but in my personal projects I went from ‘direct instance variable access everywhere’ through ‘accessors everywhere’ to ‘`self.foo = bar` is ugly, so direct setting of instance variables in the constructor, attr_readers everywhere else’. I don’t mutate my objects unless I have to (I much rather return updated copies instead), but when I do have to I think I use private attr_writers over direct setting the instance variables (so `@foo = bar` only in the constructor and `self.foo = bar` outside of it).

**Comment by troessner** [comment]
I don't think we'll reach a common sense here since it also seems highly subjective. 
I suggest to close this one.
Objections?

**Comment by mvz** [comment]
Clearly there are a lot of good possible styles here, but perhaps we can still find some actual smells?

I'm thinking the @mpapis's smell can be captured by:
* An instance variable must at least be set in the constructor, **or** be accessed through a method with lazy initialization.

And some more common sense smells:
* Don't access a superclass' instance variables directly in a subclass.
* Don't assume presence of ivars in a module.

**Comment by troessner** [comment]
This whole discussion has gotten a little vague.

```
I'm thinking @mpapis's smell can be captured by:

An instance variable must at least be set in the constructor, or be accessed through a method with lazy initialization.
And some more common sense smells:

Don't access a superclass' instance variables directly in a subclass.
Don't assume presence of ivars in a module.
```
I agree, but then let's rather create separate issues with concrete suggestions.

I'm closing this one.

**Comment by mvz** [comment]
I'll split this out into 3 discussion issues.

**Comment by mvz** [comment]
Well, that's 2 issues.
