### ISSUE TITLE
Detect misused caching

### ISSUE THREAD

**Issue by mpapis** [troessner/reek#484]
example:
```ruby
def do_something(variable)
  @cache ||= bla(variable)
end
```
this does caching of the result that depends on the input, if the input would change you would still get the old result

**Comment by andyw8** [comment]
I would say this is not a code smell – it's simply wrong code.

**Comment by mpapis** [comment]
isn't wrong code a smell?

**Comment by andyw8** [comment]
http://en.wikipedia.org/wiki/Code_smell
> Code smells are usually not bugs—they are not technically incorrect and do not currently prevent the program from functioning.

**Comment by andyw8** [comment]
Perhaps this could exist as a Lint check in RuboCop?

https://github.com/bbatsov/rubocop#lint

**Comment by mvz** [comment]
I think this might be considered a code smell, since I can certainly imagine cases where this would be a functionally valid implementation. For example, the following would set `@foo` unless it's already set:

```ruby
def provide_foo(a_foo)
  @foo ||= a_foo
end
```

**Comment by troessner** [comment]
@mvz you "don't" think that this is a code smell, right?
I believe this isn't a smell as well.

**Comment by troessner** [comment]
Closing this one since it's not really a code smell and there are valid use cases where this pattern makes sense.

**Comment by mvz** [comment]
I meant it wasn't wrong code, but could be a code smell (functionally valid, but wrong choice of implementation, if you're enclined to see it that way.). However, I don't really see anything wrong with it, it just doesn't match the memoization idiom.

**Comment by mpapis** [comment]
opened it  to help others - it hit me, if no one thinks it's a problem - I do not care, I should be able to find this problem in my code from now on - I was thinking it might help other developers doing the same mistakes. => not bugs just a mistake in what they expect from the system

**Comment by mvz** [comment]
@mpapis no problem, it's always good to open a ticket and discuss.

**Comment by troessner** [comment]
>> @mpapis no problem, it's always good to open a ticket and discuss.

Couldn't agree more.:)
