### ISSUE TITLE
IrresponsibleModule does not work on modules

### ISSUE THREAD

**Issue by mpapis** [troessner/reek#485]
```ruby
module Something
  def do_something
    true
  end
end
```
this does not give warnings about missing comments, there should be at least a comment on the method, but the module could be good too - especially if it was not hacking and the module had some extra purpose

**Comment by mvz** [comment]
I think IrresponsableModule only works on classes currently.

Perhaps we should remove this odd 'smell' altogether and let RuboCop handle this kind of issue?

**Comment by mvz** [comment]
@troessner, @chastell what's your opinion on this?

**Comment by chastell** [comment]
I’m probably a bad person to be asked about this (and bad person in general), as I have both reek’s IrresponsibleModule and RuboCop’s Style/Documentation turned off in my projects. ;)

I think this is a bigger question of whether
* reek should recognise RuboCop and actively try to complement it (and not double RuboCop’s checks), and – orthogonally – whether
* reek should flag this kind of problems as smells.

I think RuboCop and reek work great together, but I don’t mind them flagging the same problems. I’m not sure whether lack of comments is strictly a _code_ smell, though – as in, something that a static code analyser like reek should care about.

**Comment by chastell** [comment]
> I think IrresponsableModule only works on classes currently.

About this: I think this is because modules double as namespaces in Ruby, so if this was to also be a module check then it would have to make an educated guess whether it’s a namespace or not. Potential heuristics:
* top-level module is a namespace, the rest are not, or
* a module with methods is not a namespace.

(I’m still not sure this should be a reek smell in the first place, though.)

**Comment by troessner** [comment]
>> reek should recognise RuboCop and actively try to complement it (and not double RuboCop’s checks), and – orthogonally – whether

I think we shouldn't care about rubocop. It's a great gem, I love it and I use it extensively but we should do what we want to do without having it as a dependency. This doesn't mean that we shouldn't keep it's features in mind of course. And "this exists already in rubocop" can always be a good argument. But it shouldn't be a decisive one.

>> Perhaps we should remove this odd 'smell' altogether and let RuboCop handle this kind of issue?

Veto, like explained above.:)

>> I’m probably a bad person to be asked about this (and bad person in general), as I have both reek’s IrresponsibleModule and RuboCop’s Style/Documentation turned off in my projects. ;)

Heretic!

>> I think IrresponsableModule only works on classes currently.

I'd vote for making it work on modules as well.

**Comment by troessner** [comment]
I think we should make IrresponsibleModule work on modules as well.
@mvz @chastell what do you think?

**Comment by chastell** [comment]
I think it would make sense for modules with methods (so namespaces are not flagged as missing docs), but if that’s questionable then it would make sense to have it for all modules (rather than just classes).

**Comment by mvz** [comment]
@troessner I agree. And we should definitely skip namespaces.

**Comment by mvz** [comment]
Fixed in #576.

**Comment by mpapis** [comment]
thank you!
