### ISSUE TITLE
Cleanup Attributes Smell spec

### ISSUE THREAD

**Issue by beanieboi** [troessner/reek#495]
Hey,

while working on #481, we (@phillipp and i) came to the conclusion that  https://github.com/troessner/reek/blob/develop/spec/reek/smells/attribute_spec.rb is not a nice spec to work with.

i have some goals in my head for the new spec, besides a cleanup:
- remove the usage of shared examples and use custom matcher to preserve the correct stack trace for failed expectations.
- make it easier to add new specs without duplicating a lot of spec code

/cc #491

**Comment by chastell** [comment]
:+1: – more readable (even at a cost of slight duplication) specs will be most welcome.

**Comment by troessner** [comment]
Merged #501 so I'm closing this one.
