### ISSUE TITLE
rspec enhancements

### ISSUE THREAD

**Issue by beanieboi** [troessner/reek#497]
i would like to change 2 rspec configuration options.

### 1. disable monkeypatching
`config.disable_monkey_patching!`
disables the old should syntax by patching object. this enforces the new expect-syntax which does not rely on monkeypatching.

### 2. verify partial doubles
from the docs

> Prevents you from mocking or stubbing a method that does not exist on a real object. This is generally recommended, and will default to `true` in RSpec 4.

it's really nice that we don't have any violations of this in the current code. :dancer: 
i find such things hard to spot in code reviews, enabling this config options would fail the build if you mock/stub methods that don't exist. especially when you remove code during refactoring, this option fails the spec when the removed method is still mocked/stubbed.

```
config.mock_with :rspec do |mocks|
  mocks.verify_partial_doubles = true
end
```

to enable 2 we don't have to do anything, for option 1 we need to update some specs.

WDYT?

**Comment by troessner** [comment]
:+1: for both suggestions, sounds like 2 clear improvements.
Lets go for that.

**Comment by mvz** [comment]
:+1:

**Comment by chastell** [comment]
:+1: for both – being a [Bogus](https://github.com/psyho/bogus) contributor I welcome RSpec’s verified doubles very much. If stubbing/mocking turns out to mask some issues we can always go with Bogus’s contract tests. ;)

**Comment by beanieboi** [comment]
@chastell is it ok for you to close this issue and reopen if something is not working with the new rspec configuration?

**Comment by troessner** [comment]
>> @chastell is it ok for you to close this issue and reopen if something is not working with the new rspec configuration?

I'm not @chastell but I don't think he'll mind.:)
Closing this one.
