### ISSUE TITLE
Can't disable ToomanyStatements in .reek file

### ISSUE THREAD

**Issue by topher6345** [troessner/reek#504]
It seems the directive to disable `TooManyStatements` is being ignored by reek
my .reek file

```yaml
TooManyStatements:
  enabled: false
```

from the command line

```shell
reek app -c reekfile.reek | grep TooManyStatements | wc
15      90    1224
```

```shell
reek -v
reek 2.0.4 # dependency of rubycritic
```

**Comment by andyw8** [comment]
Are any other directives being ignored, or just this one?

**Comment by chastell** [comment]
I can’t reproduce this (at least not with reek 2.1.0). :( Can you come up with a minimal example?

**Comment by troessner** [comment]
Closing this. 
@topher6345 please re-open this if you have an example we can easily reproduce.
