### ISSUE TITLE
Enhance reek_of matcher to enable smell during testing

### ISSUE THREAD

**Issue by beanieboi** [troessner/reek#505]
extracted from #501
> I'm thinking we sould enhance the reek_of matcher to automatically enable the smell to be detected.

currently you need to enable the matcher by hand if you want to use the `reek_of` matcher. thats not a problem when the smell is enabled by default. if it's not it leads to unnecessary boiler code. see https://github.com/troessner/reek/blob/develop/spec/reek/smells/attribute_spec.rb#L17-L21

using `reek_of` should automatically enable the smell during the tests

**Comment by mvz** [comment]
See #503. Sorry for not linking it up to #501.

**Comment by mvz** [comment]
This has been implemented and released in Reek 4.0.2.

**Comment by beanieboi** [comment]
awesome, thanks!
