### ISSUE TITLE
Remove all wiki pages

### ISSUE THREAD

**Issue by troessner** [troessner/reek#508]
Now that we have all the documents moved to /docs in #494 we should remove all wiki pages to have everything in one place.

Also I'd like to quote myself from the referenced PR above:

>> A quick check on our wiki's git history tells me that almost no user ever bothered to edit our wiki.
I'd rather keep this information in our repo. If a user wants to update this, it's so easy to create a PR nowadays that I can hardly think of this as a problem.

Any objections? If not, I'd go ahead with the burning axe in my hands and chop that thing down.

**Comment by mvz** [comment]
No objections.

**Comment by troessner** [comment]
I'll remove them once we have released a new reek version meaning that master is up-to-date with /docs.
