### ISSUE TITLE
New release 2.2!

### ISSUE THREAD

**Issue by troessner** [troessner/reek#510]
I'd vote for the next release of reek with the following changes:

>>
9758818 - don’t track private methods in the Attributes smell (12 days ago) <beanieboi>
df04567 - Do not enable colorization if stdout is not a TTY (2 weeks ago) <Sebastian Boehm>
fb60d5f - Added Checkstyle format XML report support (3 weeks ago) <Saulius Grigaitis>

According to our versioning, adding the xml format warrant a minor version change, so we'd bump to 2.2.
I'd release this one after #509 is merged so that master is up-to-date and I can remove our wiki pages.

Any objections?

**Comment by mvz** [comment]
Sounds good to me.

**Comment by mvz** [comment]
I'd like to have #489 in there as well so our documentation is rendered nicely on rubydoc.info.

**Comment by mvz** [comment]
Which reminds me, @troessner, can you point the documentation link on rubygems.org to http://www.rubydoc.info/gems/reek please?

**Comment by troessner** [comment]
>> Which reminds me, @troessner, can you point the documentation link on rubygems.org to http://www.rubydoc.info/gems/reek please?

Done.

>> I'd like to have #489 in there as well so our documentation is rendered nicely on rubydoc.info.

Merged - release incoming..:)

**Comment by troessner** [comment]
AAAaaaaaaaaaaaaaaand 2.2 is out! Btw. I'm using the awesome hubflow toolbox : http://datasift.github.io/gitflow/GitFlowForGitHub.html in case somebody is interested.:)

**Comment by troessner** [comment]
Addendum: I removed all wiki pages, wiki is empty now.
Closing this one.

**Comment by mvz** [comment]
@troessner best deactivate the wiki as well.

**Comment by mvz** [comment]
Regarding HubFlow, I'm worried it does a little bit too much automatically. In particular, can we avoid having both tags `2.2.0` and `v2.2.0`? Perhaps I should read more about it, but I'm always worried if I can't easily map a git tool's actions to basic git operations in my head.

**Comment by troessner** [comment]
>> best deactivate the wiki as well.

Good idea, just did that.

>> Regarding HubFlow, I'm worried it does a little bit too much automatically. In particular, can we avoid having both tags 2.2.0 and v2.2.0? 

I'll keep that in mind and we can clarify that before the next release.
Let's get into the habit of having a github issue before every release so we can this discuss there before doing anything.

**Comment by mvz** [comment]
@troessner would you mind if I update the tags by
* removing `2.2.0`
* pointing `v2.2.0` to the original `2.2.0`.

**Comment by troessner** [comment]
No objections, go ahead..;)

**Comment by mvz** [comment]
Done.
