### ISSUE TITLE
Bugfix release 2.2.1

### ISSUE THREAD

**Issue by mvz** [troessner/reek#512]
I'm opening this ticket to make a list of what we should add to the next bugfix release. AIUI, according to the gitflow workflow we should create a release branch for 2.2.1 and merge any bug fixes branches into it.

Feel free to update the list below:

* #502

**Comment by mvz** [comment]
> AIUI, according to the gitflow workflow we should create a release branch for 2.2.1 and merge any bug fixes branches into it.

After pondering this some more, perhaps bugfixes releases should be handled using hotfix branches. What do you think?

**Comment by chastell** [comment]
> I'm opening this ticket to make a list of what we should add to the next bugfix release

Did we decide against using GitHub’s milestones for this? The advantage of GitHub milestones is that we can easily filter by them, see what else is missing from the next release, and adding/removing issues and PRs is simpler than editing a list in another issue (and making sure no-one is editing it at the same time).

**Comment by troessner** [comment]
@mvz I'd rather treat bugfixes not via hotfix branch. Unless we have a bug that completely breaks reek.

@chastell we can and should use both IMHO: issue for discussing what should be in the release and then using milestones to make it obvious to everybody...

**Comment by mvz** [comment]
@troessner I think `hotfix` is a terrible name that makes it sound worse than it is, but I also think part of the idea of gitflow is that bug fix releases are branched off of master.

Someone should really do a mapping between GitFlow and Semantic Versioning.

**Comment by troessner** [comment]
>> I think hotfix is a terrible name that makes it sound worse than it is, but I also think part of the idea of gitflow is that bug fix releases are branched off of master.

Yes, you're right.

**Comment by troessner** [comment]
2.2.1 has been released - closed.
