### ISSUE TITLE
Git Flow

### ISSUE THREAD

**Issue by andyw8** [troessner/reek#515]
I see there have been a few queries about the Git Flow process, and was wondering about the reasons behind switching to using this.

I can understand that such a workflow makes sense for large apps and multiple team, or where there is need to maintain multiple versions simultaneously.

But for a gem like reek, expecting users to be running the latest release does not seem like a huge burden. I also worry that such a workflow may act as a barrier to contributing to reek.

A couple of interesting posts on this subject:

http://scottchacon.com/2011/08/31/github-flow.html
http://whilefalse.blogspot.co.uk/2013/02/branching-is-easy-so.html

**Comment by mvz** [comment]
> I see there have been a few queries about the Git Flow process, and was wondering about the reasons behind switching to using this.

The basic reason for switching to Git Flow was to be able to work on features for the next major or minor release while still allowing patch releases.

I think this process is new for all of us, so we're still getting used to it.

> expecting users to be running the latest release does not seem like a huge burden

I would agree to this for human users. However, there are a couple of gems that themselves use Reek programmatically, and for those I think it makes sense to have the option to make patch releases.

I'll have a look at the posts you mentioned.

**Comment by troessner** [comment]
Yes, what @mvz said.:)

**Comment by mvz** [comment]
> I'll have a look at the posts you mentioned.

I've now read both posts. The short response is that both posts deal with web apps that are deployed by single entity, possibly several times a day. That is very different from releasing gems.

The long response:

The first post (http://scottchacon.com/2011/08/31/github-flow.html) I can totally agree with, in the context of basically continuous deployment. It is exactly how I like to work: Developers create relatively short-lived branches off of master, push their work often, and review is done in pull requests. I'll note that as soon as you need to co-ordinate your deploys with a third party (including a client), you will need something in place to stage what you're actually going to deploy. This may be separate `staging` and `production` branches that fast-forward to `master` or one of its ancestor commits regularly, or numbered release branches, or a git-flow-like setup.

The second post (http://whilefalse.blogspot.co.uk/2013/02/branching-is-easy-so.html) also is mainly concerned with the use of branches in regular development. I've heard this argument before, basically boiling down to the idea that feature branches and Continuous Integration don't match. AIUI, the argument goes that long-lived feature branches can lead to merge problems and the full test suite not being run on the code for a long time, therefore you should never create a feature branch. I think this is flawed reasoning, and the right solution is to make feature branches short-lived and open pull requests early so tools like Travis CI can test the new code both on its own branch and when merged into the main development line.

**Comment by troessner** [comment]
>>  I also worry that such a workflow may act as a barrier to contributing to reek.

We had quite some contributions since switching to git-flow and I didn't have the impression that this was something that would prevent somebody from contributing. Especially since we made the "develop" branch the default branch it's still very easy to contribute feature-wise.

I agree that hotfixes are a little bit more complicated but looking at our commit history also from before switching to git-flow you can see that the hotfixes didn't come as a casual contribution but were rather done by the main contributors.

-> Closing this one.
