### ISSUE TITLE
Stable interface for library usage?

### ISSUE THREAD

**Issue by bf4** [troessner/reek#516]
In https://github.com/metricfu/metric_fu/pull/258 we are attempting to use the Reek library directly, however, due to the interface change from [Reek::Examiner](https://github.com/troessner/reek/pull/451) to [Reek::Core::Examiner](https://github.com/troessner/reek/blob/aa6836840a2bb8682833d10e52abffaf12ec485c/docs/API.md) breaking that PR, I was wondering if we may agree on a contracted public interfaced for usage of reek as a library, (perhaps eventually even being able to pass in the AST generated by ruby_parser or parser).

```diff
-      MetricFu::Utility.capture_output do
-        Reek::Cli::Application.new(args).execute
+    def run!(files, config_files)
+      require 'reek'
+      begin
+        require 'reek/configuration/app_configuration'
+      rescue LoadError
+        # nothing we can do, it's probably an older reek version which doesn't need this file
       end
+
+      Reek::Examiner.new(files, config_files)
```

Unfortunately, I can't even easily switch on reek version since Reek::VERSION was changed to Reek::Version::STRING

**Comment by mvz** [comment]
Hi @bf4, we plan to have a stable public API in Reek 3.0.

I like the idea of being able to pass in an AST.

**Comment by bf4** [comment]
Yeah, I'd like to get that into all the metrics libraries, though not sure how to standardize the two main parser asts right now.   At least I got [rbp to stop breaking ruby_parser](https://github.com/metricfu/code_analyzer/commit/a43cddaeb7acb9c5b459369615d325927134a006)


- flog https://github.com/seattlerb/flog/blob/a158d6c2c40a688ca7a4d3cfb9d517ade1fdf5be/lib/flog.rb#L219-L224

**Comment by troessner** [comment]
@bf4 until reek 3 is coming I guess this: https://github.com/troessner/reek/blob/develop/docs/API.md is the kind of "informal" api specification with a high chance of not breaking for quite some time.:)

**Comment by bf4** [comment]
I ended up doing [the below](https://github.com/MGotink/metric_fu/pull/1) which seems stable enough


```ruby
      require "reek"
      # To load any changing dependencies such as "reek/configuration/app_configuration"
      #   Added in 1.6.0 https://github.com/troessner/reek/commit/7f4ed2be442ca926e08ccc41945e909e8f710947
      #   But not always loaded
      require "reek/cli/application"

      examiner = Reek.const_defined?(:Examiner) ? Reek.const_get(:Examiner) : Reek.const_get(:Core).const_get(:Examiner)
      examiner.new(files, config_files)
```

**Comment by troessner** [comment]
We're working on this already in #526 - closing this one.
