### ISSUE TITLE
Refactoring /core part 1

### ISSUE THREAD

**Issue by troessner** [troessner/reek#517]
I'd propose the following changes to /core:

* Rename StopContext to RootContext
* Move all *_contexts to core/contexts/
* Move SmellConfiguration and SmellRepository to lib/reek/smells

WDYT? Any objections?

**Comment by mvz** [comment]
Off the top of my head I would leave SmellConfiguration and SmellRepository where they are for now and just have the detectors in smells (and their supporting files).

SmellConfiguration in particular I would prefer not to move unless necessary due to API concerns.

**Comment by troessner** [comment]
>> Off the top of my head I would leave SmellConfiguration and SmellRepository where they are for now

Why?

>> SmellConfiguration in particular I would prefer not to move unless necessary due to API concerns.

What concerns?

**Comment by troessner** [comment]
Additionally, while looking into:

>> Move all *_contexts to core/contexts/

I believe it should be 

1.) "context" not "contexts"
2.) it should be on the top directory, right next to /core. /core is already kind of a grab-bag for quite some unrelated things already. Not to mention that "core" doesnt mean anything. We could also name it "stuff" and the name would just be as expressive.
So let's rather start working on removing most if not everything under /core into more appropriate directories.
