### ISSUE TITLE
Kill the core

### ISSUE THREAD

**Issue by troessner** [troessner/reek#522]
Like already mentioned in another issue:

>> 
 /core is already kind of a grab-bag for quite some unrelated things already. Not to mention that "core" doesnt mean anything. We could also name it "stuff" and the name would just be as expressive.

Let's kill /core completely. /core is the same like the notorious /utils folder in projects that always screams at the top of his lungs "I have not thought about where to put this".

Assuming that #519 gets merged soon this leaves us with:

```Shell
ast_node_class_map.rb
ast_node.rb 
code_comment.rb 
examiner.rb 
object_refs.rb 
reference_collector.rb 
tree_dresser.rb
tree_walker.rb
```

Now I'd put 

```Shell
ast_node_class_map.rb
ast_node.rb 
object_refs.rb 
reference_collector.rb 
```

inside a /ast folder and 

```Shell
examiner.rb 
code_comment.rb 
tree_dresser.rb
tree_walker.rb
```

I'd put at the top hierarchy.

What do you think?

**Comment by mvz** [comment]
Looks good. If possible, I'd merge the `ast/` and `sexp/` folders at the same time. There are only historical reasons for having both names, and I think this would be a good time to eliminate one of them (I vote in favor of keeping only AST).

**Comment by chastell** [comment]
:+1: to both of you. :)

**Comment by troessner** [comment]
>> Looks good. If possible, I'd merge the ast/ and sexp/ folders at the same time. There are only historical reasons for having both names, and I think this would be a good time to eliminate one of them (I vote in favor of keeping only AST).

Agreed - I'll put up a PR as soon as we fixed our current travis kerfuffle.
