### ISSUE TITLE
CodeClimate integration

### ISSUE THREAD

**Issue by andyw8** [troessner/reek#548]
CodeClimate recently opened up their platform, so it seems it would now be possible to run Reek on it.

http://blog.codeclimate.com/blog/2015/06/19/code-climate-platform/
https://github.com/codeclimate/spec

Has anyone else started looking into this?

**Comment by troessner** [comment]
>> Has anyone else started looking into this?

No - would you like to do that?..:)

**Comment by troessner** [comment]
I just talked to one of the guys via mail (hope he's ok with me making this public, nothing private about it):

```
Hey Timo-

Reek sounds like a great addition to our platform!

We don't have plans to build a Reek analysis engine right now, but any chance you (or your team) might be interested in doing so?

Our new analysis platform is open and extensible, so anyone can write their own Code Climate-compatible analysis engines. We can then run those engines for you (on any project). We designed our engine specification to be very straight-forward, and it often only takes 2-3 hours to stand up a brand new engine from scratch.

If you're interested, just let me know and I can send along some additional info.

Thanks again for the email!
```

I believe we should get this going. CodeClimate is awesome. reek is. 2 + 2 == hell, yes.

**Comment by troessner** [comment]
Alrightie, I'll definitely look into this!

Doesn't seem too complicated:

https://github.com/codeclimate/spec/blob/master/SPEC.md

**Comment by troessner** [comment]
Quoting from that spec:

```
Certain keys of the config object will be passed to all engines, and must be respected in order to conform with the specification. Today, there is only one such key:

exclude_paths -- An Array of file paths (relative to the /code directory) that should be ignored for the purposes of analysis. No Issues should be emitted for excluded files.
```

So let's implement this first. I'm gonna look into it.

**Comment by troessner** [comment]
Now that we have done all the homework I restart looking into this.

**Comment by andyw8** [comment]
I started working on a small Ruby library for building the data structures that the CodeClimate engine needs:

https://github.com/andyw8/codeclimate-engine-rb

**Comment by andyw8** [comment]
My early attempt at an engine: https://github.com/andyw8/codeclimate-reek

**Comment by troessner** [comment]
With #822 merged we can close this one.
Codeclimate is right now working on integrating `Reek`
