### ISSUE TITLE
Getting reek 3 out now

### ISSUE THREAD

**Issue by troessner** [troessner/reek#549]
I'd like to suggest that we release reek 3 for the following reasons:

- I'd like to get this https://github.com/troessner/reek/pull/539 out in the wild. Especially since this bug was something that led to quite some clutter in our commercial reek projects. I could do that via hotfix on master but a) that feels just wrong and b) gives me quite a few merge conflicts and spec failures
- The only breaking change we really have is this https://github.com/troessner/reek/pull/531
- This one isn't breaking: https://github.com/troessner/reek/pull/544 since we had no communicated API before this pull request
- And last but not least: I'd rather move fast here. Release 3.0 and then move on with minor versions. Right now I feel a little stifled quite frankly, since I'm blocked with quite some things i'd like to do but that get kind of tedious without having reek 3 out. Right now our gitflow versioning feels quite limiting to me. Maybe that was a mistake. We should have had a reek 3 branch in any case.

WDYT?

**Comment by mvz** [comment]
I'll see how far I can get on #544 this weekend. It's been a busy week.

**Comment by chastell** [comment]
FWIW, I’d really like to see #539 out as well. :)

**Comment by mvz** [comment]
Ready to go I believe :-).

**Comment by troessner** [comment]
reek 3 is released, closing this..:)

**Comment by troessner** [comment]
I took the liberty of summarizing our changes: https://troessner.wordpress.com/2015/07/04/reek-3-has-been-released/
I'd love it if you shared that with the world.:)

**Comment by chastell** [comment]
Nice! You might want to fix the `class &lt;&lt; self` in the _Singleton methods_ example. :)

**Comment by troessner** [comment]
Good catch, thanks, fixed.:)
