### ISSUE TITLE
rubocop multiline chaining

### ISSUE THREAD

**Issue by troessner** [troessner/reek#553]
See https://github.com/bbatsov/rubocop/issues/1591
I find the default rubocop strategy for this highly annoying and badly readable and would suggest that we go with something like:

```Ruby
a = [1, 3, 5].map { |i| i + 1 }
             .map { |i| i + 2 }
```

WDYT?

**Comment by mvz** [comment]
Are you referring to the indenting or to the dots?

**Comment by mvz** [comment]
Uh, sorry, from the issue it's obviously the indenting.

**Comment by mvz** [comment]
I tend to change that cop's setting to `EnforcedStyle: indented` so it alings like so, which matches what Vim does:

```ruby
a = [1, 3, 5].map { |i| i + 1 }.
  map { |i| i + 2 }
```

I would then probably move the first map to a separate line:

```ruby
a = [1, 3, 5].
  map { |i| i + 1 }.
  map { |i| i + 2 }
```

I'm not a fan of lining up at later points in the line since it involves a lot of hand-indenting.

**Comment by troessner** [comment]
Ok, then it's a tie.:)
pinging @chastell

**Comment by mvz** [comment]
Note that I don't particulary like our current settings, which do:

```ruby
a = [1, 3, 5].map { |i| i + 1 }.
    map { |i| i + 2 }
```

**Comment by chastell** [comment]
I really dislike the dots at the end – my brain recognises them much more when they’re at the beginning and it’s so much more obvious that `.map` is a continuation from the previous line (`map` just looks like mis-indented).

**Comment by mvz** [comment]
This issue is about the indenting @chastell, we can discuss the dots some other time :smile:.

**Comment by chastell** [comment]
Ah, good point, I got side-tracked by the example. :)

Unfortunately, I dislike both

```Ruby
a = [1, 3, 5].map { |i| i + 1 }.
    map { |i| i + 2 }
```

and

```Ruby
a = [1, 3, 5].map { |i| i + 1 }.
  map { |i| i + 2 }
```

I’d either indent as deep as necessary to sync the identifiers (sorry!), or – which I would actually do in 99% of the cases – I’d introduce a temp variable so that I don’t have to wrap any lines. The number of lines would stay the same, but the brain won’t have to remember that the weirdly indented ones are continuations.

**Comment by mvz** [comment]
Well, like I said, I would put the first `map` on its own line as well, which makes the identifier line-up moot.

Then, I prefer this:
```ruby
a = [1, 3, 5].
  map { |i| i + 1 }.
  map { |i| i + 2 }
```

Over this:
```ruby
a = [1, 3, 5].
    map { |i| i + 1 }.
    map { |i| i + 2 }
```

We can also disable this cop and allow this :smile: :
```ruby
a = [1, 3, 5].
          map { |i| i + 1 }.
          map { |i| i + 2 }
```

My vote would be to either use `EnforcedStyle: indented` or disable the cop entirely.

**Comment by chastell** [comment]
I’m ok with either as long as we agree on the general notion to introduce wraped lines only if temp variables can’t be used in an elegant way. :)

**Comment by troessner** [comment]
Ok, I'm lost. Did we agree on something now?
My preference would really be:

```Ruby
a = [1, 3, 5].map { |i| i + 1 }
             .map { |i| i + 2 }
```

We can also go withh @mvz suggestion:

```Ruby
a = [1, 3, 5].
  map { |i| i + 1 }.
  map { |i| i + 2 }
```

@chastell now it's up to you to say [1] or [2]. Or to suggest something completely different.:)

**Comment by chastell** [comment]
HEY I REALLY TRIED NOT TO PICK SIDES HERE

I find [1] more readable, but I understand [2]’s practicality (no need to hand-indent and it’s Vim default), although the lack of prefix dots throws me off a bit (I KNOW, I KNOW, IT’S A DIFFERENT DISCUSSION).

> Or to suggest something completely different.

I would like to push the notion that in most cases we shouldn’t have this problem to begin with and simply introduce extra variables (rather than wrap the lines). :P

**Comment by troessner** [comment]
>> I find [1] more readable

So you're voting for [1], right?.:)

**Comment by mvz** [comment]
@troessner I'm confused. Does [1] include the change in dots? Also, how would you format [1] if you moved the first map on its own line? Put another way, I like [1] a lot if I **had** to put the first map on the first line.

**Comment by troessner** [comment]
>> Does [1] include the change in dots?

The dots would be on the same line.

>> Also, how would you format [1] if you moved the first map on its own line?

No, I would have them on the same line. Haha.:)

Maybe we can compromise on this

```Ruby
a = [1, 3, 5]
  .map { |i| i + 1 }
  .map { |i| i + 2 }
```
?

**Comment by mvz** [comment]
> Maybe we can compromise on this

Hm, ok. That looks like a solution that RubuCop can enforce automatically. I'm not a fan of leading dots, but I can live with it.

**Comment by troessner** [comment]
>> 

Ok, then how about this:

```Ruby
a = [1, 3, 5].
  map { |i| i + 1 }.
  map { |i| i + 2 }
```
cause that would work for me very well.:)

**Comment by PeterCamilleri** [comment]
A most interesting discussion so far with many good points. My vote goes for:

```ruby
a = [1, 3, 5]
  .map { |i| i + 1 }
  .map { |i| i + 2 }
```

To me this is the most "symmetrical", but mostly the placement of the dots implies that the message is being sent to the value of the previous line.

**Comment by mvz** [comment]
> the placement of the dots implies that the message is being sent to the value of the previous line.

You could (and I do :smile:) argue the other way around: The dot at the end of the line implies that the line is not done yet. The indenting at the start of the line implies that it is a continuation of the previous line.

**Comment by mvz** [comment]
> Ok, then how about this:

> ```ruby
a = [1, 3, 5].
  map { |i| i + 1 }.
  map { |i| i + 2 }
```
> cause that would work for me very well.:)

Works for me :+1:.

**Comment by PeterCamilleri** [comment]
Two points:
A) For me the beginnings of lines are much easier to visually scan than the ends of lines. Thus I prefer the continuation character (the dot) at the beginning.
B) It really does not matter what system is used so long as it is applied in a consistent manner. Things get ugly when different styles are used in the same code base.
C) I don't suppose that as a matter of style, this could have some configurability? At a drop dead minimum, the ability to turn it off.

**Comment by mvz** [comment]
@PeterCamilleri we use RuboCop to enforce consistent dot placement. Reek itself does not check style issues. In our current RuboCop configuration, the trailing dot is enforced. RuboCop allows both styles.

Apart from that, I like to keep my lines short enough so I can scan both beginning and end. Otherwise, it is too easy to miss trailing dots, other continuation characters (operators etc.), and funny logic.

**Comment by PeterCamilleri** [comment]
My bad... Since this a discussion about reek, I was confused and thought this might be about something going into reek.

**Comment by troessner** [comment]
@mvz then let's configure rubocop accordingly. Whoever has time to look into this first .:)

**Comment by mvz** [comment]
Done. Only makes a difference in about 3 places. WDYT, better or worse?

**Comment by troessner** [comment]
Better! Closing this issue..;)
