### ISSUE TITLE
General idea list for reek

### ISSUE THREAD

**Issue by troessner** [troessner/reek#556]
- [ ] Fix all known bugs
- [ ] New smell detectors (All of those are still up for discussion):
  - Detect more [type checking](https://github.com/troessner/reek/issues/673)
  - Inappropriate intimacy: a class that has dependencies on implementation details of another class.
  - Refused bequest: a class that overrides a method of a base class in such a way that the contract of the base class is not honored by the derived class. See Liskov substitution principle.
  - Lazy class / Freeloader: a class that does too little.
  - LoD violations
  - Code Calisthenics 
  - [IVar assumptions](https://github.com/troessner/reek/issues/633)
  - [Uninitialized IVar](https://github.com/troessner/reek/issues/632)
  - [Magic number / string](https://github.com/troessner/reek/issues/609)
  - [ExcessiveConstantUsage](https://github.com/troessner/reek/issues/621)

**Comment by mvz** [comment]
Maybe we can open discussion issues on each of those smells? We already have a Rails Mode ticket, by the way.

**Comment by troessner** [comment]
>> Maybe we can open discussion issues on each of those smells?

Absolutely!
However I'd just would do that when we actually want to discuss them, not prematurely.

**Comment by jdickey** [comment]
What specifically did you have in mind by "Code Calisthenics"? I've seen very little use of that phrase, and most of what I have seen has been very PHP-focussed. Care to elaborate?

**Comment by troessner** [comment]
>> What specifically did you have in mind by "Code Calisthenics"? I've seen very little use of that phrase, and most of what I have seen has been very PHP-focussed. Care to elaborate?

Yes, that statement doesnt make much sense without going into details. I created a separate issue for this to not overload this thread, let's continue discussing this in #580

**Comment by mvz** [comment]
I still think we'll get super confused by linking closed issues.

**Comment by troessner** [comment]
Closing this one to keep our issues nice and tidy.
All interesting smell detectors have their separate tickets.
