### ISSUE TITLE
Reek 3.0 tries to parse everything (even non ruby files)

### ISSUE THREAD

**Issue by yld** [troessner/reek#557]
- files prefixed with a dot (.git)
- files suffixed with a .cache

Everything. This was not the case in previous versions.

**Comment by yld** [comment]
I can not disable .git dir parsing using the following YAML configuration:
```yaml
 ---
exclude_paths:
  - .git
```yaml

**Comment by troessner** [comment]
Whoopsie?
This sounds pretty bad.
I'll take a look at this tonight.

**Comment by troessner** [comment]
First report is fixed, see #559 - i'll immediately release 3.0.1 after this gets merged.
Pinging @mvz && @chastell for a speedy review here please.:)

**Comment by troessner** [comment]
Regarding the second bug report:

```
I can not disable .git dir parsing using the following YAML configuration:

 ---
exclude_paths:
  - .git
```yaml
```

Funny, this only happens when the hidden directory is on the top level of the scan.
"exclude_paths" works properly when the hidden directory is in a subdirectory (which is the case in our specs).
I'll fix that tomorrow probably.

**Comment by troessner** [comment]
Additional fix up in #560

**Comment by troessner** [comment]
And 3.0.2 is released. 
Last thing to fix from this bug report is #562 which I'll look into this weekend.

Closing this one.
Thanks a lot for reporting!
Using 3.0.2 should ease your pain hopefully .:)

**Comment by troessner** [comment]
@yld reek 3.0.3 has just been released, everything should work now for as "normal", please give it a try and let us know if all is good now.:)

**Comment by yld** [comment]
Works flawlessly now, thanks.
