### ISSUE TITLE
Dropping gitflow again

### ISSUE THREAD

**Issue by troessner** [troessner/reek#561]
After having had a couple of releases with gitflow I think we made a mistake by adopting it.
AFAIS the workflow only adds complexity but doesn't offer any benefit for us.
I believe gitflow is great for commercial projects with fixed release times and a dedicated QA, but not for an open source project like reek.
I'd vote for dropping it and returning back to master branch + features branches.
WDYT?

**Comment by mvz** [comment]
Agreed. It seems to be more trouble than it's worth and the tooling also doesn't seem to add much for us. If we want to support a previous release we can just create a release-x.y branch instead.

**Comment by troessner** [comment]
Then let's drop it. @chastell ?

**Comment by chastell** [comment]
:+1:!

**Comment by troessner** [comment]
Great! Then we just need to:

- Make master the default branch again
- point all existing pull requests to master
- drop the develop branch

I'll look into that.

**Comment by troessner** [comment]
>> Make master the default branch again

Done.

>> point all existing pull requests to master

I did that with my pull request, now it's your turn @mvz and @chastell ;)

**Comment by mvz** [comment]
All PRs have been retargeted. Only think left is CONTRIBUTING.md.

**Comment by troessner** [comment]
And "develop" is gone now.
I'll submit a PR regarding Contributing.md tomorrow.

**Comment by troessner** [comment]
I'll update Contributing.md with our discussion from here: https://github.com/troessner/reek/pull/571

**Comment by chastell** [comment]
What’s our procedure for merging `master` to `reek-4` (and resolving merge conflicts, if any)? A PR each time seems like an overkill. Whoever gets at it first? Whoever needs to make a `reek-4`-targetting PR syncs `master` before opening the PR? :)

**Comment by troessner** [comment]
>>  Whoever gets at it first? Whoever needs to make a reek-4-targetting PR syncs master before opening the PR? :)

Yep, both suggestions sound good to me..:)

**Comment by troessner** [comment]
contributing.md is updated, closing this one.
