### ISSUE TITLE
Write HTMLReport to STDOUT

### ISSUE THREAD

**Issue by troessner** [troessner/reek#570]
....I guess we all agree on that, right?.:)
Would be breaking, so labelled with breaking-change-for-reek-4.

**Comment by chastell** [comment]
Tentatively opened #571, will get it in sync with master when due.

**Comment by mvz** [comment]
I changed the title since the location of the template is not a breaking change.

**Comment by troessner** [comment]
I just merged #611 into the reek-4 branch -> closing this issue.
