### ISSUE TITLE
Code Calisthenics smell

### ISSUE THREAD

**Issue by troessner** [troessner/reek#580]
Coming from #556 
I was referring to : http://williamdurand.fr/2013/06/03/object-calisthenics/
The reason why I added this was because I did like a couple of points from there. 
I think most things on that list don't make sense for us (level of indentation) or are already implemented (LargeClass).

However I do like:

http://williamdurand.fr/2013/06/03/object-calisthenics/#2-don-t-use-the-else-keyword
and
http://williamdurand.fr/2013/06/03/object-calisthenics/#8-no-classes-with-more-than-two-instance-variables (even though i think it should more be around 3 or 4)

and I was thinking about maybe adding them as a "disabled by default" smell.

What do you guys think?

**Comment by chastell** [comment]
I like these two (as disabled smells), and they should be relatively easily doable. :)

**Comment by jdickey** [comment]
I'd take the [`sandi_meter`](https://github.com/makaroni4/sandi_meter) into account, deferring to it for things like that instance variable count.

Metz' "Four Rules for Developers", as summarised by [ThoughtBot](https://robots.thoughtbot.com/sandi-metz-rules-for-developers), specify that

1. Classes must be no longer than one hundred lines of code;
1. Methods must be no longer than five lines of code;
1. No method may take more than four parameters, counting items within a Hash;
1. No controller may instantiate more than one object. Therefore, views can only know about one instance variable, and must not introduce Law of Demeter violations sending messages via that object ("`object.collaborator.value` is not allowed").

I don't think Reek should reinvent this wheel, nor relax its constraints (although the Gem linked to earlier allows you to relax or tighten them to taste). 

As far as the rest of Durand's "Object Calisthenics" rules, I agree they're good ideas and would make useful additions to Reek. Lazy people are going to bitch and moan and rip Reek out of their toolchain&hellip;until debugging time hits them over the head with the usefulness of all this.

Thanks for bringing this up.

**Comment by troessner** [comment]
Closing this in favor of #627 and #628
