### ISSUE TITLE
Recognize singleton methods defined when module_function is a scoping modifier

### ISSUE THREAD

**Issue by troessner** [troessner/reek#582]
Follow-up issue to #567 

I'll look into this.

**Comment by mvz** [comment]
@troessner if you're busy with #529, I'd like to take a stab at this one.

**Comment by troessner** [comment]
>>@troessner if you're busy with #529, I'd like to take a stab at this one.

Absolutely, please go ahead!

**Comment by chastell** [comment]
@mvz: [Timo’s old commit](https://github.com/troessner/reek/commit/a302360cd4d0202441e802fab92411e89ef42258) (with my minor fixes) might be helpful here.

**Comment by mvz** [comment]
@chastell thanks!
