### ISSUE TITLE
wiki deleted?

### ISSUE THREAD

**Issue by tansaku** [troessner/reek#586]
wiki links like https://github.com/troessner/reek/wiki/Duplicate-Method-Call are redirecting to the main github repo - did the wiki get deleted?  if so that's a great shame :-( or is it just moved to a new home ...?

**Comment by troessner** [comment]
>> wiki links like https://github.com/troessner/reek/wiki/Duplicate-Method-Call are redirecting to the main github repo - did the wiki get deleted? 

Yes, we moved everything to /docs: https://github.com/troessner/reek/tree/master/docs
Nobody except for the reek team itself was actually using the wiki so we decided to make "proper" docs out of it. 
You're still invited to improve those of course, just issue a pull request.:)

**Comment by tansaku** [comment]
aha, awesome - one thing is that it breaks reek -U e.g. 

``` [12]:CoinManager#total refers to coin_array more than self (FeatureEnvy) [https://github.com/troessner/reek/wiki/Feature-Envy]```

which I think is a great feature of your gem

**Comment by mvz** [comment]
D'oh! I thought we adjusted those links.

**Comment by tansaku** [comment]
ah, maybe I'm not on the latest gem ... :-/ let me update

**Comment by tansaku** [comment]
hmm, just updated to reek 3.0.3 and still the old links

**Comment by troessner** [comment]
>> hmm, just updated to reek 3.0.3 and still the old links

Whoopsie!

We really did miss that. Fix up in #588

**Comment by troessner** [comment]
Quick review please at @mvz or @chastell - i'll release v3.0.4 right away then.

**Comment by troessner** [comment]
And 3.0.4 is released with the bugfix!
@tansaku thanks for the report, please let me know if this works for you now..:)

**Comment by tansaku** [comment]
that works - thanks for the awesome fast turn around!
