### ISSUE TITLE
CI apart from code climate

### ISSUE THREAD

**Issue by tansaku** [troessner/reek#587]
hey guys, I note that hound CI integrates rubocop into pull requests.  Is there anything similar for reek? I know about code climate but I'd love something that injects reek smell notifications directly as comments on pull requests ...

**Comment by mvz** [comment]
I think hound uses its own linter called hound?

To more directly answer your question, for injecting reek notifications have a look at [pronto-reek](https://github.com/mmozuras/pronto-reek).

**Comment by troessner** [comment]
Why do you think hound integrates reek? AFAIS it doesnt : https://github.com/thoughtbot/hound/blob/master/Gemfile

**Comment by tansaku** [comment]
@troessner I think hound uses rubocop as it's linter: https://github.com/thoughtbot/hound/blob/master/Gemfile#L31 - I've been able to configure hound CI via .rubocop files.  I'd love to do something similar for reek, but I know they don't include it in hound.

@mvz that's an interesting lead - thanks very much!

**Comment by troessner** [comment]
>>  I'd love to do something similar for reek, but I know they don't include it in hound.

That would be more than awesome / welcome!
Maybe you open up an issue at hound so we can discuss this there?

**Comment by tansaku** [comment]
@troessner chatting about it on hound here: https://github.com/thoughtbot/hound/issues/576

**Comment by mvz** [comment]
@tansaku That issue doesn't mention reek it seems?

**Comment by mvz** [comment]
I don't think there's anything we can do about this; Someone will need to create a pull request/feature request for hound. Now that we have a stable API, this should be easier to do.

**Comment by troessner** [comment]
>> I don't think there's anything we can do about this; Someone will need to create a pull request/feature request for hound. Now that we have a stable API, this should be easier to do.

Agreed. Closing this one.

**Comment by tansaku** [comment]
@mvz thanks so much for suggesting pronto-reek - am using that, but it's locked to 2.2.1 - I've opened an issue ... https://github.com/mmozuras/pronto-reek/issues/9 ... seems like there's a different way to call Reek::Core now which I've fixed, but there's a new error: 

https://github.com/mmozuras/pronto-reek/pull/10
