### ISSUE TITLE
Don’t use singleton configuration

### ISSUE THREAD

**Issue by chastell** [troessner/reek#594]
State-holding singletons are problematic, [configuration ones doubly so](https://github.com/troessner/reek/pull/591). Let’s turn `AppConfiguration` into a class and use it instead of the singleton, injecting where necessary (this won’t be trivial, but should be doable).

**Comment by troessner** [comment]
I am working on this already in the course of having directory specific smell configuration (precursor for the rails mode).

**Comment by troessner** [comment]
@chastell && @mvz just to make sure: Like I said, I'm actively working on this right now so please don't touch the AppConfiguration if possible cause otherwise we'll get huge merge conflicts and one of us will have to throw his work away.

**Comment by chastell** [comment]
If this is about #596 then feel free to not merge that until you’re done here – the changes to `AppConfiguration` there are trivial and I can port them afterwards.

**Comment by troessner** [comment]
>> If this is about #596 then feel free to not merge that until you’re done here – the changes to AppConfiguration there are trivial and I can port them afterwards.

Yes, please!

**Comment by troessner** [comment]
>> If this is about #596 then feel free to not merge that until you’re done here – the changes to AppConfiguration there are trivial and I can port them afterwards.

Scratch that, I just merged it to not block you and I'll just have to bite the bullet here.:)

**Comment by chastell** [comment]
Appreciated! :sparkles:
