### ISSUE TITLE
Making smells configurable on a directory base. Oh my

### ISSUE THREAD

**Issue by troessner** [troessner/reek#597]
So, I started to work on this as a necessary precursor for the rails friendly mode (#529).

In order to do this I need to change the AppConfiguration singleton to proper configuration objects (yay! @chastell mentioned this also in #594 )

The good thing about killing the configuration object singleton is that not only we make different modes and directory specific configuration possible, but also make it possible to configure our spec matchers separately - that is all in all incredibly powerful if you think about it.

So far it's going fine (even though our spec suite with its 500 indirections, instance variables and what not is biting me in the ass all the time) but there are  a couple of design questions I'd like to discuss regarding backwards compatibility and api design:

First of all the configuration file becomes more powerful:

```yaml
---
IrresponsibleModule:
  enabled: false
"app/helpers":
  UtilityFunction:
    enabled: false
exclude_paths:
  - "app/controllers"
```

However since we add the directory key this is not really backwards compatibiliy breaking.

But having single configuration objects is. E.g. the method signature of  [Examiner](https://github.com/troessner/reek/blob/master/lib/reek/examiner.rb#L27) changes to 

```Ruby
    def initialize(source, smell_types_to_filter_by = [], app_configuration = Configuration::AppConfiguration.new)
```

which makes calling it a little bit more error prone since now you have to do something like this if you want to pass in a custom configuration but smell_types_to_filter_by are not set:

```Ruby
Examiner.new src, [], my_custom_app_configuration
```

This makes our API a little ugly. However even when I switch smell_types_to_filter_by and app_configuration around there are still a lot of cases where you explicitly have to pass something that shouldn't be necessary.

So I'd like to use keyword arguments here to improve on this like so:

```Ruby
Examiner.new src, smell_types_to_filter_by: [], configuration: my_custom_app_configuration
```

Even though 2.0 keyword arguments are not really powerful (since they are not required) I still think this   is the right way (In my mind we could even drop supporting ruby 2.0 but that is a separate discussion).

I wouldnt touch the spec matcher the API though. It would still be:

```Ruby
ShouldReekOf.new :NestedIterators, smell_details = { ....}
```
since "exclude_paths" and "directories" don't make much sense with spec matchers if you think about. 

WDYT?

**Comment by troessner** [comment]
Update:

I'd propose this Examiner signature:

```Ruby
    def initialize(source, filter_by_smells: [], configuration: Configuration::AppConfiguration.new)
```

**Comment by mvz** [comment]
I like this signature, so I think we should move to it for reek 4, but in the mean time perhaps we can avoid a breaking API change like so (not sure what SemVer has to say about this):
```ruby
def initialize(source, filter_by_smells = [], configuration: Configuration::AppConfiguration.new)
```

**Comment by troessner** [comment]
>> def initialize(source, filter_by_smells = [], configuration: Configuration::AppConfiguration.new)

Good idea!

Another item for discussion: https://github.com/troessner/reek/blob/master/spec/reek/smells/nested_iterators_spec.rb#L139
[1] This means we need to adjust our spec matchers as well since before this PR it was possible to configure them implicitly using AppConfiguration.
[2] OR we just drop this feature.

I think we should go with [1] and then update our spec matcher signatures to:

```Ruby
    class ShouldReek
      def initialize(configuration = Configuration::AppConfiguration.new)
        @configuration = configuration
      end
    end

    class ShouldReekOf
      def initialize(smell_category, smell_details = {}, configuration = Configuration::AppConfiguration.new)
      end
    end
```

I would love to use this:

```Ruby
def initialize(smell_category, smell_details = {}, configuration: Configuration::AppConfiguration.new)
end
```

But hashes and kw arguments don't work very well together.

**Comment by troessner** [comment]
Addendum: 
I just checked, https://github.com/troessner/reek/blob/master/spec/reek/smells/nested_iterators_spec.rb#L139 is nowhere documented so it was never part of the API. 
Now that is where sloppy documentation finally pays of!
Anyways, let's go with:

```Ruby
      def initialize(smell_category, smell_details = {}, configuration = Configuration::AppConfiguration.new)
```
because actually I think this feature is pretty cool.

**Comment by mvz** [comment]
I prefer the `with_test_config` syntax. Adding the config as an extra parameter makes things less clear. I *think* RSpec gives you ways to add such things neatly as part of the DSL, so you can do stuff like:

```ruby
expect(foo).to reek_of(:NestedIterator).with_config(bar)
```

I haven't tried this, though.

For now, perhaps we can implement `with_test_config` like so:
```ruby
  def with_test_config(config)
    if config.is_a? String
      configuration = Reek::Configuration::AppConfiguration.new OpenStruct.new(config_file: config)
    elsif config.is_a? Hash
      configuration = Reek::Configuration::AppConfiguration.new
      configuration.instance_variable_set :@top_level_smells, config
    else
      raise "Unknown config given in `test_configuration_for`: #{config.inspect}"
    end
    allow(Reek::Configuration::AppConfiguration).to receive(:new).and_return configuration
    yield if block_given?
  end
```

**Comment by troessner** [comment]
>> For now, perhaps we can implement with_test_config like so:

But this wouldn't make much sense because then we would test for ourselves but none of our users could use this. Unless he'd use our with_test_config as well which would be a little absurd.:)

I'd rather go and try this approach you just suggested:

>> expect(foo).to reek_of(:NestedIterator).with_config(bar)

**Comment by mvz** [comment]
> I'd rather go and try this approach you just suggested:

OK. Would you like me to investigate?

**Comment by troessner** [comment]
>> OK. Would you like me to investigate?

That would be awesome and highly appreciated!

**Comment by mvz** [comment]
This is fixed now, right?

**Comment by troessner** [comment]
What do you mean? Right now it's like this:

```Ruby
    class ShouldReekOf
      def initialize(smell_category, smell_details = {}, configuration = Configuration::AppConfiguration.new)
      end
    end
```

So the "with_config" thingie is not there yet (if that is easily possible with rspec).
Quite frankly, I'd rather focus on other things since I believe our current solution is good. Not perfect, but good. 
But if you want to restart this then just go ahead..:)

**Comment by mvz** [comment]
I meant this entire ticket :-D.

**Comment by troessner** [comment]
Ah, yes! Closing.:)
