### ISSUE TITLE
Fix reek_of matcher messages

### ISSUE THREAD

**Issue by mvz** [troessner/reek#599]
The failure messages for `reek_of` are too general. For example, if the match fails due to the details being wrong, it just says it didn't smell.

**Comment by troessner** [comment]
>> For example, if the match fails due to the details being wrong, it just says it didn't smell.

Let's rather call that a bug.:)

**Comment by mvz** [comment]
> Let's rather call that a bug.:)

Title adjusted accordingly :-).

**Comment by troessner** [comment]
I took the liberty of taking this over. PR incoming.
