### ISSUE TITLE
An option to show column number?

### ISSUE THREAD

**Issue by ahmadseleem** [troessner/reek#601]
Is there an option to show column number ?

**Comment by mvz** [comment]
Not at the moment, but parser gives us enough information to potentially add that.

Do you experience issues locating the source of the detected smells without the column?

**Comment by ahmadseleem** [comment]
You did a great job, anyway! thanks, keep it up!
I have more feedback, maybe I should contribute a little here as I can/know.

**Comment by mvz** [comment]
Yes, please do report issues for anything you think can be improved or any questions you may have.

**Comment by troessner** [comment]
Like @mvz it's not supported and not planned right now - closing.
