### ISSUE TITLE
Failure on valid syntax: Parser::SyntaxError: unexpected token tCOLON

### ISSUE THREAD

**Issue by philoserf** [troessner/reek#602]
I've read through the open and closed issues for related issues. While there are some ruby parser issues related to symbol syntax, this case appears new. 

Using MRI 2.2.2.

Given a ruby code fragment like this:

```ruby
data = {
    "key0": 'value0',
    "key1": 'value1' }
```
**reek** bails with the error message:

```text
file.rb:xx:yy: error: unexpected token tCOLON
    "key0": 'value0',
          ^
file.rb: Parser::SyntaxError: unexpected token tCOLON
```
while `ruby` 2.2.2 testifies syntax is valid: 

```shell
ruby -cv file.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Syntax OK
```

`ruby_parse` also handles the code without issue.

**Comment by mvz** [comment]
Which version of reek are you using?

**Comment by philoserf** [comment]
It does look like the bundle locked on an old version. Closing.
