### ISSUE TITLE
SourceCode#description

### ISSUE THREAD

**Issue by troessner** [troessner/reek#604]
Regarding: https://github.com/troessner/reek/blob/master/lib/reek/source/source_code.rb#L16
We use "description" as filler for everything.
Might be a string, STDIN or Filename / Pathname.
I think the name is horribly misleading and we should change it.
Suggestion: source_via
Since this "description" terminology is used across the application, I think it makes sense to discuss this first.
WDYT?

**Comment by chastell** [comment]
How about `SourceCode#origin`?

**Comment by troessner** [comment]
Ah, yes, thats better!

**Comment by mvz** [comment]
> How about `SourceCode#origin`?

Yes, very nice!

**Comment by troessner** [comment]
Removing the "discussion" label since we probably all agree on that.

**Comment by troessner** [comment]
Fix up in #648
