### ISSUE TITLE
Option hell in /cli

### ISSUE THREAD

**Issue by troessner** [troessner/reek#605]
We should get rid of the option hell in /cli which always trips me up. There's the OptionInterpreter, the OptionParser and that options OpenStruct.
We should unify this and remove confusion.
WDYT?

**Comment by chastell** [comment]
Yes, definitely!

**Comment by troessner** [comment]
Removing the "discussion" label since we probably all agree on that.:)

**Comment by troessner** [comment]
Starting to work on this now ;)

**Comment by mvz** [comment]
:+1:
