### ISSUE TITLE
Add .with_config option to RSpec matchers

### ISSUE THREAD

**Issue by mvz** [troessner/reek#606]

**Comment by troessner** [comment]
@mvz is it realistic that we tackle this?
The last couple of months have shown that our current solution works pretty well.

I'd close this issue, if this is ok for you....

**Comment by mvz** [comment]
Maybe just tag it `maybe-someday`?

**Comment by troessner** [comment]
>> Maybe just tag it maybe-someday?

Good idea!

**Comment by troessner** [comment]
Let's face it: We'll probably never address this. Let's rather have a clean issue overview. Closing this one.

**Comment by mvz** [comment]
Hm, how am I going to keep track of ideas then?

**Comment by troessner** [comment]
Seems like we had a misunderstanding, re-opening, see my last comment on #633

**Comment by mvz** [comment]
This has been implemented :tada:.
