### ISSUE TITLE
Make AppConfiguration's initializer flexible enough to deal with different inputs

### ISSUE THREAD

**Issue by troessner** [troessner/reek#608]
Coming from here: https://github.com/troessner/reek/pull/593/files#diff-373a31cd38fa792eeb0826b025e8da97R69

**Comment by mvz** [comment]
Let's at lease/also get rid of the options parameter and just pass in the path or something.

**Comment by troessner** [comment]
Fix wip in #625

**Comment by troessner** [comment]
#625 is merged -> closing this one.
