### ISSUE TITLE
magic number / string smell

### ISSUE THREAD

**Issue by troessner** [troessner/reek#609]
The discussion originated in #593 : 
I believe we should get rid of all magic numbers and strings in our codebase.  Which means that most or maybe all would turn into constants or belong to constants.
Furthermore i suggest a corresponding SmellDetector.
WDYT?

**Comment by chastell** [comment]
I don’t know. ¯\_(ツ)_/¯

I usually cargo-cult this as a Good Practice™, but more and more often I realise that – in the cases when a given magic number/string is used exactly once – the practice gives zero benefits and comes with a jumping-around overhead (much like `let` declarations in specs that have only one `it` block). I wouldn’t mind the overhead as much if it weren’t kicking in so often when I need to debug something _fast_. :)

I’m definitely for a MagicConstant smell, though; I’m just not sure whether it should be enabled by default. ᕦ(òóˇ)ᕤ

**Comment by mvz** [comment]
I used to always make constants when I was using other programming languages, but for Ruby, less so. I wonder why.

I'm inclined to go with @chastell regarding single-use constants, especially since Ruby borrows the SmallTalk pattern of wrapping constants in methods:

```ruby
class Foo
  def self.default_name
    'The Foo'
  end
end
```

Perhaps we can implement a milder smell that would be more useful: RepeatedLiteral. This should ignore several basic constants by default, as well, like `0`, `1`, `[]` and `{}`.

I also prefer not to put symbols in constants and would like to get rid of reek's practice to do so.

**Comment by mvz** [comment]
The problem with RepeatedLiteral is of course that Reek examines source code by file. Maybe we should change that?

**Comment by chastell** [comment]
> Perhaps we can implement a milder smell that would be more useful: RepeatedLiteral. This should ignore several basic constants by default, as well, like `0`, `1`, `[]` and `{}`.

Oh interesting! It looks like a good idea in theory, I wonder how it would look like in practice.

> The problem with RepeatedLiteral is of course that Reek examines source code by file. Maybe we should change that?

Eventually we should (we currently don’t catch stuff like ‘this class includes seven modules, so has seventy-seven methods now’). For this a global literal counter would suffice if that’s simpler.

> I also prefer not to put symbols in constants and would like to get rid of reek's practice to do so.

Oh yes! :+1:

**Comment by troessner** [comment]
>> Eventually we should (we currently don’t catch stuff like ‘this class includes seven modules, so has seventy-seven methods now’).

And I have seen quite some code like that just to silence reek / rubocop.

>> Maybe we should change that?

Not sure about that quite frankly. I need to let that sink for a while.:)

>> Perhaps we can implement a milder smell that would be more useful: RepeatedLiteral. This should ignore several basic constants by default, as well, like 0, 1, [] and {}.

But then it gets complicated again. And I'm pretty sure there are quite a few cases where "1" is confusing as well.:)
"No magic numbers and strings" is easy to understand, straight-forward to implement and easy to reason out.

**Comment by mvz** [comment]
> "No magic numbers and strings" is easy to understand, straight-forward to implement and easy to reason out.

True, but if no-one will enable that smell, there's not much use implementing it :smile:.

**Comment by troessner** [comment]
>> True, but if no-one will enable that smell, there's not much use implementing it :smile:.

Also a good point.:D

>> Perhaps we can implement a milder smell that would be more useful: RepeatedLiteral. This should ignore several basic constants by default, as well, like 0, 1, [] and {}.

Let's go with that. @chastell ?

**Comment by chastell** [comment]
:+1: for RepeatedLiteral! :)

**Comment by troessner** [comment]
>> :+1: for RepeatedLiteral! :)

Veto!.:)

Why not "MagicNumber"? That is a term that a lot of people are familiar already. "RepeatedLiteral" does sound fancy but at the same time vague. "MagicNumber" doesn't need any explanation, "RepeatedLiteral" does.

**Comment by mvz** [comment]
To be clear, here is what I think we're going to implement:

**Bad: Literal is repeated**
```ruby
@blog.title = 'My Blog'
@other_blog.title = 'My Blog'
```

**Good, not using a constant**:
```ruby
def default_title
  'My Blog'
end

@blog.title = default_title
@other_blog.title = default_title
```

**Also good, using a constant**
```ruby
DEFAULT_TITLE = 'My Blog'

@blog.title = DEFAULT_TITLE
@other_blog.title = DEFAULT_TITLE
```

**Also good, literal only used once:**
```ruby
@blog.title = 'My Blog'
```

I think RepeatedLiteral captures this, but MagicNumber is a well known term. The only problem I have with the latter is that we're not just talking about numbers. Perhaps MagicLiteral?

**Comment by troessner** [comment]
Ah, then we were misunderstanding each other. 

For me is this:

>> Also good, literal only used once:
@blog.title = 'My Blog'

already bad. **Any** literal assigned as an attribute would be bad.

Good:

```Ruby
DEFAULT_BLOG_TITLE = 'My Blog'
@blog.title = 'My Blog'
```

**Comment by troessner** [comment]
Cleaning up our issues: Linked this issue in #556 - closing this one.
