### ISSUE TITLE
Instance variables vs getters / setters in reek

### ISSUE THREAD

**Issue by troessner** [troessner/reek#612]
I know we had already started a discussion about this but this was in an unrelated issue and I'd like to start clean.
So, what can we agree on?
I'd say we go with style suggested here: https://github.com/jswanner/private_attr
Meaning: No more instance variables at all.
That's a clear and easy rule to follow.:)

**Comment by chastell** [comment]
It’s a tad u̶g̶l̶y̶ baroque and I have a slight preference for just using `@foo = foo` in constructors (and explicit setters everywhere else if mutation can’t be avoided), but I’m ok with it. Can’t question the simplicity of ‘no `@` at all’. ;)

**Comment by mvz** [comment]
I'm afraid such a simple rule will kill my favourite pattern: memoization:

```ruby
def foo
  @foo ||= some calculation, for_foo
end
```

We use it about 33 times in reek. Creating differently named setters for each seems crazy to me. We'd get this:

```ruby
attr_accessor :foo_memoizer
def foo
  self.foo_memoizer ||= some calculation, for_foo
end
```

**Comment by chastell** [comment]
Ah, right, memoization – so I _do_ use ivar setting outside of the constructor, I just disassociated it so much from state I forgot about this case. :)

**Comment by troessner** [comment]
Ok, then how about "use instance vars in the constructor and for memoization and getters / setters for everything else"?

**Comment by mvz** [comment]
> use instance vars in the constructor and for memoization and getters / setters for everything else

:+1:

**Comment by chastell** [comment]
Oh very much so! I can do this (perfect task for my summer-fried in 30°C brain), but if not then please merge #610 first.

**Comment by troessner** [comment]
Would it make sense to add a "reek styleguide" mentioning this to our contributing guidelines?

**Comment by mvz** [comment]
@troessner good idea.

**Comment by troessner** [comment]
I'll come up with a PR the next days.

**Comment by chastell** [comment]
Oh, I think I have this done, just not pushed, sorry. Lemme check.

**Comment by chastell** [comment]
Sorry, no, still working on this on the `ivar_clean-up` branch – it’s more work than anticipated. I should wrap it up by the end of next week.

**Comment by troessner** [comment]
>> Sorry, no, still working on this on the ivar_clean-up branch – it’s more work than anticipated. I should wrap it up by the end of next week.

Then I'll just don't do anything and let you add that to our styleguide together with everything else in the ivar_clean-up branch, right?

**Comment by chastell** [comment]
Right!

**Comment by troessner** [comment]
>> Then I'll just don't do anything and let you add that to our styleguide together with everything else in the ivar_clean-up branch, right?

I took the liberty of taking this over in #701, hope you don't mind.

**Comment by chastell** [comment]
Not at all, thanks! I think this should be closed now, right?

**Comment by mvz** [comment]
Yes!
