### ISSUE TITLE
Getting rid of 1.6.

### ISSUE THREAD

**Issue by troessner** [troessner/reek#620]
We still have that branch: stable-1.6

Given that we are already on 3.1. I highly doubt that we will ever backport anything we do to that branch.:)

Let's remove it - objections?

**Comment by chastell** [comment]
:+1: – the actual releases are tagged, so will stick around anyway, and all the commits on `stable-1.6` that `git log master..stable-1.6` shows are actually on master already anyway.

**Comment by mvz** [comment]
:+1:

**Comment by troessner** [comment]
And gone he is.:)
