### ISSUE TITLE
Link to other analyzers / linters and projects that use reek

### ISSUE THREAD

**Issue by troessner** [troessner/reek#624]
Well, the title says it all.:)

I'd love to have this in our README. `reek` users are for sure interested in other static code analyzers as well. Let's give our brother and sister projects in mind some love and list them in our README including a one-sentence description (which I omitted below):

My suggestions:

Analyzers:

- debride: https://github.com/seattlerb/debride
- flay: https://github.com/seattlerb/flay
- flog: https://github.com/seattlerb/flog
- Sandimeter: https://github.com/makaroni4/sandi_meter

Projects:

- pronto / pronto-reek: https://github.com/mmozuras/pronto

WDYT?
Additional suggestions?

**Comment by mvz** [comment]
:+1:

Additional suggestion: https://github.com/YorickPeterse/ruby-lint

**Comment by chastell** [comment]
:+1: – additional suggestion: https://github.com/whitesmith/rubycritic

**Comment by troessner** [comment]
I'll come up with a PR the next days.

**Comment by mvz** [comment]
I just found another interesting one: https://github.com/DamirSvrtan/fasterer, based on https://github.com/JuanitoFatas/fast-ruby

**Comment by troessner** [comment]
>> I just found another interesting one: https://github.com/DamirSvrtan/fasterer, based on https://github.com/JuanitoFatas/fast-ruby

Just tried it out, pretty cool. Added it to the PR as well.

**Comment by troessner** [comment]
#635 is merged -> closing.
