### ISSUE TITLE
Smell suggestion: Limit nr of instance variables per class

### ISSUE THREAD

**Issue by troessner** [troessner/reek#628]
Coming from #580 

http://williamdurand.fr/2013/06/03/object-calisthenics/#8-no-classes-with-more-than-two-instance-variables 

I'd rather go with 4 since 2 seems overzealous.

WDYT?

**Comment by chastell** [comment]
You mean the TooManyInstanceVariables smell we already have? :)

(Note: it currently defaults to allow 9 instance variables. N̶E̶I̶N̶ NINE.)

**Comment by troessner** [comment]
>> You mean the TooManyInstanceVariables smell we already have? :)

Haha, yes!

I think the reason why I forgot this smell exists is because reek never reported it on my own codebase.
Probably because 9 instance variables is insane like you already noted.
I'd vote for setting that to 4 - what do you guys think?

**Comment by mvz** [comment]
> I'd vote for setting that to 4 - what do you guys think?

That seems a sensible amount.

**Comment by troessner** [comment]
Pull request coming up....

**Comment by troessner** [comment]
wip in #634

**Comment by troessner** [comment]
#634 is merged -> closing.
