### ISSUE TITLE
TooManyMethods's slightly insane default value

### ISSUE THREAD

**Issue by troessner** [troessner/reek#641]
After https://github.com/troessner/reek/pull/634 I got curios what other **insane** default values we might have in reek and I found this bomb: https://github.com/troessner/reek/blob/master/lib/reek/smells/too_many_methods.rb#L21

25. Well, no wonder that smell was never reported in any code I have ever seen.

I'd vote for 10 methods max. WDYT?

**Comment by chastell** [comment]
Hmmm, I’d have to check my codebases, but I think I could imagine having more than ten private methods. What’s reek’s max? :)

**Comment by troessner** [comment]
>> What’s reek’s max? :)

:laughing:

**Comment by chastell** [comment]
I’m somewhat on the fence here – I fully agree a class should have few public methods, probably few protected ones as well, but I’m not so sure about private methods. I sometimes have quite a few of them for readability and often refactor mercilessly (they're private after all). But I can also see how too many private methods heavily suggest there’s probably another object hiding behind them…

**Comment by troessner** [comment]
Ok, lets compromise on 15. Deal?

**Comment by mvz** [comment]
Deal :smile:.

**Comment by troessner** [comment]
Fix wip in #646
