### ISSUE TITLE
Breaking change for reek 4: Clean up Examiner constructor

### ISSUE THREAD

**Issue by troessner** [troessner/reek#650]
....because right now it has this signature:

```Ruby
    def initialize(source,
                   filter_by_smells = [],
                   configuration: Configuration::AppConfiguration.default)
```

Let's use keyword arguments everywhere.

**Comment by chastell** [comment]
:+1:

**Comment by mvz** [comment]
I'm have a branch with some cleanups that includes a change here. I'll push it soon so it can be reviewed.

**Comment by mvz** [comment]
I just realized that branch contains no changes to Examiner#initialize.

Anyway, :+1: from me.

Once #651 is merged, we can extract the smell detector selection out of this class and just pass in a SmellRepository.
