### ISSUE TITLE
errors on master due to ~/.reek file

### ISSUE THREAD

**Issue by tansaku** [troessner/reek#674]
So I imagine I've done something stupid, but `bundle exec rake` on master (commit hash: 034e209) gives me 800 examples, 23 failures, 2 pending.

I'm on OSX 10.10.5 
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

and I'm getting 23 errors, however I just tried removing my .reek file from my home directory and that fixed it.  That seems slightly unfortunate that ~/.reek should cause the tests to fail.  For reference here is my .reek file:

```
$ more ~/.reek 
IrresponsibleModule:
  enabled: false
Attribute:
  enabled: true
```

and the test failures it caused:

https://gist.github.com/tansaku/c71c0dc1e46c4a966454

**Comment by mvz** [comment]
Thanks, I can confirm that adding a `.reek` file with the contents shown above gives the same result for me.

**Comment by tansaku** [comment]
Right, so for the moment I guess we just move ~/.reek out of the way to keep our builds green ...

**Comment by mvz** [comment]
Yes :cry:

**Comment by chastell** [comment]
Can we skip the tests that blow up with an existing `.reek` [like we do for `ConfigurationFileFinder`](https://github.com/troessner/reek/blob/3c2d85ffe955fa46126118222f5ae77c6c8759a1/spec/reek/configuration/configuration_file_finder_spec.rb#L85-L88)?

**Comment by mvz** [comment]
@chastell unfortunately, that's basically all tests.

**Comment by mvz** [comment]
@chastell having thought about it some more, a good solution may be to create a temporary home dir and point `$HOME` there for the duration of the tests, similiar to how we handle the config tests in the cucumber scenario's. I'll try to come up with a PR for that.

**Comment by chastell** [comment]
I think that’s a good idea, just `ensure` it gets repointed after the tests run. I also think this is what Aruba does.
