### ISSUE TITLE
Remove  # @api private comments

### ISSUE THREAD

**Issue by troessner** [troessner/reek#675]
.....because they:

-  decrease readabiity 
- are counter-intuitive. Because "api private" is the regular case, not the exception. We should rather list exceptions and not the other way round
- is repetitive and feels un-rubyesque

Objections?

**Comment by chastell** [comment]
Yes, please!

**Comment by troessner** [comment]
#678 -> fix ready.

**Comment by mvz** [comment]
See also #578.

**Comment by mvz** [comment]
Done!
