### ISSUE TITLE
Make NestedIterators ignore Object#tap

### ISSUE THREAD

**Issue by troessner** [troessner/reek#676]
Object#tap should be an exception to the rule because it's no smell to do things like:

```Ruby
class Grmpff
  def gruml
    {}.tap do |hash|
      hash[:foo] = [:holla, :die, :waldfee]
      hash.each do |key, value|
        puts value
      end
    end
  end
end
````

What do you guys think?

**Comment by chastell** [comment]
:+1:

**Comment by troessner** [comment]
This will btw. also decrease our reek warnings on reek. I stumbled across that during my ongoing crusade in #677

**Comment by troessner** [comment]
I'll look into this soon.

**Comment by mvz** [comment]
Are there any other cases we should ignore by default now that we're looking into this?

**Comment by troessner** [comment]
>> Are there any other cases we should ignore by default now that we're looking into this?

Can't think of any right now :)

**Comment by chastell** [comment]
Yeah, I don’t think there are any others. I’d rather we be conservative, `#tap` is a very special case.

**Comment by troessner** [comment]
I just stumbled upon another valid one that I suspect will occur quite often in specs and ruby frameworks "before / after" hooks:

```Ruby
    def self.require_user_uuid_param
      before do
        validate_params { param :user_uuid, String, required: true, format: UUID_REGEX }
        do_stuff
      end
    end
```

I suggest that we exclude "before", "after" and "around" as well.
WDYT?
cc @RaVbaker

**Comment by chastell** [comment]
I’m ok with it. If so, let’s also add `let` and `let!`.

**Comment by chastell** [comment]
…and maybe `setup` + `teardown`, although I’m not quite sure whether any use them in the block form (rather than method names).

**Comment by troessner** [comment]
We hijacked the original issue, I'm gonna up a new one to keep it neat.
