### ISSUE TITLE
Improve NestedIterators sensitivity

### ISSUE THREAD

**Issue by troessner** [troessner/reek#685]
One example that will occur quite often in specs and ruby frameworks are "before / after" hooks:

```Ruby
    def self.require_user_uuid_param
      before do
        validate_params { param :user_uuid, String, required: true, format: UUID_REGEX }
        do_stuff
      end
    end
```
This example would be flagged with NestedIterators which doesn't make any sense.

In the issue where this [originated](https://github.com/troessner/reek/issues/676) we discussed ignoring further  common method names like "setup" and "teardown", which, after giving it some thought, seems like a dangerous road to go down due to its vagueness.

Why not exclude all method calls that do not pass an argument to the block, e.g. like the one above?
If it doesn't pass an argument, there's nothing to iterate over, so it should be ignored.
And yes, I'm aware that in theory every method in ruby that takes a block is called an iterator which is complete nonsense in my mind and I believe we shouldn't adhere to it.

We'd need to pay special attention to Symbol2Proc calls since there is no explicit argument but looking at the different S-expressions for all those cases I believe we can distinguish between them all.

What do you think?

cc @RaVbaker (I stumbled upon the example above in one of your PR's).

**Comment by chastell** [comment]
> Why not exclude all method calls that do not pass an argument to the block

Oh interesting! I think this could work – I can imagine code that would be an iterator which side-steps this limitation, but nothing that should ever happen in a real system.

In theory you can have iterators that don’t need the block argument (e.g., `collection.each { print '.' }` that prints some progress or `size = 0; collection.each { size += 1 }`, but that’s just a case of not knowing `collection.size`.
