### ISSUE TITLE
Alert on "helper" or "util" in class or module names

### ISSUE THREAD

**Issue by troessner** [troessner/reek#687]
.....because I'm sick and tired of seeing things like lib/helpers or lib/utils.

For me this means: "I have no idea where to put it so i'll just put it somewhere."

For me that's a bad smell.

WDYT?

**Comment by andyw8** [comment]
"Manager" too?

**Comment by troessner** [comment]
>> "Manager" too?

Good idea!

**Comment by HParker** [comment]
I hear it is considered a bad practice to have a pattern name as a class name. I know I am annoyed by a number of our models that go something like `PostDto` or `PostBuilder`.

**Comment by chastell** [comment]
I think helper + util are a bit different than manager, builder, etc. – the first two are ‘I don’t have a clue where else to put this stuff’ neutral groupings, while manager, builder (presenter? decorator?) are pattern names used in class names. I’d split these two general cases into separate smells.

**Comment by mvz** [comment]
I'm with @chastell regarding builder and manager. Those do communicate function.

I think we can group this problem under UncommunicativeModuleName, detect Util and Helper by default, and allow people to add more forbidden name parts if necessary.

**Comment by troessner** [comment]
On fifteenth thought I'm not so sure anymore that this makes sense. Seems like there are quite a lot valid exceptions. Closing this one.
