### ISSUE TITLE
Discrepancies between AppConfiguration.from_path and from_map

### ISSUE THREAD

**Issue by troessner** [troessner/reek#694]
When you have a config file like this:

````
---
UncommunicativeModuleName:
  accept:
    - Inline::C
````

You end up with this in your AppConfiguration (which gets loaded via AppConfiguration.from_path):

```Ruby
@default_directive={Reek::Smells::UncommunicativeModuleName=>{"accept"=>["Inline::C"]}}
````

This should be equivalent to when you use AppConfiguration.from_map like this:

```Ruby
      default_directive_for_smell = {
        :default_directive => {
          "UncommunicativeModuleName" => {
            "accept" => ['Inline::C']
          }
        }
      }
      Reek::Configuration::AppConfiguration.from_map(default_directive_for_smell)
```

Unfortunately it isn't, since you end up with 

```Ruby
@default_directive={"UncommunicativeModuleName"=>{"accept"=>["Inline::C"]}}
```

in the latter case.

Both methods should produce the exact same result.

**Comment by mvz** [comment]
I'd like to take a stab at this.

**Comment by troessner** [comment]
That would be most welcome ;)
