### ISSUE TITLE
Improve warnings for FeatureEnvy and UitilityFunction

### ISSUE THREAD

**Issue by troessner** [troessner/reek#702]
Right now:

UtilityFunction: "doesn't depend on instance state"
FeatureEnvy: "refers to #{name} more than self"

I suggest to change this to:

UtilityFunction: "doesn't depend on instance state (maybe move it to another class?)"
FeatureEnvy: "refers to #{name} more than self (maybe move it to another class?)"

I can hear you scream "but the current message are correct!".
Yes, they are. But this is not academic software and our experience has clearly shown that users are very confused by the current messages, e.g. in #681 

And yes, we could keep the existing messages around and add more information to our -U flag or something similar, but no novice is going to read that. 

Let's make it as easy as possible for users.

WDYT?

**Comment by mvz** [comment]
Sounds reasonable.

**Comment by tomash** [comment]
Or maybe something along the lines of "see reek documentation for suggestions"?

**Comment by troessner** [comment]
>> Or maybe something along the lines of "see reek documentation for suggestions"?

I don't think that's gonna cut it. Indirect feedback is nice for experienced users, but I think the confusion generated by our current messages needs to be address directly and not by referring to another source.
