### ISSUE TITLE
Refactoring sexp_extensions

### ISSUE THREAD

**Issue by troessner** [troessner/reek#722]
Our  sexp_extensions have become a huge (500 lines!), badly maintainable mess -> https://github.com/troessner/reek/blob/master/lib/reek/ast/sexp_extensions.rb

We should refactor this completely, identify common functionality and break it up into separate files.

I'd start to look into this after #546 

What are your thoughts on this?

**Comment by mvz** [comment]
The main problem is probably the fact that it is all in one file. Then, there are probably a couple of warts, such as the whole name/full_name/simple_name thing. Are there any other issues you're seeing?

**Comment by troessner** [comment]
>> The main problem is probably the fact that it is all in one file. Then, there are probably a couple of warts, such as the whole name/full_name/simple_name thing. Are there any other issues you're seeing?

Nope, that's exactly it.
But given the file size and the age of the file I'm 100% sure that I find loads of other things as well especially:

* dead code
* common code that is duplicated

I'll start with this and then let's see what else comes out of this ;)

**Comment by troessner** [comment]
Fixed with #746 - closing this one.
