### ISSUE TITLE
reek --todo

### ISSUE THREAD

**Issue by troessner** [troessner/reek#723]
Quoting from a discussion with @chastell so that we don't forget about this:

1. (Important) Introduce a `reek --todo` (or compatible) flag that
will output a todo.reek file which silences all current smells. This
would allow people to have a policy of ‘flag all new smells, let’s
go through the legacy ones one-by-one’. RuboCop’s --auto-gen-config
worked really well for me in a few projects.

2. (Not very) Verify that whitelisted smells are still there and
yell if they’re not. RuboCop does this and the benefit is that
(a) once you fix a smell you’re prompted to drop the whitelisting
and won’t reintroduce it unknowingly and (b) if you move / rename
a method you won’t have cruft entries forever in your reek config.

**Comment by mvz** [comment]
Yes, this would be very nice!

**Comment by backus** [comment]
Ended up here via google so I'll add a note for others: until this feature is implemented it is straightforward to generate a todo configuration using the yaml formatter.  Here is the script I used to do this (excuse the ugly code):

```ruby
require 'yaml'

REEK_OUTPUT = YAML.load(`bundle exec reek -c config/reek.yml -f yaml`)

class Smell
  def self.coerce(options)
    new(options.fetch('smell_type'), options.fetch('context'))
  end

  def initialize(type, context)
    @type    = type
    @context = context
  end

  attr_reader :type, :context
end

SMELLS = REEK_OUTPUT.map(&Smell.method(:coerce))

GROUPS = SMELLS.group_by(&:type).map do |type, smells|
  [type, { 'exclude' => smells.map(&:context) }]
end.to_h

puts GROUPS.to_yaml
```

**Comment by mvz** [comment]
Awesome @backus, it should be really easy for us to rework that into a `reek --todo` option.

**Comment by troessner** [comment]
Cleaning up our issues: This would be a super-awesome feature, leave this here. Hopefully we'll find the time to implement this soon.
