### ISSUE TITLE
Integrate mutant?

### ISSUE THREAD

**Issue by troessner** [troessner/reek#750]
I just played around with it like this:

```Bash
gem install mutant mutant-rspec
```

and then run it:

```Bash
 mutant --include lib --require reek --use rspec Reek::Examiner
```

Result (truncated):

```
-----------------------
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Reek::Examiner]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            8
Includes:        ["lib"]
Requires:        ["reek"]
Subjects:        6
Mutations:       184
Kills:           169
Alive:           15
Runtime:         5.91s
Killtime:        12.47s
Overhead:        -52.58%
Coverage:        91.85%
Expected:        100.00%
```

Not entirely sure what to make of the result, I really need to start reading the docs for this.
I'll document my  progress here ;)

**Comment by chastell** [comment]
Oooh, > 90% mutation coverage of the `Examiner`, good. I think we should initially choose the most crucial partrs of Reek and see whether we can bump their mutation coverage with moderate effort, then see how that went. :)

**Comment by troessner** [comment]
>> I think we should initially choose the most crucial partrs of Reek

How about our public API?

**Comment by chastell** [comment]
Good idea!

**Comment by backus** [comment]
If you just want to use mutant *from now on* you can run it with the `--since` flag which lets you only mutate code introduced since the revision you specify.  For example:

```sh
$ mutant --include lib --require reek --use rspec --since HEAD~1 Reek::Examiner
```

will just mutate code touched by the diff `HEAD~1..HEAD`.

**Comment by backus** [comment]
Also @troessner if you have questions you can join the [mutant slack](https://mutation-testing.slack.com/)

**Comment by mbj** [comment]
For integrating mutant into a project that was not using a mutation coverage tool from day one I recommend choosing to run it on CI against the master branch via specifying `--since master`. If you use hygenic commits, you can go for `--since HEAD~1` as @backus explained.

Depending on the size of the project it might also make sense to proactively ignore "currently uneasy to mutation cover subsets via the `--ignore-subject Expression#here` flag.

A word of warning (or advertisement, depending on perception): Adding mutation coverage to the workflow of a project causes backpressure. The tool as I wrote it intentionally is expecting a certain (not very well documented) workflow. Once working with mutant feels painfull I highly recommend to ping me about your experience so I can put it into a context, and help you around corners.

I totally agree the workflow should be documented, and I take the blame for not doing so.

Thankfully the community of active mutant users is growing so answering the questions, and the net energy available for creating better documentation is increasing.

We are using the slack channel because I use slack at work, so the impedance mismatch is small. I'll invite anyone interested. Just send me your email addresses via mail / twitter / whatever.

**Comment by troessner** [comment]
>> If you just want to use mutant from now on you can run it with the --since flag which lets you only mutate code introduced since the revision you specify. For example:

Wow, that's an highly awesome feature.

>> For integrating mutant into a project that was not using a mutation coverage tool from day one I recommend choosing to run it on CI against the master branch via specifying --since master. If you use hygenic commits, you can go for --since HEAD~1 as @backus explained.
Depending on the size of the project it might also make sense to proactively ignore "currently uneasy to mutation cover" subsets via the --ignore-subject Expression#here flag.

Thanks for the advice!

>> Once working with mutant feels painfull I highly recommend to ping me about your experience so I can put it into a context, and help you around corners.

Actually I'm working on a talk about how `Reek`, `Mutant` and `rubocop` use Ruby's AST and how they differ. Your input about the `Mutant` part would be highly appreciated, but I'll just nudge you via mail (or rather github issue?) as soon as I have something ready for review ;)

**Comment by mbj** [comment]
> Your input about the Mutant part would be highly appreciated, but I'll just nudge you via mail (or rather github issue?) as soon as I have something ready for review ;)

At your preference. We also have a mutant slack channel. Send me your email address and you get a invite.

**Comment by troessner** [comment]
>> At your preference. We also have a mutant slack channel. Send me your email address and you get a invite.

That would be: timo.roessner [at] googlemail.com

Thanks, appreciate it!

**Comment by troessner** [comment]
I'll restart looking into this.

**Comment by mbj** [comment]
> I'll restart looking into this.

Feel free to ping me in the mutant channel if you need a hand on this.

**Comment by troessner** [comment]
@mbj I'm a little confused about the semantics regarding the exit status.

```Bash
mutant --include lib --require reek --use rspec Reek::Examiner

.....
Coverage:        90.36%
Expected:        100.00%
```

And

```Bash
 echo $?
1
```

Ok, fair enough, `mutant` tells me 100% was expected which I didn't fulfil so we have a non-exit status.
But why doesn't this work:

```Bash
 mutant --include lib --require reek --use rspec Reek::Examiner --expected-coverage 0.9036

.....
Coverage:        90.36%
Expected:        90.36%
```

```Bash
  ( $ (master)) echo $?
1
```

I would have expected an exit status of 0.
Am I missing something obvious here or is this a bug?

**Comment by troessner** [comment]
Ah, @mbj I guess this behaviour is due to [rounding precision problems](http://blog.arkency.com/2015/05/mutation-testing-and-continuous-integration/)?

In this case, we'd need to increase our API mutation coverage to 100% to fix this, right?

**Comment by mbj** [comment]
@troessner The rounding precision problem was fixed already, use a rational input `--expected-coverage $killed/$amount_mutations`. But I actually think you should add excludes so you have 100% and work to reduce the excludes. This will get you a far better workflow.

**Comment by troessner** [comment]
>> $killed/$amount_mutations

Ok, `mutant` tells me:

>>
Mutations:       197
Results:         197
Kills:           178

So I fire up pry:

```
[3] pry(main)> Rational(178, 197).to_f
=> 0.9035532994923858
```

And then use this like this:

>>
mutant --include lib --require reek --use rspec Reek::Examiner --expected-coverage 0.9035532994923858

Now I get:

>> Mutations/s:     10.76
Coverage:        90.36%
Expected:        90.36%

But the exit status is still 1:

>>
echo $?
1

Not sure what to do now. I'd agree that we should have 100% coverage for our public api, but i'd still like to understand what I'm doing wrong here @mbj :(

**Comment by mbj** [comment]
@troessner Use `--expected-coverage 179/197` ;)

**Comment by mbj** [comment]
The whole idea is NOT to use the floats, mutant works with the rationals internally and was changed to allow the lossless rationals at the CLI.

**Comment by mvz** [comment]
From @mbj's comment I conclude that you need to actually put `--expected-coverage 178/197`.

**Comment by mvz** [comment]
You beat me to it, @mbj  :-).

**Comment by troessner** [comment]
Ah, ok, works now, thanks @mbj and @mvz !

@mvz @chastell what should we include in our tests?

I guess everything that comes up via:

>> grep -r '@public' lib/

wdyt?

**Comment by mbj** [comment]
> @mvz @chastell what should we include in our tests?

I'd simply go with the match expression `Reek*` in the mutant CLI. And work from there.

**Comment by chastell** [comment]
I’d go with @mbj’s suggestion – I think our private methods should be test-covered (implicitly, via public method calls) as well, otherwise we can just refactor the codebase to be 100% and gain zero benefits. ;)

**Comment by mvz** [comment]
I agree with @chastell and @mbj. A lot of our code is not public API, but is part of what's needed to make the `reek` command itself work.

**Comment by mbj** [comment]
> A lot of our code is not public API, but is part of what's needed to make the reek command itself work.

Yes. The idea is that all private API needs to be covered via tests from the public API. If you wanted I'd offer a small pairing session with the reek team explaining / discovering life on how to use mutant against your project.

**Comment by mvz** [comment]
This has been implemented.

**Comment by mbj** [comment]
> This has been implemented.

Ping me on feedback, and all pain that makes your question the decision to integrate it.

For feedback I'm happy to listen, and for pain I'm happy to explain context that will likely improve your efficiency.
