### ISSUE TITLE
Make Ataru run examples in-order

### ISSUE THREAD

**Issue by mvz** [troessner/reek#755]
Because Ataru uses minitest, it runs the examples in a random order. This is most probably the reason it sometimes fails.

There are several open Ataru issues related to this:
- https://github.com/CodePadawans/ataru/issues/75
- https://github.com/CodePadawans/ataru/issues/80
- https://github.com/CodePadawans/ataru/issues/68

**Comment by troessner** [comment]
Ataru seems dead, I don't think this will ever get solved.

**Comment by mvz** [comment]
Hm .. I still like the concept. Maybe I should fork it :smile:.

**Comment by troessner** [comment]
Or ask to take over the ownership?

**Comment by troessner** [comment]
Cleaning up our issues: doesn't seem like we'll ever take care of this + it kind of stopped being a problem AFAIS (or never really was?).

**Comment by troessner** [comment]
Seems like we had a misunderstanding, re-opening, see my last comment on #633

**Comment by mvz** [comment]
I don't think we've had any Ataru problems recently.
