### ISSUE TITLE
Object oriented clusterfuck pattern in Reek

### ISSUE THREAD

**Issue by troessner** [troessner/reek#775]
We have done a **lot** of refactorings in Reek over the last couple of months and years.

One antipattern though is still used heavily in our code base. I call it "Object oriented clusterfuck pattern" in lack of a better name and it refers to doing **everything** by setting state implicitly in X to be used in Y.

Sounds vage? Ok, let me give you an example by looking at our [Examiner](https://github.com/troessner/reek/blob/master/lib/reek/examiner.rb#L83):

- We create a SmellRepository
- Get a syntax tree
- pass both to the initializer of the TreeWalker and then call "walk" on it. But that doesnt return anything. That's the first WTF.
- That  SmellRepository is then heavily worked on the TreeWalker. That's the second big WTF.
- This SmellRepository then reports to an collector

A creates B and passes B to C. C then works on B so that later A can make B do D.
That's pretty bad spaghetti code. 

Unfortunately there are more instances where we do this. Let's kill this deamon with fire everywhere.
When A creates B then B should create C and pass the results back explicitly.

Or in other words: Method should return values and not operate on foreign entities and with a gazillion of sideeffects.

What do you guys think?

**Comment by chastell** [comment]
Very much yes! It also really hinders inferring how Reek actually works (in detail).

**Comment by mvz** [comment]
:+1:, and :+1: for the name 'Object Oriented Clusterfuck Pattern'.

**Comment by troessner** [comment]
Cleaning up our issues: Was just for discussion and since we all agree we can close this one.
