### ISSUE TITLE
undefined method `simple_name' for (send (const nil :Class) :new)

### ISSUE THREAD

**Issue by backus** [troessner/reek#786]
Similar to #719 and #715 

The following produces an error when reek attempts to parse it:

```ruby
Foo = Class.new.new
```

I checked this bug against the latest revision of master (28e8b2f).

**Comment by troessner** [comment]
Confirmed:

>> 
echo "Foo = Class.new.new" | bin/reek

gives me

>>
/Users/timo/dev/reek/lib/reek/ast/sexp_extensions/send.rb:34:in `module_creation_receiver?': undefined method `simple_name' for (send (NoMethodError)
  (const nil :Class) :new):#<Class:0x007fb57d3132a8>
	from /Users/timo/dev/reek/lib/reek/ast/sexp_extensions/send.rb:30:in `module_creation_call?'
	from /Users/timo/dev/reek/lib/reek/ast/sexp_extensions/module.rb:62:in `defines_module?'
	from /Users/timo/dev/reek/lib/reek/context_builder.rb:88:in `process_casgn'
	from /Users/timo/dev/reek/lib/reek/context_builder.rb:56:in `build'
	from /Users/timo/dev/reek/lib/reek/context_builder.rb:26:in `initialize'
	from /Users/timo/dev/reek/lib/reek/examiner.rb:84:in `new'
	from /Users/timo/dev/reek/lib/reek/examiner.rb:84:in `run'
	from /Users/timo/dev/reek/lib/reek/examiner.rb:43:in `initialize'
	from /Users/timo/dev/reek/lib/reek/cli/reek_command.rb:13:in `new'
	from /Users/timo/dev/reek/lib/reek/cli/reek_command.rb:13:in `block in execute'
	from /Users/timo/dev/reek/lib/reek/cli/reek_command.rb:12:in `each'
	from /Users/timo/dev/reek/lib/reek/cli/reek_command.rb:12:in `execute'
	from /Users/timo/dev/reek/lib/reek/cli/application.rb:31:in `execute'
	from bin/reek:12:in `<main>'

Thanks for the report @backus !
