### ISSUE TITLE
Allow configuring Rake task with a FileList

### ISSUE THREAD

**Issue by avdgaag** [troessner/reek#788]
The Rake task currently allows you to specify a single glob pattern:

```ruby
Reek::Rake::Task.new do |task|
  task.source_files = 'lib/**/*rb'
end
```

Internally, this is fed to Rake’s `FileList` and converted to an array of actual filenames to pass to the `reek` executable.

What I would like is to define _multiple_ glob patterns, and exclude some specific files. This basically can’t be done with a glob pattern, but would be very easy if I could pass in my own `FileList`. This would be nice:

```ruby
Reek::Rake::Task.new do |task|
  task.source_files = FileList['lib/**/*rb'].exclude('lib/templates/**/*.rb')
end
```

Note that this is different from excluding files in the Reek configuration: that will silence errors, but will not stop Reek from unsuccessfully trying to parse .rb files that are not valid Ruby code (such as .rb files that contain ERB instructions, as with Rails generator templates).

My suggestion would be to allow setting both file lists and strings in the Rake task. Use the single string glob pattern if you want to, but you _can_ supply your own, hand-crafted filelist if you want to.

**Comment by troessner** [comment]
Sounds like a good idea to me!
Care for a pull request?
I'd help you if you're up for it ;)

**Comment by mvz** [comment]
> Note that this is different from excluding files in the Reek configuration: that will silence errors, but will not stop Reek from unsuccessfully trying to parse .rb files that are not valid Ruby code.

We should fix that as well probably.

**Comment by avdgaag** [comment]
Sorry, forgot about this over the holidays. I’ll make a pull request for this particular change, stay tuned.

> We should fix that as well probably

That, however, is out of my league :smile:

**Comment by troessner** [comment]
>> Note that this is different from excluding files in the Reek configuration: that will silence errors, but will not stop Reek from unsuccessfully trying to parse .rb files that are not valid Ruby code (such as .rb files that contain ERB instructions, as with Rails generator templates).

This is not correct, please see #814 for the corresponding discussion.

**Comment by troessner** [comment]
#823 is merged, closing this one.
