### ISSUE TITLE
Use the contracts gem?

### ISSUE THREAD

**Issue by troessner** [troessner/reek#789]
I'd vote for giving the [contracts gem](https://github.com/egonSchiele/contracts.ruby) a shot in our codebase. Ruby will probably be released in 2029 and I want my static typing, damn it!
Or at least something close ;)

WDYT?

**Comment by chastell** [comment]
On technical level: given how slow Reek is already, we’d have to use it in development only (yes, I read the article about the gem’s speed – we’d have to test this, but the numbers in the article show that the gem still makes the code significantly slower).

On ideological level: Ruby is a fundamentally dynamic language; if you want static typing take a look at Crystal (I did and I like it a lot). :)

That said: I do think trying to specify contracts that fulfil our methods would be a good exercise (oh hello all the stuff that usually returns something usable, but sometimes returns `nil`…). I’m skeptical about putting this in production code, but might be interesting to try it as a testing tool.

**Comment by troessner** [comment]
We could make Reek faster (i have a gazillion ideas already) and test contracts for our heavily used methods to check the performance hit. Deal?

Re: Crystal. Not sold on it. I am missing the USP. Or there is one and i am missing it?

**Comment by chastell** [comment]
> We could make Reek faster (i have a gazillion ideas already) and test contracts for our heavily used methods to check the performance hit. Deal?

How about [RDL](https://github.com/plum-umd/rdl)? If we can ensure performance, I’d rather went with something a tad more versatile than contracts.ruby.

> Re: Crystal. Not sold on it. I am missing the USP. Or there is one and i am missing it?

Unique selling point? Types with Ruby syntax and performance. (Disclaimer: I do tonnes of heavy computations at the uni and doing them with Ruby is absurd, but the syntax and succinctness of algorithms expressed in Ruby still make it worth it. I wanted to write a lot of Rust extensions to make up for performance, but now Crystal seems like a much more natural choice.)

Also: this issue is about type-enforced Ruby, and this is _precisely_ what Crystal is… :stuck_out_tongue_winking_eye:

**Comment by chastell** [comment]
[Also](https://twitter.com/sdogruyol/status/677084627874508800):

> 10000 WebSocket connections: Crystal %1.85 Cpu 11 MB Memory vs Node %38.5 cpu 900 MB.

Also small, command-line apps that actually boot fast and don’t require a (current-enough) Ruby runtime to run. \*cough\*

**Comment by troessner** [comment]
>> How about RDL? If we can ensure performance, I’d rather went with something a tad more versatile than contracts.ruby.

Well, for me as a github star-whore I am a little sceptical of its star count. Just 10 stars doesn't exactly communicate "I am used in production a lot" to me. 
Also it seems like it [doesn't support Ruby 2.0](https://github.com/plum-umd/rdl#supported-versions-of-ruby) which would be a show stopper. OR we take righteous actions and drop 2.0 support as well. Which would clean up our codebase in reference to kw args significantly.
But I'm still open to giving it a shot - what are the major benefits you see of RDL over the contracts gem?

>> Unique selling point? Types with Ruby syntax and performance.

Yes, but that is not enough for me. In the end all languages are subjective (with the exception of PHP maybe) and for me to use sth new it has to blow me away and change my thinking. Go did that, Clojure did that, Haskell did that. I can't see the same thing happening with Crystal.
BTW I don't mean to be disrespectful in any way, I'm sure the guys creating Crystal are excellent at what they do and I have nothing but respect for them. It's just that I'm not that fascinated.
Add a revolutionary concurrency model like Go on top of Crystal and I might change my mind (not that they need to give a s**t about my opinion).

**Comment by chastell** [comment]
> I am a little sceptical of its star count. Just 10 stars doesn't exactly communicate "I am used in production a lot" to me.

The first version of RDL was released six days ago and RDL 1.0.0 was released on Friday, so it’s hard to expect it to be widely adopted. ;)

> OR we take righteous actions and drop 2.0 support as well.

I vote we do that regardless of which gem (or none…) we go with. Ruby 2.0 will be end-of-lined in February, there’s no need to support it beyond that. :stuck_out_tongue_winking_eye:

> what are the major benefits you see of RDL over the contracts gem?

The contracts gem seems to be all about classes of objects (strict types), which – when it comes to method arguments – is against everything Ruby is about. Ruby is all about duck typing and arguments loosely implementing a common interface (whatever calls the given method actually makes). RDL can be used to enforce strict types, but it can be also used to enforce arbitrary checks (via the block form), so you can say anything from ‘this method is designed to take anything that can respond to a two-argument `foo`’ to ‘this method requires an even integer’.

(Note that the opposite is true for method return types: the caller is the one burdened by what it can do with whatever the method returned, so there’s a huge difference between ‘this method always returns a string, it’s just an empty one sometimes’ – or ‘this method always returns a string and will raise if it can’t’ – and ‘this method sometimes returns a string and sometimes a nil, so almost every single call to it will need to be guarded a type check’.)

Note: I don’t know how RDL’s performance fares and how it compares to contracts’ (I’m not sure whether the ‘lightweight’ in description applies to performance or usage).

If you want to try out either then go ahead and let’s see where you get. :)

**Comment by troessner** [comment]
Ok, RDL sounds indeed more interesting.

P.S.: Ruby 3 will be statically typed with smart type inference a la Scala. Mark my words. I'd be willing to bet my hazienda on mallorca on that if anybody is up for it!

**Comment by mvz** [comment]
@troessner where in Reek's codebase would you want to start adding any contract?

I'm a little hesitant since I don't know how contracts will hamper refactoring. To my mind, they make the most sense for our public API methods.

**Comment by troessner** [comment]
>> I'm a little hesitant since I don't know how contracts will hamper refactoring. To my mind, they make the most sense for our public API methods.

Sounds like a good start!

But taking one step back:

Actually I don't know if we should use **any** external library at all.
I mean, the second somebody uses Reek's API and then uses a conflicting RDL library version the user will rightfully complain. If Reek was just stand-alone -> no problem. But since we're actually pushing for api usage that's a different topic.
WDYT?

**Comment by troessner** [comment]
Closing this one, maybe I'll come up with a preliminary pull request when I feel like it and then we can discuss this further ;)
