### ISSUE TITLE
Directory Directive blows up if the directory doesn't exist

### ISSUE THREAD

**Issue by jfelchner** [troessner/reek#799]
This seems reasonable at first glance, but I would really like to be able to have a common `.reek` file that I use everywhere (Rails, non-Rails, legacy, greenfield) that I can keep up-to-date with a simple script to copy my most recent config version to all my projects.  Unfortunately this issue keeps me from doing that.  For example:

```
'app/helpers':
  FeatureEnvy:
    enabled:                false
  UtilityFunction:
    enabled:                false
```

blows up on non-Rails projects (or Rails projects where the `app/helpers` directory has been removed).

Thoughts?

**Comment by troessner** [comment]
I see your point and i am open to change this behaviour. @mvz and @chastell if you agree as well i'll whip up a PR over the next days.

**Comment by mvz** [comment]
Yes, I think this is reasonable.

**Comment by troessner** [comment]
Fix up in #800

**Comment by troessner** [comment]
@jfelchner I just released Reek 3.8.1 with this very fix included, please upgrade and let us know how this works for you ;)

**Comment by jfelchner** [comment]
@troessner wow, this is some response time! :grinning:  Just tested it and it works amazingly well.  Thanks again! :+1: I'll send you a couple bucks for a :beer: or some :coffee:

**Comment by troessner** [comment]
Great that this worked for you, you're welcome ;)
