### ISSUE TITLE
UnusedPrivateMethod with actions in Rails Controllers

### ISSUE THREAD

**Issue by jfelchner** [troessner/reek#803]
This isn't a huge deal for me.  I just disabled this check in `app/controllers`, but I ran into it and thought you all would want to know.

It's fairly typical to have:

``` ruby
class MyController < ApplicationController
  before_action :blah

  def show
    # show stuff
  end

  # other stuff

  private

  def blah
    # Action-y stuff
  end
end
```

Currently this throws an `UnusedPrivateMethod` error.

**Comment by jfelchner** [comment]
And sorry about all the bug reports lately. :bug: :grinning:

**Comment by troessner** [comment]
I don't follow unfortunately - isn't the "blah" method in your example used by a controller action?

**Comment by chastell** [comment]
I think the point is that `before_action` should mark the `blah` as a used private method.

**Comment by chastell** [comment]
…and Reek marks is as an UnusedPrivateMethod because it’s not used anywhere else (other than in `before_action`).

**Comment by troessner** [comment]
Ah, I missed the before_action ;)

Wouldn't it make more sense to add this [here](https://github.com/troessner/reek#working-with-rails)?

**Comment by mvz** [comment]
> Wouldn't it make more sense to add this here?

Yes, that seems the most straightforward solution. There's a lot of metaprogramming Reek just can't deal with.

**Comment by jfelchner** [comment]
Cool. Whatever you all think is best. I just wanted to make you all aware of it! :+1: Feel free to close.
