### ISSUE TITLE
Drop private_attr?

### ISSUE THREAD

**Issue by chastell** [troessner/reek#804]
Now that Ruby 2.3 no longer warns on private accessors I’d love to drop the private_attr gem.

Unfortunately, the `attr_*` calls do not return the symbols for the created accessors, so we can’t go with `private attr_reader :foo, :bar`. Even more unfortunately we seem to have a policy of keeping private accessors at the top of classes (rather than with the rest of private methods). ;)

I see three options:

1. Drop private_attr and move `attr_*` calls below the `private` keyword; I assume this is a no-go, as it goes against the policy of keeping accessors at the top of classes.
1. Start the classes with `private` followed by `attr_*` calls followed by `public`. This feels fugly, but would allow us to both keep the accessors at the top of the classes and drop private_attr.
1. Keep private_attr for the sole purpose of having non-public accessors at the top of the classes (rather than not emitting warnings on private accessors).

Thoughts?

**Comment by mvz** [comment]
> Drop `private_attr` and move `attr_*` calls below the private keyword;

This has my preference. It keeps the 'public' API of the class in one place, the private in another. Option 2 is very ugly I think; option 3 is silly and would make me want to change the visibility and attribute detection code :frowning:.

**Comment by troessner** [comment]
>> Drop private_attr and move attr_* calls below the private keyword; I assume this is a no-go, as it goes against the policy of keeping accessors at the top of classes.

There is no policy for that. It just sucks. Because then you **use** attributes at the top of the class but you **declare** them at the bottom. That is against your reading flow. That's why it sucks. It's counter-intuitive. And doesn't seem fitting for a language where readability >>>> everything.

>> Drop private_attr and move attr_* calls below the private keyword;

Well, thankfully we're a team of three (== odd number) which gives us the opportunity for a clear decision.
If you two feel that's better then let's go for it. I'll still think that it sucks (see above) but I'll abide by that decision :)

**Comment by mvz** [comment]
> That is against your reading flow.

That is true, but then it would make sense to move **all** private methods to the top.

I think there are two ways of looking at this: Either you start out defining all the little details (supporting private methods, private attributes, etc.), and then define the 'big picture' methods (public methods), *or* you first defined the big picture methods, and then define the details ('If you're really interested, you can read the fine print here'). The first variety reads more like a mathematical paper, the second more like a report with an executive summary. The first public, then private convention tends to sort of favour the second way of laying out code.

> opportunity for a clear decision.

:smile: true, but I'd rather try to reach consensus first. Given that, which of the three options @chastell gave has your preference?

**Comment by chastell** [comment]
I think the distinction between private accessors and other private methods is artificial – the whole point of using accessors (over direct ivar references) is that they are methods than can be easily extended to cover new behaviour without the callers being any the wiser. After all, `attr_reader :foo` is just syntactic sugar for `def foo; @foo; end` – which I assume we’d all happily put down below the `private` keyword.

I also agree with the ‘first the big picture, then the details’ approach – the whole point of things like `Reek::AST::SexpExtensions::SendNode#module_creation_call?`:

```ruby
def module_creation_call?
  object_creation_call? && module_creation_receiver?
end
```

is to express it in terms of other methods – ones _defined below_.

> I'd rather try to reach consensus first.

Oh definitely! I’d rather we end up with any kind of voting as a last resort. :)

**Comment by troessner** [comment]
>> Oh definitely! I’d rather we end up with any kind of voting as a last resort. :)

Ok, let's go for it ;)

**Comment by chastell** [comment]
(I’m waiting for #796 to be merged so that @mvz doesn’t need to rebase that one. No rush on my side, just making a note that I’ll get to this one when it won’t be a burden to other open PRs.)
