### ISSUE TITLE
Build only PRs *or* pushes?

### ISSUE THREAD

**Issue by mvz** [troessner/reek#805]
Travis currently builds both PRs and pushes, which doesn't make that much sense for us since we always rebase and squash onto current master. How about turning one of them off?

**Comment by chastell** [comment]
Agreed; I don’t think buliding pushes makes that much sense (in other projects I often push work-in-progress branches just in case to not lose the code, not to get it build by CI).

**Comment by troessner** [comment]
<img width="786" alt="screen shot 2015-12-29 at 15 29 45" src="https://cloud.githubusercontent.com/assets/271109/12035884/11507e76-ae41-11e5-8aa8-c6264b41da0d.png">

**Comment by troessner** [comment]
I just disabled one of them. I leave figuring out which one to the astute reader.;)
