### ISSUE TITLE
Adding Exceptions for Memoized Instance Variables in TooManyInstanceVariables

### ISSUE THREAD

**Issue by jfelchner** [troessner/reek#807]
I think the purpose of the `TooManyInstanceVariables` smell is great, but there's the use case for instance variables where they're simply used to hold state for a memoized method and are typically not allowed to be set.  I think that this use case of instance variables is actually an indicator of good code.  The developer has decided that the method's results don't rely on changing state and understands the mutability of the class/method.

I'd like to add an exception to `TooManyInstanceVariables` to account for this and exclude instance variables if they are seen _only_ during a memoization (eg `@foo ||= 'bar'`).  If in other parts of the code it is read from, or if it's assigned elsewhere (eg `@foo = 'baz'`) then it would count even if it is memoized elsewhere in the code.

First, is this acceptable and second where would I go to see an example of a place to start the PR off from?  I don't have experience dealing with Ruby parsers.

**Comment by troessner** [comment]
Ad 1) great shoot!
Ad 2) https://github.com/troessner/reek/blob/master/docs/How-reek-works-internally.md

**Comment by troessner** [comment]
And of course https://github.com/troessner/reek#developing-reek--contributing ;)

**Comment by chastell** [comment]
> I'd like to add an exception to `TooManyInstanceVariables` to account for this and exclude instance variables if they are seen _only_ during a memoization (eg `@foo ||= 'bar'`).

Oooh, this is a very good idea! :+1:

**Comment by mvz** [comment]
Awesome. :+1:

**Comment by troessner** [comment]
@jfelchner I assume you won't pick this up any time soon, right?

**Comment by jfelchner** [comment]
@troessner correct.  I've had too much on my plate lately.  Thanks for checking in!

**Comment by mvz** [comment]
I still think this is a good idea.

**Comment by waldyr** [comment]
I can pick this up. But probably we should focus on the spec refactor. What do you think?

**Comment by troessner** [comment]
Yes, spec refactoring first please :)

**Comment by waldyr** [comment]
@jfelchner we just released version 4.4.0 which contains the requested. 

Reek should not account memoized instance variables in the TooManyInstanceVariables smell anymore.

Could you try it out and check if everything is working as you requested?

**Comment by troessner** [comment]
Closing this with #1032 merged.
