### ISSUE TITLE
Wrap exceptions under ReekException

### ISSUE THREAD

**Issue by troessner** [troessner/reek#809]
The title says it all - I believe we should wrap all exception that `Reek` explicitly might throw under `ReekException` and store the original exception as a attribute like [here](http://devblog.avdi.org/2013/12/25/exception-causes-in-ruby-2-1/) or use `Exception#cause`. 
That provides a cleaner separation of concerns to the user and will make debugging on the user end simpler (because it's clearer where the problem originates).

WDYT?

**Comment by chastell** [comment]
We can, we can also do exception tagging in our API:

```ruby
ReekException = Module.new
def any_of_our_api_methods
  # …
rescue => exception
  exception.extend ReekException
  raise
end
```

– this way _all_ of the exceptions originating from Reek will be explicitly tagged as such (and rescuable with `rescue ReekException`).

**Comment by mvz** [comment]
Yes, for exceptions that we anticipate and are implementation details. So I don't see the need to wrap `Errno::ENOENT` if user-supplied files don't exist (even though we can anticipate that to happen), but we should probably shield the user from errors in `parser`, so we could theoretically swap out the parser and still throw the same errors. This also requires having several exception types.

**Comment by chastell** [comment]
I agree we probably shouldn’t _wrap_ `Errno::ENOENT`, but I still think we could _tag_ it – the whole idea of exception tagging is ‘mark all exceptions originating from X dependency as such’. It would still be an `Errno::ENOENT`, it would just carry additional metadata for those who choose to check that.

**Comment by mvz** [comment]
But won't the backtrace already tell you where it came from? I'm not for giving people the opportunity to catch every exception (generally considered a bad thing) by something innocuous like `rescue ReekException`.

Do you maybe have any real-life examples of exception tagging and how it is used? Just trying to figure out the use case here.

**Comment by troessner** [comment]
Why not just:

```Ruby
class ReekException < Runtime; end
```
And then we wrap this:

>> Yes, for exceptions that we anticipate and are implementation details

into a ReekException and print out the original stacktrace like in the article above?

**Comment by mvz** [comment]
How about we start by using custom error classes everywhere we currently (re)raise an exception[1]? After that, we can see if there are any regularly thrown exceptions that we should wrap or otherwise modify.

[1] Except for keyword args!

**Comment by troessner** [comment]
>> How about we start by using custom error classes

You mean like ReekException::FileNotFound, ReekException::BadConfiguration .....?

**Comment by mvz** [comment]
> You mean like ReekException::FileNotFound, ReekException::BadConfiguration .....?

Yes, something like that. Doesn't have to be under a new `ReekException` namespace. We already have `Reek::Configuration::ConfigFileException`.

**Comment by troessner** [comment]
Yes, but users should be able to catch one exception mother type so I'd rather have something that is expressive like ReekException ;)

**Comment by mvz** [comment]
> Yes, but users should be able to catch one exception mother type

We can make them all subclasses of `Reek::Exception`.

**Comment by mvz** [comment]
I'm sure we'll figure those details out :smile:.

**Comment by chastell** [comment]
Just to make it clear: my point wasn’t to _either_ wrap everything in a single Reek expcetion _or_ do exception tagging – we can have both: wrap some stuff in a Reek exception (where it makes sense) _and_ tag all of Reek-originating exception with something (say, a `ReekOriginatingException` module) so that people can handle them as they see fit. But I’ll probably be ok with whatever you two come up with. :)

**Comment by troessner** [comment]
Yes, i got your point and i am fully on board with it!
Volle Fahrt voraus, Kapitän!

**Comment by mvz** [comment]
In the spirit of this ticket, I've started cleaning up the `raise` statements in Reek's codebase. It turns out there aren't many of them, and some can even be removed.

**Comment by mvz** [comment]
Regarding, tagging, @chastell, doesn't this mean a lot of boiler plate in each of our API methods?

**Comment by chastell** [comment]
Hm, yes, that’s the price for tagging all originating exceptions. That said: do we have _that_ many methods that we support as our official API? (If so, then maybe this means we have a large API, and maybe _that’s_ a problem.)

**Comment by troessner** [comment]
I'm not so sure if this ticket still makes sense.
We're in the process of validating:

* our configuration file before running Reek
* checking configuration via comments during runtime and handling them by outputting a warning
* have Examiner already catch incomprehensible source errors

So long story, seems like this issue is obsolete?
If nobody disagrees I'd like to close this one then to clean up our issues ;)

**Comment by chastell** [comment]
Hm, I think this issue is about Reek API consumers being able to easily catch Reek-originating errors, so a bit orthogonal to the points above. That said – maybe we should address this when (or, y’know, _if_…) someone consuming Reek’s API actually hits this as an issue. :)

**Comment by troessner** [comment]
Yes, but my point here was rather that with the road we're going down right now Reek would under **no circumstances** ever throw an exception and instead rather write on stderr.
So at the moment this ticket makes no sense :)

**Comment by chastell** [comment]
No _custom_ exception; we can just as well throw something outside of our control (a gem we depend on raises, there are some system issues, etc.). _If_ we were to tag Reek-originating exceptions we should probably tag these (extend with a module + reraise), but – as I said – let’s get to this part of the discussion if there is someone who would actually find it beneficial. :)

**Comment by mvz** [comment]
Yes, let's close this fornkw and reopen it if and when it becomes relevant.

**Comment by troessner** [comment]
And closed it is ;)
