### ISSUE TITLE
Reek does'nt see private methods called in RAILS hooks and validations as used

### ISSUE THREAD

**Issue by yld** [troessner/reek#813]
Given this model
````Ruby
class Document < ActiveRecord::Base
  validate :custom_validation

  private

  def custom_validation
  end
end
````

And this controller
````Ruby
class DocumentController < ApplicationController
  before_action :set_document

  private

  def set_document
  end
end
````
reek throws 2 UnusedPrivateMethod warnings

**Comment by troessner** [comment]
Please see [Working with Rails](https://github.com/troessner/reek#working-with-rails) - right now `Reek` does not have "Rails knowledge" baked in (I'd love to have this is as a plugin) so it's better to disable certain smells for Rails controllers.

**Comment by yld** [comment]
Oups, thank you.
