### ISSUE TITLE
Get rid of the unparser gem

### ISSUE THREAD

**Issue by troessner** [troessner/reek#815]
Coming from #801 :

Shouldn't we rather try to get rid of unparser? 
Not saying that it's not a great gem, but this dependency is weighing on us and AFAIS the drawbacks outweigh the benefits by far. I think we can easily kill it.

WDYT?

**Comment by mvz** [comment]
Yes!

**Comment by chastell** [comment]
Yes, please!

**Comment by schmijos** [comment]
:+1: I agree.

A specific problem is for example an arising incompatibility between **rubocop 0.36.0** (which requires `parser >= 2.3.0.0`) and **reek 3.7.1** (which requires `parser ~> 2.2.2` per **unparser 0.2.4**)

**Comment by mvz** [comment]
@schmijos we're already working on it in #827.

**Comment by mvz** [comment]
And done!
