### ISSUE TITLE
Using `exclude` in the Reek config does not work for the UnusedPrivateMethod detector

### ISSUE THREAD

**Issue by troessner** [troessner/reek#816]
Seems like we shipped a bug in the UnusedPrivateMethod detector that went unnoticed - apparently using `exclude` in the config doesn't work:

```
  ( $ ) cat unused_private_method.reek 
---
UnusedPrivateMethod:
  exclude:
    - "Foo#bar"

  ( $ ) cat foo.rb 
class Foo
  private
  def bar; end
end

  ( $ ) reek foo.rb 
  [3]:UnusedPrivateMethod: Foo has the unused private instance method `bar` [https://github.com/troessner/reek/blob/master/docs/Unused-Private-Method.md] 
```

Disabling via source code comment works though.
I'll look into this.

**Comment by chastell** [comment]
> Disabling via source code comment works though.

I was _just_ about to open an issue – no, [it doesn’t](https://github.com/chastell/lovely_rufus/commit/23ea8b6bd4d4a4a62a6473322a5d826c26225b18)…

**Comment by troessner** [comment]
It does, my friend, it does!
But on a class level, not a method level.
Please see the top of ContextBuilder for an example. We probably should make this clearer in the docs.;)

**Comment by troessner** [comment]
https://github.com/troessner/reek/blob/master/lib/reek/context_builder.rb#L20

**Comment by chastell** [comment]
Oooh. Is there a reason why we don’t support this on a per-method basis? (See #817 for a use-case.)

**Comment by troessner** [comment]
>> Oooh. Is there a reason why we don’t support this on a per-method basis? (See #817 for a use-case.)

You could make the argument that a "UnusedPrivateMethod" already screams "class scope" and not "method scope" ;)

Apart from that disabling by regex would be useless which is an incredible powerful feature. Just imagine how shitty [this](https://github.com/troessner/reek/blob/master/lib/reek/context_builder.rb#L20) would look like on a method base. You'd have to write 25 identical source code comments. Or disable it completely. Not cool, don't you agree? ;)

**Comment by troessner** [comment]
BTW our official docs mention the "disable via comment on a class level" [explicitly](https://github.com/troessner/reek/blob/master/docs/Unused-Private-Method.md#configuration) so it's not like it's a secret :laughing:

**Comment by chastell** [comment]
I have nothing against having this comment _working_ on class scope, I just don’t see why it couldn’t work on method scope as well. I wouldn’t mind being able to mark a Rails `before_filter` as _actually used_ and keep being warned that some other private methods in the controller can be potentially safely dropped.

**Comment by troessner** [comment]
>> I wouldn’t mind being able to mark a Rails before_filter as actually used and keep being warned that some other private methods in the controller can be potentially safely dropped.

I dont get it - cant you do this right now as well?

**Comment by chastell** [comment]
Well, we probably can with a class-level
```
# :reek:UnusedPrivateMethod: { exclude: [ThisClass#foo, ThisClass#bar] }
```
but it would be more useful (and symmetric to most other excludes) if we could do that as well just by adding
```
# :reek:UnusedPrivateMethod
```
before `#foo` and `#bar`. In many projects I work on private method names tend to change a lot and keeping such whitelisting local to them would require less maintenance. But I’m OK if we decide not to bother. :)

**Comment by troessner** [comment]
I see your point, but for instance [this](https://github.com/troessner/reek/blob/master/lib/reek/context_builder.rb#L20) would be significantly harder and tedious to do.
Just to give you a good example where setting this on a class scope makes sense ;)

**Comment by mvz** [comment]
Since each scope uses al the parent scopes' configurations as well, changing the detector to run at the method scope level would still allow per-class configuration. As I recall, there were other reasons to run at the class level, though. Mainly for efficiency. Right, @troessner?

**Comment by chastell** [comment]
Let me quote myself from above:

> I have nothing against having this comment _working_ on class scope, I just don’t see why it couldn’t work on method scope _as well_.

I’m all sold on a class-scope level (and the regex example makes perfect sense), it would just be nice to be able to stick [this](https://github.com/chastell/art_decomp/commit/8f7c958200af00835ba460842779560bae4794b4) next to the method in question (and drop the config part of the comment).

But if that’s a lot of work (of efficiency would be impacted) then by all means let’s not add this. :)

**Comment by troessner** [comment]
Re:

>> As I recall, there were other reasons to run at the class level, though. Mainly for efficiency. Right, @troessner?

and

>> But if that’s a lot of work (of efficiency would be impacted) then by all means let’s not add this. :)

Yes, I outlined the reasons [here](https://github.com/troessner/reek/pull/724#issuecomment-165887484)

**Comment by chastell** [comment]
Oh right, then I definitely rest my case. :)

**Comment by troessner** [comment]
It seems like this bug affects all smell detectors that work on class base. I just stumbled across this working on [this PR](https://github.com/whitesmith/rubycritic/pull/127/files#diff-497423560d2ac7e4f7259f11341b23b9R22) where I had to use source code comments for TooManyStatements because the "regular" exclude won't work.

I'll tackle this bug next.

**Comment by troessner** [comment]
>> It seems like this bug affects all smell detectors that work on class base. I just stumbled across this working on this PR where I had to use source code comments for TooManyStatements because the "regular" exclude won't work.

Scratch that, it is just UnusedPrivateMethod, I couldn't see straight.

**Comment by troessner** [comment]
Closing this one with #885 merged.
