### ISSUE TITLE
UnusedPrivateMethod triggered when the caller is in another class

### ISSUE THREAD

**Issue by chastell** [troessner/reek#817]
[`LovelyRufus::Layers::EmailQuoteStripper#fixed_quote`](https://github.com/chastell/lovely_rufus/blob/23ea8b6bd4d4a4a62a6473322a5d826c26225b18/lib/lovely_rufus/layers/email_quote_stripper.rb) is a private method called by `#call` ([inherited from `QuoteStripper`](https://github.com/chastell/lovely_rufus/blob/23ea8b6bd4d4a4a62a6473322a5d826c26225b18/lib/lovely_rufus/layers/quote_stripper.rb)), but Reek marks it as unused.

I doubt we can do anything with this with our current per-file scope (and no knowledge about the code from ancestor classes), so we should probably close this now – but I wanted to have this as a known limitation of the smell.

**Comment by troessner** [comment]
Yes! The template pattern is unfortunately something `Reek` can't be aware of right now. PR incoming for the UnusedPrivateMethod docs.

>> I doubt we can do anything with this with our current per-file scope

Yes, we should have a global registry that maps out the entire source tree.
Now who's up for this pull request?!

**Comment by troessner** [comment]
Addressing this in #818

**Comment by mvz** [comment]
This behavior is basically as I envisioned it :smile:.

**Comment by chastell** [comment]
OK, I’m closing this one for now.

> Yes, we should have a global registry that maps out the entire source tree.

Until this appears, of course. ;)

**Comment by troessner** [comment]
>> Yes, we should have a global registry that maps out the entire source tree.

That would probably be the biggest PR `Reek` has ever seen :)
