### ISSUE TITLE
Move all development dependencies in our gemspec to the Gemfile

### ISSUE THREAD

**Issue by troessner** [troessner/reek#821]
Let's move all development dependencies in our gemspec to the Gemfile.
The separation right now doesn't make any sense and is academic, but not pragmatic.
And we use bundler for everything anyway.

WDYT?

**Comment by troessner** [comment]
Right now I'm doing 

>> RUN bundle install --without local_development development

in our Dockerfile. That already shows that something is wrong in our set up. We only need one development group I believe.

**Comment by mvz** [comment]
> We only need one development group I believe.

I've traced the origin of the local_development group to this PR: https://github.com/troessner/reek/pull/226, and this commit: 68f97b700cb519ce5510305b39d0cc3a86c8869e. I don't know if these considerations are still relevant.

**Comment by mvz** [comment]
By the way, from where will CodeClimate pick up our Dockerfile in the end? From the git repo? From the gem? Somewhere else?

**Comment by troessner** [comment]
>> By the way, from where will CodeClimate pick up our Dockerfile in the end? From the git repo? From the gem? Somewhere else?

I guess they build the image once and then it's kind of .... there on their servers. So it would be kind of static. No idea how the update process would work, we'll need to clarify that ;)

But just to be clear here: My suggestions in this issue are completely independent from CodeClimate. Working on it just made the issues in our current set up more obvious to me.

>> I don't know if these considerations are still relevant.

They are and I intend to honor them! 

Let me explain what I had in mind:

- Move all development dependencies from the gemspec to the Gemfile into the group "development"
- Rename the currently only group in the Gemfile "local_development" to "debugging". Because that is what it is used for (not sure what "yard" is doing there)

That way it's crystal clear what is used for what and we use bundler or rather: the Gemfile consistently for development.

wdyt?

**Comment by mvz** [comment]
Yes, this looks sensible to me.
