### ISSUE TITLE
undefined method `method_context_class' for #<Reek::Context::MethodContext:0x00>

### ISSUE THREAD

**Issue by backus** [troessner/reek#831]
I was playing with reek on master and noticed a regression which I don't think is released yet. The following code should reproduce the issue

```ruby
def foo
  def bar
  end
end
```

I believe this commit introduced the issue: https://github.com/troessner/reek/commit/dd780b41b7304517585b055fe2a7631e50a2a9f7

**Comment by backus** [comment]
Thanks for the quick fixes @mvz!

**Comment by troessner** [comment]
Fixed with the release of 3.9.0 just now.
