### ISSUE TITLE
Investigate Ruby 2.3 syntax consequences

### ISSUE THREAD

**Issue by chastell** [troessner/reek#836]
We should handle the new syntax introduced in Ruby 2.3.

- [ ] `&.` safe navigation
- [ ] `<<~` squiggly heredoc

**Comment by chastell** [comment]
(In the future we might want to introduce a code smell that suggests turning on frozen string literals in per-file comments, but I’d make it a separate issue.)

**Comment by seanhandley** [comment]
:+1:

I'm being held back from using the new 2.3 syntax features because my build process relies on being able to run rubycritic.

**Comment by troessner** [comment]
"RubyCritic"? Wrong browser tab? ;)

Reek should be able to deal with 2.3 syntax already. This issue is more about if and how we should handle new node types like for the safe navigation operator. We just ignore it right now but it shouldnt raise any errors.

**Comment by seanhandley** [comment]
@troessner I get an error when running rubycritic because it has a hard dependency on Reek. See the below stack trace:

```
  app/models/user.rb:4 :: parse error on value ":" (tCOLON)
  skipping app/models/user.rb
ERROR: parsing ruby file app/models/user.rb
Racc::ParseError: app/models/user.rb:4 :: parse error on value ":" (tCOLON) at:
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:528:in `on_error'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby_parser-3.7.3/lib/ruby_parser_extras.rb:1125:in `on_error'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby_parser-3.7.3/lib/ruby_parser_extras.rb:1037:in `block in process'
ERROR: parsing ruby file app/models/user.rb
```

My code runs fine with the lonely operator but it's reek's use of ruby-parser, (and in turn racc) that generates language parse errors.

**Comment by troessner** [comment]
`Reek` uses `parser`, *not* `ruby_parser`.
Please show me the full stacktrace, the actual call and relevant version (Reek & Rubycritic)

**Comment by seanhandley** [comment]
Sorry @troessner - my mistake.

**Comment by seanhandley** [comment]
That is the full stacktrace I get from running rubycritic. Reek is 3.9.1 and RubyCritic is 2.7.0

That error goes away when I remove this line from my code

```ruby
User.first&.send(:[], 'blob')
```

**Comment by seanhandley** [comment]
Also `Object&.new` creates this issue.

**Comment by chastell** [comment]
Both are parsable by Reek just fine:

```
$ echo 'User.first&.send(:[], 'blob')' | bin/reek
$ echo 'Object&.new' | bin/reek 
$ echo '= invalid syntax =' | bin/reek 
STDIN:1:1: error: unexpected token tEQL
STDIN:1: = invalid syntax =
STDIN:1: ^                 
STDIN: Parser::SyntaxError: unexpected token tEQL
```

Given that the exception comes from `ruby_parser` → `racc/parser` I do think this is some other gem’s dependency issue.

**Comment by seanhandley** [comment]
Thanks @chastell - I'll keep looking.

**Comment by seanhandley** [comment]
Looks like it is indeed a `ruby_parser` issue: https://github.com/seattlerb/ruby_parser/commit/da22d1e256305dff2bb549e9f13fcf9f69c43bb2

Support for Ruby 2.3 isn't yet released.

**Comment by mvz** [comment]
@chastell what actually do you mean by 'handle' in this ticket? I'd like to rename it so it reflects the contents better and doesn't suggest Reek has a problem parsing 2.3 syntax.

**Comment by chastell** [comment]
When I created it I assumed we will have to add at least stub methods so as not to blow up, but I checked and we don’t (the syntax is simply ignored). I _think_ we will need to handle the new syntax only when we want it to trigger certain smells (say, NilCheck…) – if I’m right then we should indeed close this issue.

**Comment by mvz** [comment]
We should probably see how replacing `.` with `&.` affects Reek's results then. The `<<~` hopefully just renders a type of string literal, but we should check that too. I updated the title accordingly.

**Comment by troessner** [comment]
>> When I created it I assumed we will have to add at least stub methods so as not to blow up, but I checked and we don’t (the syntax is simply ignored). I think we will need to handle the new syntax only when we want it to trigger certain smells (say, NilCheck…)

Yes, that's exactly what I had thought as well ;)

**Comment by Frost** [comment]
I just encountered this:

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ reek -v
reek 4.0.3
$ cat reek_fail.rb 
def foo
  []&.map { |var| puts(var) }
end
$ reek reek_fail.rb 
/home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:124:in `block in ignored_iterator?': undefined method `name' for s(:array):#<Class:0x0055566fb85270> (NoMethodError)
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:124:in `any?'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:124:in `ignored_iterator?'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:115:in `increment_depth'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:105:in `block in scout'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:100:in `map'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:100:in `scout'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:70:in `find_deepest_iterator'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:48:in `inspect'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_detector.rb:47:in `run_for'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_repository.rb:47:in `block in examine'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_repository.rb:46:in `each'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_repository.rb:46:in `examine'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/examiner.rb:81:in `block in run'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:85:in `each'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:87:in `block in each'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:86:in `each'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:86:in `each'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/examiner.rb:80:in `run'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/examiner.rb:37:in `initialize'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:24:in `new'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:24:in `block in populate_reporter_with_smells'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:23:in `each'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:23:in `populate_reporter_with_smells'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:15:in `execute'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/application.rb:28:in `execute'
	from /home/frost/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reek-4.0.3/bin/reek:13:in `<top (required)>'
	from /home/frost/.rbenv/versions/2.3.0/bin/reek:23:in `load'
	from /home/frost/.rbenv/versions/2.3.0/bin/reek:23:in `<main>'
```

The same thing goes for a `{}&.map { ... }`

**Comment by mvz** [comment]
@chastell are you still working on this? I can take a look at @Frost's issue at least.

**Comment by mvz** [comment]
@Frost I investigated your problem and it looks like there's a bug in the parser gem. See https://github.com/whitequark/parser/issues/291.

**Comment by mvz** [comment]
@Frost .. and the bug in parser has been fixed.

**Comment by troessner** [comment]
Do you stil. have this on your radar @chastell ? Just asking cause it's still labeld "work in progress"...

**Comment by chastell** [comment]
Ah, right, sorry – I think the consensus is that (a) since the parser gem upgrade the new syntax doesn’t blow up Reek anymore, (b) the `&.` safe navigation operator should be potentially considered a nil-check (but that’s a separate issue and I’m not sure whether we reached consensus on this) and (c) the `<<~` squiggly heredoc operator shouldn’t trigger any smells.

Tentatively closing, feel free to reopen if I’m missing something.
