### ISSUE TITLE
Private method used for after_initialize is marked as unused (false positive)

### ISSUE THREAD

**Issue by oliverklee** [troessner/reek#843]
One of our Rails models looks like this:

````ruby
class User < ActiveRecord::Base
  after_initialize :default_values

  private

  def default_values
     # do something
  end
end
```

Reek marks this method as unused:

```
app/models/identity/user.rb -- 1 warning:
  [108]:UnusedPrivateMethod: Identity::User has the unused private instance method `default_values` [https://github.com/troessner/reek/blob/master/docs/Unused-Private-Method.md]
```

**Comment by oliverklee** [comment]
We have the same problem in our controllers where private methods are used in the `before_action` and `after_action` filters while reek marks them as unused.

**Comment by oliverklee** [comment]
Related: #724

**Comment by oliverklee** [comment]
Note: Our user class is located within an Identity module.

**Comment by troessner** [comment]
This is one of this detectors [know limitations](https://github.com/troessner/reek/blob/master/docs/Unused-Private-Method.md#known-limitations) we can't fix. At least not without implementing a global class / method registry.

So for now I'm afraid you'll have to disable this detector either via [source code comment](https://github.com/troessner/reek#source-code-comments) or disable it completely in your config. Using `exclude` is not working right now unfortunately for this detector ( #816 )

We're thinking of disabling this detector by default in #844 - let's continue the discussion over there.
Closing this issue.

**Comment by oliverklee** [comment]
Thanks for the clarification.

**Comment by mvz** [comment]
Please also see the section on Rails in the documentation. It list detectors that are better left disabled in a Rails project.
