### ISSUE TITLE
Small improvements to our Dockerfile

### ISSUE THREAD

**Issue by troessner** [troessner/reek#846]
1.) We can change instructions like

```
ADD . ${app_dir}
WORKDIR ${app_dir}
```

to

```
WORKDIR ${app_dir}
ADD . .
```

as I learned while reading [an article](https://semaphoreci.com/community/tutorials/dockerizing-a-ruby-on-rails-application) in my newsfeed about docker since the first "." will refer to your local directory and the second "." to whatever WORKDIR is set.

2.) Replace ADD instructions with COPY like mentioned in the [best practices](https://docs.docker.com/engine/articles/dockerfile_best-practices/)

3.) dockerignore is ...ignored, means that everything is copied into the image

4.) `bundle install` is not cached properly, meaning that this runs the install process on every build

**Comment by chastell** [comment]
> 4.) `bundle install` is not cached properly, meaning that this runs the install process on every build

IIRC this happens because we don’t have `Gemile.lock` – if we had this (in the repo or elsewhere) then this would be cached.

**Comment by troessner** [comment]
But we do have a Gemfile.lock locally and it should be copied to the image like everything else does, since docker doesnt care about .gitignore. 
So I am not sure that git-absence of Gemfile.lock has anything to do with this.

**Comment by chastell** [comment]
Hmm, maybe it gets touched / the timestamps get updated and Docker invalidates all subsequent caches (and so rebundles)?

**Comment by troessner** [comment]
Quoting from [here](https://medium.com/@fbzga/how-to-cache-bundle-install-with-docker-7bed453a5800#.t6c2966t4):

>> Docker creates a layer for each command executed. When you execute it a second time it will reuse the cache from previous execution if it did not change.
In this case there is a high probability that the ADD command will get a cold cache, because you change your app’s code all the time (hopefully).

But this happens also for me when there are no code changes.

I still could try this trick:

````
COPY Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install
```

but at the moment my docker installation isn't working anymore :(
I'll investigate after I fixed this.

**Comment by troessner** [comment]
Update: This [blog](http://ilikestuffblog.com/2014/01/06/how-to-skip-bundle-install-when-deploying-a-rails-app-to-docker/) mentions the same trick:

>> See what I did there? Before copying the whole app, I copied just the Gemfile and Gemfile.lock into the tmp directory and ran bundle install from there. If neither file changed, both ADD instructions are cached. Because they are cached, subsequent commands—like the bundle install one—remain eligible for using the cache.

I'll look into it ;)

**Comment by chastell** [comment]
I was just about to dig out that blog post and link it here. :)

**Comment by troessner** [comment]
I don't think I'll ever look into this again because it's far from being a problem and I'd rather spent my time differently :)
Closing this one.

**Comment by backus** [comment]
If you ever are interested in finding easy tweaks to improve the dockerfile you should checkout [hadolint](https://github.com/lukasmartinelli/hadolint)

**Comment by troessner** [comment]
Oh, this looks very nice, thanks a lot for the tip!
