### ISSUE TITLE
Default rules and user experience

### ISSUE THREAD

**Issue by andyw8** [troessner/reek#855]
Sorry if this already been discussed, but @troessner's enabling of Reek on [transitions](https://codeclimate.com/github/troessner/transitions) reminded me that the out-the-box experience for new users isn't great due to large number of warnings. 

I think disabling some of the default rules would help to highlight the most useful smells that Reek can detect. At the moment they seem lost in the noise. The one that I think is really off-putting is `IrresponsibleModule`, since practically every Ruby codebase would fail this, even if the code itself is fine. (I'm not against the rule itself, just the default config).

Any thoughts?

**Comment by troessner** [comment]
But then how would you consciously re-enable it? Once it's out of a users mind he'll never re-enable it, say, 3 months later.

**Comment by mvz** [comment]
I think the upcoming `--todo` feature will help a lot here.

**Comment by troessner** [comment]
Great point @mvz, hadnt thought about that!

**Comment by troessner** [comment]
I'm closing this one now with #723 merged - I believe the todo list addresses all of our concerns.

**Comment by troessner** [comment]
And thanks for bringing this up @andyw8, appreciate it!
