### ISSUE TITLE
What to do about Smell Category?

### ISSUE THREAD

**Issue by mvz** [troessner/reek#866]
I think Smell Category could be a useful concept, but it's only half implemented. Let's discuss where we want to go with this. Some options:

1. Remove it from the code and documentation
2. Remove it from the code but keep it in the documentation as an organizing principle
3. Keep it in the code and expose it
  * In the configuration file
  * To the `--smell` CLI option (#863)

For option 3 to work sensibly, we will need to make sure categories that contain more than one smell have a different name from any of the smells. This is currently not the case, since LongParameterList is both a smell and the category that LongYieldList belongs to.

Current work tends toward 3 as an end goal, but we're not very active with this and I don't think there's much of a demand from our users. Therefore, option 2 would definitely be a valid choice in my mind.

**Comment by troessner** [comment]
Agree with you, i think [2] is the way to go!
I think neither us nor the users are really utilizing those categories at the moment so we can remove a lot of complexity and code.

**Comment by mvz** [comment]
@chastell any thoughts on this?

**Comment by chastell** [comment]
Yes, let’s simplify where possible.

BTW: I know I have a huge backlog of Reek stuff to catch up, I was super busy lately. On the flip side I’ll be talking about Reek on tomorrow’s Pivorak meetup in Lviv. :)

**Comment by mvz** [comment]
Option 2 has been chosen and implemented.
