### ISSUE TITLE
Blocker for Reek 4: keyword arguments for your spec matchers

### ISSUE THREAD

**Issue by troessner** [troessner/reek#891]
We almost forgot about this: https://github.com/troessner/reek/blob/master/lib/reek/spec/should_reek_of.rb#L14
We should fix it before releasing Reek 4.

**Comment by troessner** [comment]
and let's not forget about: https://github.com/troessner/reek/blob/master/lib/reek/configuration/app_configuration.rb#L52
But that one should be trivial.

**Comment by mvz** [comment]
@troessner I think this can be closed?

**Comment by troessner** [comment]
Indeed ;)
