### ISSUE TITLE
Running reek for all files from RSpec file does not seem to work

### ISSUE THREAD

**Issue by pkuczynski** [troessner/reek#895]
I created `spec/reek_spec.rb` file with content:

```ruby
require 'reek'
require 'reek/spec'
require 'spec_helper'

describe 'Make sure all code' do
  it 'contains no code smells' do
    Dir['lib/**/*.rb'].each do |file|
      expect(file).not_to reek
    end
  end
end
```

I debug it and it correctly iterates over all files in my gem, but does not seem to check if they smell. When I run reek command from terminal, I see 60 warnings.

Am I doing something wrong?

**Comment by troessner** [comment]
Hmmm, can't see anything wrong with that on first glance. 
We're doing something very similar [in Reek](https://github.com/troessner/reek/blob/master/spec/quality/reek_source_spec.rb) which works fine. 

How are actually calling this spec? We run it by rake task, so it's starting at the root of the project, so 'lib/**/*.rb' actually works out.
I suspect that you do this differently so Dir['lib/**/*.rb'] is just empty. 

What's the output of 

```Ruby
  it 'contains no code smells' do
    puts "!!! Dir['lib/**/*.rb'] is #{Dir['lib/**/*.rb'].inspect}"
    Dir['lib/**/*.rb'].each do |file|
      expect(file).not_to reek
    end
```

**Comment by pkuczynski** [comment]
You can see my branch here: https://github.com/railsconfig/config/tree/reek

I had similar doubts, but added puts and it was listing all the files on the execution.

I am using appraisal gem to test my gem against different versions of rails, so I execute tests using `appraisal rspec`

**Comment by troessner** [comment]
>> I am using appraisal gem to test my gem against different versions of rails, so I execute tests using appraisal rspec

Then I'm guessing that appraisal suppresses / redirects the STDOUT from rspec.
Seems not like a Reek problem, but an appraisal one so you probably should investigate in this direction :)

**Comment by mvz** [comment]
> Then I'm guessing that appraisal suppresses / redirects the STDOUT from rspec.

Hm, but even so it should cause the specs to fail, right?

@pkuczynski can you try running just rspec to eliminate appraisal as a possible source of this problem?

**Comment by mvz** [comment]
My guess is `Dir['lib/**/*.rb'].each` yields strings. This results in `expect(file).not_to reek` interpreting the value of `file` as literal source code instead of a file name.

In Reek's tests, we use `Pathname.glob`, which yields `Pathname` objects, which the matcher will interpret as files to be read and checked.

**Comment by troessner** [comment]
Ah, makes sense, well spotted @mvz !

**Comment by troessner** [comment]
@pkuczynski any updates from your side?

**Comment by pkuczynski** [comment]
Sorry for late reply. I follow @mvz suggestion and change my test to look like this:

```ruby
    Pathname.glob('lib/**/*.rb').each do |file|
      expect(file).not_to reek
    end
```

and it works perfectly! :)
