### ISSUE TITLE
Reek 4 - let's get this going!

### ISSUE THREAD

**Issue by troessner** [troessner/reek#896]
Let's release Reek 4 after we have merged all current PR's.
WDYT?

**Comment by mvz** [comment]
I'd like to have one more look at our API and the open tickets this Tuesday and see if there's anything I'd like changed or included. After that, let's roll!

**Comment by mvz** [comment]
I'll have a look at the API and open tickets today.

**Comment by troessner** [comment]
Reek 4 is out, closing this one.
