### ISSUE TITLE
Can't suppress PrimaDonnaMethod and UnusedPrivateMethod smells in method context

### ISSUE THREAD

**Issue by rolandhawk** [troessner/reek#903]
I have this code:

```
class Bang
  # :reek:PrimaDonnaMethod
  def bang_one!
    puts "bang!"
  end
  def bang_two!
    puts "bang bang!!"
  end
end
```

Reek still report 2 PrimaDonnaMethod smells.
I know that PrimaDonnaMethod and UnusedPrivateMethod work in class context. But it makes me can't suppress the warning partially. Is it actually intended to be like that?

**Comment by troessner** [comment]
The right configuration would be this:

```Ruby
# :reek:PrimaDonnaMethod: { exclude: [ bang_one ] }
class Bang
end
```

but unfortunately that **is** a bug indeed as I just realized.
I'll look into fixing this one but for now you'll have to live with this I'm afraid :-/

**Comment by jhubert** [comment]
Just ran into this one as well.

**Comment by troessner** [comment]
I'll look into fixing this the next weeks :)

**Comment by troessner** [comment]
Actually the configuration via source comment is working for UnusedPrivateMethod - we also have a [spec](https://github.com/troessner/reek/blob/master/spec/reek/smell_detectors/unused_private_method_spec.rb#L108) validating this. I'll update the docs for this as well though, since it's still not obvious.

**Comment by jhubert** [comment]
Yeah, I was only running into the PrimaDonnaMethod one.

**Comment by rolandhawk** [comment]
cool thanks @troessner

**Comment by troessner** [comment]
Just released the bugfix, please upgrade.
