### ISSUE TITLE
Suggestion: Detect subclassing of core classes

### ISSUE THREAD

**Issue by andyw8** [troessner/reek#907]
I came across some code today which reminded me of this post: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes

I think it would be fairly easy to detect this in Reek.

Some considerations:

* What classes should be considered? String, Hash and Array come to mind but I'm sure there's plenty others.
* What should the smell be called?

**Comment by troessner** [comment]
Good idea!

I think your selection is good to get started.

How about SubclassedFromCoreClass smell? 😆

**Comment by andyw8** [comment]
Ok, I'll start looking into it.

**Comment by troessner** [comment]
Nice!

**Comment by mvz** [comment]
No need to close this, right?

**Comment by andyw8** [comment]
Sure, I just thought since it's not waiting on any action from the Reek team it would help to keep the noise down. Could be a while until I get around to actually implementing it.

**Comment by troessner** [comment]
#954 is merged and released, closing this one.
