### ISSUE TITLE
Tweak the behaviour of how we handle the --todo flag

### ISSUE THREAD

**Issue by troessner** [troessner/reek#916]
Coming from #914:

>> I've noticed another strange behavior, though. It seems that when generating the todo file, reek actually respects an existing reek file. Is this intended?

It's obvious that we should tweak the behaviour of how we handle the --todo flag since it's confusing and / or not properly explained.

### I believe we have 2 use cases:

1.) There is already an existing configuration file. 

In this case we could ask the user:

>>
We found the existing configuration file xyz.reek and will take this into account.
Should we append the output of --todo to this file? 
In case of "no" we'll just write the results to STDOUT 
[Yes/no/abort]

In case the user answers "yes", we'll just append the results to the existing configuration file using the existing configuration file with a marker above it like this

```Yaml
    ### Autogenerated by `reek --todo -c xyz.reek` ###
```

In case of "no", we'll just write it to STDOUT and in case of "abort" we'll....just abort.  

2.) There is not existing configuration file

In this case, the behaviour stays as it is right now.

WDYT?

**Comment by mvz** [comment]
There is a sub-case of 1) where the existing `.reek` file was generated by `--todo`. In this case I may want to ignore the settings contained therein, and just overwrite the generated file. Hopefully, my code will have improved and the new generated file will be smaller :smile:.

**Comment by troessner** [comment]
>> There is a sub-case of 1) where the existing .reek file was generated by --todo. In this case I may want to ignore the settings contained therein, and just overwrite the generated file.

How would you like to handle this? I can think of a lot, a **lot** of valid edge cases here that would trigger bugs and confusion. I'd rather not handle it all. Overwrite, or not.
That's the way most people use those tools anyway.

I'd revisit this if we had a feature like rubocop where one file can include others, because then it is easy to separate what has been added programmatically and what not. Using markers in one file doesn't work well if you want to edit the file programmatically.

wdyt?

**Comment by mvz** [comment]
> Overwrite, or not.

Yes, those are the choices we should offer, but in order to succesfully overwrite it, we have to actually ignore the contents, since otherwise the new file will be blank.

But maybe you mean: Append, or not? I agree that is the easiest option now, and avoids creation of extra `.reek` files.

In that case, we should in fact append to the config file passed on the command line, if any.

**Comment by troessner** [comment]
>> But maybe you mean: Append, or not? I agree that is the easiest option now, and avoids creation of extra .reek files.

Errr, yes, I basically meant it like in my initial posting above:

>> In case the user answers "yes", we'll just append the results to the existing configuration file using the existing configuration file with a marker above it like this

Regarding:

>> In that case, we should in fact append to the config file passed on the command line, if any.

Ack.

**Comment by troessner** [comment]
Let's fix this, this is really annoying. I'm have a long flight ahead of me next week and I'll look into this. 
But let's make it simpler. I believe our thought process above is too complicated.
I think the most basic relevant use case here is that somebody re-runs Reek with the --todo flag with the intention of updating this file so `bundle exec reek lib` is a success.

How about the follow super-simple algorithm:

* If we run Reek with --todo
* we ignore the existing .reek.todo
* and simply overwrite it

No cli yes / no / whatever, not catering to exotic use cases, just a very simple workflow that a user himself can then adapt to what he needs (with 99% probably being happy with the way it is)

wdyt?

**Comment by mvz** [comment]
Yes, let's go with that.

**Comment by troessner** [comment]
And re-thinking this even further: What's the purpose of the --todo flag? Right, to ease the **adoption** of Reek into a bigger codebase that has not been developed using code quality tools.
If you have the need to continuously re-run Reek with the --todo you're doing something really wrong and probably should think about if you really want to use Reek at all because you're basically defeating its purpose like that.

**Comment by mvz** [comment]
Re-running could serve the purpose of checking your progress towards good quality: Some exclusions may have become outdated. It's how I use rubocop's `--auto-gen-config`.

**Comment by troessner** [comment]
>> Re-running could serve the purpose of checking your progress towards good quality: Some exclusions may have become outdated.

But manually checking this given a bigger codebase will be very tedious and error-prone.
I doubt that anybody is using it like this.

>>  It's how I use rubocop's --auto-gen-config

Fair point. But Rubocop and Reek are hard to compare. Rubocops warning are far more volatile than Reeks ones on average. It's easier to fix a "foobar rescue false" than fixing a FeatureEnvy.
So I'm not sure that the comparison holds.

**Comment by mvz** [comment]
I think we're overthinking this a bit. I'd rather first make `--todo` useful for ourselves, and only then see if the way other people use it is good or bad: If their use leads to problems, we can always consider whether we want to accommodate it or discourage it.

This also means I think we can just describe how it works in the README, rather than give some reasoning based on how we now think this feature is supposed to be used. So we can just say something like: "Running reek with the `--todo` flag simply overwrites any existing `.todo.reek` file, and ignores all configuration files, even when passed on the command line".

If we really want to give a reason, we can say it is because we want `reek --config .todo.reek` not to return any smells.

**Comment by jhubert** [comment]
Chiming in here a little late.

I'm setting up reek on a new project and I want to create a todo file taking into account my preferences that are already in a config file. For example, if I preset the following rule:

```yaml
"app/controllers":
  IrresponsibleModule:
    enabled: false
```

I would expect `rake -t` to not include any of those violations. In testing now (and based on the readme), it seems that it ignores that configuration entirely.

Is there any easy way to create a todo file only containing things that you want to fix?

**Comment by troessner** [comment]
>> Is there any easy way to create a todo file only containing things that you want to fix?

[Not really](https://github.com/troessner/reek/#beware-of-multiple-configuration-files).
I fully understand the need for this though. We made a decision if we wanted to support multiple configuration files and opted for the easier, less ambiguous solution - that is, to only support one configuration file.
So for now I'm afraid you have to mix your configuration into one file.
