### ISSUE TITLE
Reek to be used in coala

### ISSUE THREAD

**Issue by sils** [troessner/reek#920]
Hi,

I'm a developer of coala (coala-analyzer.org) and want to inform you, that we're brewing an integration for your tool at https://github.com/coala-analyzer/coala-bears/pull/434 .

You seem to have written a lot of user interaction stuff which is essentially what coala aims to do (letting analysis writers focus on analysis instead of UI, it's a language independent framework.) With coala users don't have to learn multiple tools for multiple languages though and can just use one tool, one config, one command for all their languages in their projects.

Should be merged soon and released by the end of the month. (Pre release happens on merge.)

**Comment by troessner** [comment]
Nice! Do you gather usage statistics for the tool maintainer so we can see in what contexts and how Reek was used?

**Comment by sils1297** [comment]
No, we don't have usage statistics.

**Comment by sils1297** [comment]
It's an interesting idea though, would you mind filing an issue at coala elaborating a bit on what you would love to see? Maybe we can make a feature for it.

Also if you have suggestions what other tools would be good to have among yours to cover as much as possible for ruby projects with static code analysis would be great.

We currently have:

- Code clone detection (via CPD)
- Style Checking (RuboCop)
- Smell checking (reek)
- Syntax checking (ruby -wc)
- Other native language independent routines (spacing, invalid hyperlink check, ...)

**Comment by troessner** [comment]
@sils1297 I haven't forgotten about this, just swamped right now, will come back to this later.

**Comment by troessner** [comment]
I did check out your generated doc page [here](https://github.com/coala/bear-docs/blob/master/docs/RubySmellBear.rst) - the way this looks is very confusing and I don't think people will use it like that.

That's exactly the problem I have seen over the years with things like that:

>> With coala users don't have to learn multiple tools for multiple languages though and can just use one tool, one config, one command for all their languages in their projects.

That all sounds nice and dandy ... until you run into the classic "oh, how the hell do I handle configuration?" problem.

No offense, I think it's a noble effort, but putting another layer on top of Reek will be obscure to the user. [RubyCritic](https://github.com/whitesmith/rubycritic) tries something similar and the handling of different detectors is already a nightmare because you have to make very different tools kind of look the same. And that is **only** for Ruby, not for dozens of other languages.

Best of luck -  closing this one.

**Comment by sils** [comment]
Hey @troessner coud you elaborate a bit on the problem? I'm not fully getting it and would love to know more.

I do agree that we have to improve on the documentation which is hard indeed. Configuration might not be as advanced as using a particular tool directly (usually it can be, sometimes there are technical issues) but usually enough to configure most projects properly.

We'd be grateful on any suggestions.

**Comment by mvz** [comment]
@sils I can't speak for @troessner but on that page I see several parameters that when true enable a Reek detector, and several that when true disable a detector. I would at least make it consistent.

**Comment by sils** [comment]
@mvz thanks for your feedback. Is there any practical disadvantage apart from making it hard for, say, reek users to migrate to coala?

Background: We're actively not mirroring exactly the original settings. This way the same settings will be available for other bears for other languages and there's no need to read up on everything again if a similar feature set exists. When making an abstraction like this we sometimes have to invert the meaning.

E.g. if I write in my coafile:

```ini
[default]  # Inherits to all other sections
use_spaces = hell yeah
indent_size = 2
```

I can expect *all* the bears to pick that up.

**Comment by mvz** [comment]
@sils the main disadvantage for me would be that I can't look at my configuration and see at a glance which smells would be detected and which wouldn't. For me, that would be super-annoying.

For example, I may have:

```
attribute: true
bad_module_name: true
```

I'd have to actually look at the documentation to see that attribute setters would now *not* be detected, whereas 'bad module name' would.

Maybe I'm misreading the documentation and for all of them 'true' means the detector is enabled, but then your documentation is just very confusing. In that case, I also don't see why some keys start with 'allow_' and others don't.

**Comment by troessner** [comment]
>> We're actively not mirroring exactly the original settings. This way the same settings will be available for other bears for other languages and there's no need to read up on everything again if a similar feature set exists. When making an abstraction like this we sometimes have to invert the meaning.

I fully understand why you do that. I really do. But that's exactly the point that doesn't and that has made my shy away from tools like that. 

The overhead of the additional indirection (your format -> Reek format) works so long as you never have to actually tweak something. And then it gets super confusing. If I wouldn't know Reek I would be completely lost looking at your page.

**Comment by sils** [comment]
@mvz @troessner thanks so much for your time and feedback. I'll try to get it to the right places so we can work on that.

@mvz ok IIUC we'd mainly have to improve naming to improve on your points.

**Comment by mvz** [comment]
@sils Yes, naming, but also consistency. I also agree with @troessner on adding an extra layer of indirection in the configuration.
