### ISSUE TITLE
Document json (and possibly other) output formats

### ISSUE THREAD

**Issue by Makman2** [troessner/reek#938]
Hey there :)
I'm a maintainer from the [coala](http://coala-analyzer.org/) project, we have integrated your tool into our static code analysis, but we encountered some issues, and the json output format specification is nowhere described. I couldn't find something for other formats as well. Now I need to figure that own on my own.

I think you should document this properly, so everyone can make use of your output formats without encountering pitfalls :+1:

**Comment by troessner** [comment]
>> I think you should document this properly, so everyone can make use of your output formats without encountering pitfalls 👍

Agreed, I'll update our README soon, thanks for pointing this out ;)

**Comment by Makman2** [comment]
thanks for the quick response :D

**Comment by troessner** [comment]
Quick update: I'll look into this once we have finished #940

**Comment by troessner** [comment]
Closing this one with #993 merged. It's still not documented but now it's consistent and easy to find out yourself. You basically get what you see.
