### ISSUE TITLE
Give deppbot a shot

### ISSUE THREAD

**Issue by troessner** [troessner/reek#952]
https://www.deppbot.com/ -> wdyt?

**Comment by mvz** [comment]
Definitely seems worth a try.

**Comment by troessner** [comment]
I just subscribed the Reek repo but seems like we need a Gemfile.lock:

>> Please note that deppbot only works for GitHub repositories that contain a valid Gemfile and Gemfile.lock.

I could live with a checked in Gemfile.lock. WDYT @mvz ?

**Comment by mvz** [comment]
I think that would lead to endless churn on that file. Perhaps we should wait a little to see if deppbot will support not having the lock file? Or ask them :smile:.

**Comment by mvz** [comment]
Hm .. actually, looking at the FAQ, they only do a bundle update and don't touch the Gemfile. So I don't think this is very useful for Reek. I can see how this is useful for an app, maybe not so much for a gem.

**Comment by troessner** [comment]
Agreed, thats useless for us. Do you know any alternatives?

**Comment by mvz** [comment]
I think gemnasium offers this kind of service as a paid option. I don't know of any others.

**Comment by mvz** [comment]
I may try to create something to run locally. It's a problem I've been interested in for a while.

**Comment by troessner** [comment]
>> I may try to create something to run locally. It's a problem I've been interested in for a while.

Sounds like a good idea! We could then also automate those tedious version bumps that we only do of dependency bumps.

**Comment by troessner** [comment]
I just got an automated mail from deppbot:

------------------
Hi!

We are sorry that deppbot is unable to process your troessner/reek repository. As such, we have unsubscribed the repository.

The repository is a RubyGem which is not the best use case with deppbot.

If you have any questions about this, please let us know.

We hope you have enjoyed using deppbot so far.

Thank you!

Cheers, 
deppbot

**Comment by troessner** [comment]
I'll check out if gemnasium can do what we want.

**Comment by troessner** [comment]
>> I'll check out if gemnasium can do what we want.

Nope as well, closing this one, seems there is no good option here :(
