### ISSUE TITLE
Evaluate badges from the hamster gem

### ISSUE THREAD

**Issue by troessner** [troessner/reek#985]
I think that [the badges from the hamster gem](https://github.com/hamstergem/hamster) look pretty awesome. 
Let's evaluate if some of those make sense for us.

**Comment by mvz** [comment]
I can see that even the ones we already have look a lot better there.

We already have: 
* Travis build status
* Version
* Dependencies
* Docs
* Code Climate
* Code Beat

We need to evaluate:
* Downloads
* Tag
* Release
* License
* Discuss

**Comment by troessner** [comment]
I'd vote for 

* Downloads
* Tag
* License

**Comment by waldyr** [comment]
Should we also change the badge's style to the flat one?

**Comment by troessner** [comment]
>> Should we also change the badge's style to the flat one?

+1, looks easier on the eyes.
