### ISSUE TITLE
TooManyConstants Affects Parent Modules Even When Ignored

### ISSUE THREAD

**Issue by dgollahon** [troessner/reek#987]
Hi, I just upgraded to `4.2.0` from an older version and noticed the new `TooManyConstants` smell which, to me, has some unexpected behavior.

If I have a scenario like this

```ruby
module Foo
  class Bar
    A = 1
    B = 2
    C = 3
    D = 4
    E = 4
    F = 4
  end
end
```

and run `reek`, i get:
>   [2]:TooManyConstants: Foo::Bar has 6 constants [https://github.com/troessner/reek/blob/master/docs/Too-Many-Constants.md]

which is all well and good. If I change `Bar` to a module:

```ruby
module Foo
  module Bar
    A = 1
    B = 2
    C = 3
    D = 4
    E = 4
    F = 4
  end
end
```

I get
>   [1]:TooManyConstants: Foo has 6 constants [https://github.com/troessner/reek/blob/master/docs/Too-Many-Constants.md]
  [2]:TooManyConstants: Foo::Bar has 6 constants [https://github.com/troessner/reek/blob/master/docs/Too-Many-Constants.md]

Even when I add an ignore on `Bar`

```ruby
module Foo
  # ignore :reek:TooManyConstants:
  module Bar
    A = 1
    B = 2
    C = 3
    D = 4
    E = 4
    F = 4
  end
end
```

I still get
>   [1]:TooManyConstants: Foo has 6 constants [https://github.com/troessner/reek/blob/master/docs/Too-Many-Constants.md]

This extends for as many modules as you nest. Adding the ignore above `Foo` instead of above `Bar` suppresses both warnings in this case.

Is this a bug? Or am I missing some module-specific purpose here?

**Comment by troessner** [comment]
This most definitely is a bug - @waldyr can you take over?

**Comment by waldyr** [comment]
Sure

**Comment by dgollahon** [comment]
fastest bugfix response I can ever remember getting 🎉 i'll be on the lookout for the next version bump, thanks!

**Comment by troessner** [comment]
I assume @waldyr was having his well deserved good night sleep so I just went ahead and released 4.2.1 :)
@dgollahon can you please check if that works for you?

**Comment by dgollahon** [comment]
@troessner: works for the two cases in my codebase, thanks! :)

**Comment by troessner** [comment]
Great to hear that!
