### ISSUE TITLE
Make checking the warnings in smell detectors consistent across our specs

### ISSUE THREAD

**Issue by troessner** [troessner/reek#994]
Follow-up from #993 

In basically all of our specs for detectors we check the warnings for the right lines, the right message, the right parameters and so on. Unfortunately we do this in a lot of different ways and in different places (e.g. beginning of the spec vs the end vs scattered across the spec).

E.g. like this:

```Ruby
    context 'when a smells is reported' do
      let(:warning) do
        src = <<-EOS
        ...
        EOS
        Reek::Examiner.new(src, filter_by_smells: ['UtilityFunction']).smells[0]
      end

      it 'reports the line number of the method' do
        expect(warning.lines).to eq([1])
      end
  end
```

or like this (the worst in my mind)

```Ruby
      let(:warning) do
        src = 'def cc(arga = true) end'
        ctx = Reek::Context::MethodContext.new(nil, Reek::Source::SourceCode.from(src).syntax_tree)
        detector.inspect(ctx).first
      end

      it 'reports the right parameter' do
        expect(warning.parameters[:parameter]).to eq('arga')
      end
```

or like this (the most concise way but the error message isn't really helpful in case the spec fails):

```Ruby
  it 'reports a class without a comment' do
    src = 'class BadClass; end'
    expect(src).to reek_of :IrresponsibleModule,
                           lines: [1],
                           message: 'has no descriptive comment'
  end
```

We should fix this and come up with one way. 

Of the top of my head I can think of

* shared_examples 
* separate module we include in our spec_helper
* via our own spec matcher even though that sucks because you get a generic failure message when it fails

and then put this up at the top of each detector.

**Comment by troessner** [comment]
Before going on with this I'd rather wait for #992 and #993 to be merged.

**Comment by waldyr** [comment]
I really like the matcher. In my opinion with a better message it would be the best choice.

**Comment by mvz** [comment]
I would prefer using the matcher as well. Improving the matcher's message will then benefit us throughout our specs.

**Comment by troessner** [comment]
Alright, then let's improve the matcher and then use it consistently throughout our specs ;)

**Comment by troessner** [comment]
I'm so excited for this, fixing our broken spec set up will make developing Reek roughly a gazillion times faster ;)

**Comment by troessner** [comment]
@mvz why did you close this? 
Pull request #993 was the relevant here, and that one is still open :)

**Comment by mvz** [comment]
I think you mentioned the wrong issue in #1001 and GitHub did its magic.

**Comment by troessner** [comment]
Connected to #1001

**Comment by troessner** [comment]
Closing with #1056 merged!
