### ISSUE TITLE
Weird edge case bug in our specs

### ISSUE THREAD

**Issue by troessner** [troessner/reek#999]
I stumbled across this around a year ago in a new spec I was working on but managed to work around it. Now it happened again so I thought I'd document it here.
I happened while working [on this PR](https://github.com/troessner/reek/pull/997) with this innocent looking spec:

```Ruby
  describe '.run' do
    let(:examiner) do
      described_class.run('class C; def f; end; end')
    end

    context 'returns an Examiner' do
      it 'has the right smells' do
        expect(examiner.smells).to eq([])
      end
    end
  end
end
```

Running the spec like this:

````
DEBUG=1 bx rspec spec/reek/examiner_spec.rb:73
```

failed with:

```
Run options: include {:focus=>true, :locations=>{"./spec/reek/examiner_spec.rb"=>[73]}}
F

Failures:

  1) Reek::Examiner.run returns an Examiner has the right smells
     Failure/Error:
       def inspect(ctx)
         return [] if descriptive?(ctx) || ctx.namespace_module?
         expression = ctx.exp
         [smell_warning(
           context: ctx,
           lines: [expression.line],
           message: 'has no descriptive comment',
           parameters: { name: expression.name })]

     ArgumentError:
       wrong number of arguments (given 0, expected 1)
     # ./lib/reek/smells/irresponsible_module.rb:22:in `inspect'
     # ./spec/reek/examiner_spec.rb:76:in `block (4 levels) in <top (required)>'

Finished in 0.0037 seconds (files took 0.65824 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/reek/examiner_spec.rb:73 # Reek::Examiner.run returns an Examiner has the right smells
```

The error itself doesn't make any sense at this point. Also, look at the weird stacktrace which basically goes from IrresponsibleModule to the spec directly.

I think this has somehow something to do with rspec, because when I do it like this:

```Ruby
      it 'has the right smells' do
        smells = examiner.smells
        expect(smells).to eq([])
      end
```

the exception is raised in **this** line:

```Ruby
expect(smells).to eq([])
```

and not in this:

```Ruby
smells = examiner.smells
```

I can even insert a breakpoint before

```Ruby
expect(smells).to eq([])
```
and "cd" / walk around in `smells` itself with everything looking as expected.

Additionally the whole spec works if I do it like this:

```Ruby
it 'has the right smells' do
  smells = examiner.smells
  expect(smells[0].message).to eq('has no descriptive comment')
  expect(smells[1].message).to eq("has the name 'f'")
  expect(smells[2].message).to eq("has the name 'C'")
end
```

**Comment by troessner** [comment]
>>   ArgumentError:
       wrong number of arguments (given 0, expected 1)

Maybe it was a bad f***ing idea to name the entry point to our detectors `inspect` 😆 
Looking at the error it seems like Ruby somehow confuses it with `Object#inspect` when the weather in the Tundra is 10 degrees colder than usual and there is a blood moon on the horizon.
Let me check out if renaming it to something unambiguous fixes the problem.

**Comment by troessner** [comment]
Thinking about it, the rspec matcher

>> expect(smells).to eq([])

probably iterates over smells and then calls `inspect` on all entries. I mean, that still doesn't explain all of the other symptoms above but at one point you'll just have to let go ;)
Apart from that, we probably should still rename `inspect` to decrease confusion.
WDYT?

**Comment by mvz** [comment]
> probably iterates over smells and then calls inspect on all entries.

From a cursory look at this issue, yes, this is probably what happens, and it happens when the test fails.

> Maybe it was a bad f***ing idea to name the entry point to our detectors inspect :laughing:

Yes, we should fix that **now**.
